### ISSUE TITLE
Messed up precedence of feasts?

### ISSUE THREAD

**Issue by Sarto1** [DivinumOfficium/divinum-officium#1010]
I am a bit confused: Although tomorrow is the Stigmatisation of Francis, (II.) Vespers only commemorates the feast, while the office is of Joseph of Cupertino (I. Vespers). Shouldn't Joseph only be commemorated, since his feast is one day later? And on his feast, Vespers is of Januarius, although this is also only I. Vespers, and Joseph is only commemorated on his own feast.
The II. Vespers of Januarius is actually of Eustachius et al., although it should be their first Vespers.

Could this be an error, or is there an obscure rule where first Vespers of a duplex feast suddenly suppress second Vespers of another duplex feast?

I am, of course, talking about the Divino afflatu, and the 1910 version (the 1955 version got it right, as far as I have seen).

**Comment by APMarcello3** [comment]
The rubrics for all three feasts indicated (17, 18, 19 September) indicate that Vespers on those days is of the subsequent office, at least from the Little Chapter onwards.
