### ISSUE TITLE
Gradual was missing a line

### ISSUE THREAD

**Issue by josephtocci** [DivinumOfficium/divinum-officium#1018]
Yesterday, I was following along with Mass, and the English translation of the Gradual was missing text starting with Alleluia , Alleluia until the end of the Gradual.

Set the date to 10-14-2018 and go to the Sancta Missa with default settings and you will see it.
https://divinumofficium.com/cgi-bin/missa/missa.pl

**Comment by APMarcello3** [comment]
Fixed by 155910b
