### ISSUE TITLE
Divino afflatu: wrong readings in V week of October

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#1025]
With the *Divino afflatu* rubrics, the wrong readings being shown on some days in the V week of October.

Specifically, on Monday 10-29-2018, the readings start with 2 Mac 6:18-22 (correct)
http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=10-29-2018&command=prayMatutinum&version=Divino%20Afflatu&testmode=regular&lang2=English&votive=

But on Tuesday 10-30-2018 the same readings appear again, whereas they should be 2 Mac 7:7-12 and following:
http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=10-30-2018&command=prayMatutinum&version=Divino%20Afflatu&testmode=regular&lang2=English&votive=

On Saturday 3-11-2018 the readings that should have been shown on Tuesday finally appear instead of the correct readings for Saturday:
http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=11-3-2018&command=prayMatutinum&version=Divino%20Afflatu&testmode=regular&lang2=English&votive=

The correct readings for the day appear when newer rubrics are chosen. I don't see anything in the data files that could explain this. The only conditional is for the Tridentine office. I assume the problem must be in the Perl code.

**Comment by mbab** [comment]
This is result of files Tabulae/StrDA2018.
I don't know reason to put `10-30=105-1;;` as Oct 30 is Feria Tertia this year.
Also Trident files looks wrong lessons for this week.

**Comment by APMarcello3** [comment]
Should be fixed by 1c117f2fe.
