### ISSUE TITLE
12-29-2018 : wrong psalms for Compline (1960)

### ISSUE THREAD

**Issue by jperon** [DivinumOfficium/divinum-officium#1060]
[As can be seen here](http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=12-29-2018&caller=&command=prayCompletorium&version=Rubrics%201960&testmode=regular&lang2=Latin&votive=), psalms are from saturday, while they should be from sunday, as it's the octave of Christmas.

**Comment by APMarcello3** [comment]
Closed by 696ef1416

**Comment by jperon** [comment]
I think the fix isn't correct : with this, 12-30-2018 becomes [Die sexta post Nativitatem](http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=12-30-2018&caller=&command=prayMatutinum&version=Rubrics%201960&testmode=regular&lang2=Latin&votive=) instead of Dominica infra Octavam Nativitatis.
