### ISSUE TITLE
Spanish translation option doesn't work - English appears instead

### ISSUE THREAD

**Issue by matthewchoffman** [DivinumOfficium/divinum-officium#1061]

**Comment by APMarcello3** [comment]
Cf. issue #819. The Spanish translation is as yet incomplete and therefore defaults to English.

**Comment by matthewchoffman** [comment]
Why is there a selection for Spanish if Spanish is not yet available and inexplicably defaults to English? Shouldn't some message appear saying "in the works" or something to that effect, or perhaps just eliminating the option until it actually exists?

**Comment by DLakomy** [comment]
@APMarcello3 I think that this language option should indeed be removed from the lists, till at least the psalter is done. At the moment only two rarely used Commune files are translated, so almost everything is, in fact, in English.
