### ISSUE TITLE
Dominica infra Octavam Nativitatis

### ISSUE THREAD

**Issue by jperon** [DivinumOfficium/divinum-officium#1062]
This issue is a follow-up of #1060, to be sure it won't "disappear".

IMHO, 696ef14165f82d10521097002586fabbbbae7ce3 isn't the good fix (and probably should be reverted), as it puts days of the octave over the Sunday. The only special thing is that *Dominica infra Octavam Nativitatis* has 1st Vespers followed by Sunday Compline, even though it's 2nd class… So it behaves nearly as a 1st class feast. I don't know how to correctly fix it, but this is how I understand it.

**Comment by APMarcello3** [comment]
7d707e9 increases the rank of Nat1-0 to 6 in 1960 rubrics, which consequently will display a typo in the ranking. (An explicit edit to horascommon.pl did not resolve the problem.) This will likely have to be dealt with in calcalc.

**Comment by APMarcello3** [comment]
https://github.com/DivinumOfficium/divinum-officium/issues/1315

**Comment by APMarcello3** [comment]
Trient 1910: there should be a commemoration of the Sunday infra Octavam Nativitatis on 30 Dec 2019, feast of St Thomas, with lectio IX.

Also the psalms at vespers on the same day are wrongly taken from the common of martyrs instead of from the Nativity.
