### ISSUE TITLE
St. Agnes Jan 21 fifth reading of Matins lacks English translation in some settings

### ISSUE THREAD

**Issue by petermottola** [DivinumOfficium/divinum-officium#1065]
St. Agnes' (Jan 21) fifth reading of Matins has the responsory in English but no text whatsoever for the lesson itself, which begins "Hæc tredecim annórum martyrium fecisse traditur."  This affects only 1955 and earlier, but the text does exist in the system, because it is present in the Pre-Tridentine Monastic.  ("We learn by tradition that this holy martyr testified in the thirteenth year of her age.")

**Comment by APMarcello3** [comment]
Closed by 4f071a6.
