### ISSUE TITLE
Wrong responsory after second reading of matins 01-25 (Rubrics1960)

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#1067]
With the 1960 rubrics, the responsory after the second reading of matins on the conversion of St. Paul (01-25) should be "Bonum certámen certávi, …", which is Responsory2 of 06-30. Instead, Responsory3 ("Repósita est mihi …") of 06-30 is shown. I thought I could fix this by defining Responsory2 or Responsory3 in web/www/horas/Latin/Sancti/01-25.txt, but this had no effect.

**Comment by APMarcello3** [comment]
Should be fixed by 5d6169cbd.
