### ISSUE TITLE
Erratum for the Confiteor

### ISSUE THREAD

**Issue by frflorentg** [DivinumOfficium/divinum-officium#1071]
I would like to report a mistake which crept in here:

[http://divinumofficium.com/cgi-bin/missa/mpopup.pl?popup=Communio&rubrics=1&lang1=Latin&lang2=English](url)

It is written:

> S. Indulgéntiam, ✝︎ absolutionem et remissiónem peccatórum **nostrórum** tríbuat **nobis** omnípotens et miséricors Dóminus.

However, the _Ritus servandus_ precises as follow:

> _Tum sacerdos genuflectit, et manibus junctis vertens se ad populum in cornu Evangelii, dicit: Misereatur vestri, et Indulgentiam, absolutionem, et remissionem peccatorum **vestrorum,** etc.,_ … Rit. serv., titulum 10, § 6

It should thus be changed to:

> S. Indulgéntiam, ✝︎ absolutionem et remissiónem peccatórum **vestrórum** tríbuat **vobis** omnípotens et miséricors Dóminus.

**Comment by APMarcello3** [comment]
Closed by 365ad9da5.
