### ISSUE TITLE
Antiphons Clipped for Pre-1960

### ISSUE THREAD

**Issue by TheCardinalSystem** [DivinumOfficium/divinum-officium#1075]
Every hour loaded with the pre-1960 rubrics, except for Matins, only have half the antiphon. Matins has the antiphon repeated twice.

Screenshots:
![Image of Tertia](https://i.imgur.com/PlP5RZu.png)
![Image of Matins](https://i.imgur.com/oUUfv5d.png)

**Comment by APMarcello3** [comment]
This is not an error, as there are rubrics in the pre-1960 office for when the antiphon is to be said up to the asterisk and when it is said in its entirety. Please consult such a pre-1960 Breviarium Romanum for information and rubrical details.

**Comment by TheCardinalSystem** [comment]
> This is not an error, as there are rubrics in the pre-1960 office for when the antiphon is to be said up to the asterisk and when it is said in its entirety. Please consult such a pre-1960 Breviarium Romanum for information and rubrical details.

Is the repeated antiphon in Matins also intentional?

**Comment by gregordick** [comment]
> Is the repeated antiphon in Matins also intentional?

Yes: it's intoned by the cantors and repeated by the choir.
