### ISSUE TITLE
Site down? 

### ISSUE THREAD

**Issue by Saelo-Vaehrker** [DivinumOfficium/divinum-officium#1093]
I can't access the site as of this morning. I pulled up the Matins I had loaded for today from last night, finished it, and tried to open today's Lauds, and it wouldn't load.  Initially I was able to get to the main screen to select "Desktop" or "Mobile", but now I can't even get there.

**Comment by APMarcello3** [comment]
As of 12:20 GMT the site appears to be back up again. There was a known server issue.
