### ISSUE TITLE
Possible mistakes in Trident Quadragesime

### ISSUE THREAD

**Issue by mbab** [DivinumOfficium/divinum-officium#1094]
Duplex in Quadragesima is taken variable:

1. Vespera at Cinerum this year is from St, Thomas even next day is from Tempora https://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=03-06-2019&command=prayVespera&version=Trident%201570
2. March 12th office is taken from Sanctoral (St. Gregorii duplex) https://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=03-12-2019&version=Trident%201570
3. March 19th is from Temporal (St. Joseph duplex) https://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=03-19-2019&version=Trident%201570

**Comment by monicalabbao** [comment]
Do you have the Ordo for items 1, 2, and 3?

**Comment by APMarcello3** [comment]
These appear to be displaying correctly ...
