### ISSUE TITLE
Site Down - need help with hosting?

### ISSUE THREAD

**Issue by benyanke** [DivinumOfficium/divinum-officium#1113]
I'm not sure how to best contact you, so I'll just do it here.

I see www.divinumofficium.com is down. Do you need assistance with hosting or sysadmin work? I'd be happy to assist, or even donate resources and handle it completely. Feel free to ping me directly if interested, or respond here. My email is on my github profile.

In the meantime, I have a mirror up at: http://divinumofficium.benyanke.com/

**Comment by ursi-net** [comment]
Many thanks or the message and your help..hoping that divinumofficium is turning back soon.

in Christ

Urs Schöck

**Comment by APMarcello3** [comment]
I am on the phone with Bluehost as we speak. We are VPS customers and the server likely needs a hard reboot.

**Comment by APMarcello3** [comment]
As of 18:28 GMT the website should be functioning normally.
