### ISSUE TITLE
Error in 3rd responsory of Matins on Passion Sunday

### ISSUE THREAD

**Issue by fraAMP** [DivinumOfficium/divinum-officium#1114]
Ave Maria!
JMJFr

For: Rubrics 1960. Dominica I Passionis.
It seems that the final response for the 3rd lesson should include the part after the asterisk until the versicle. [as in other days]

That is, instead of:
"R. Quis dabit cápiti meo aquam, et óculis meis fontem lacrimárum, et plorábo die ac nocte? quia frater propínquus supplantávit me."

it should be:
"R. Quis dabit cápiti meo aquam, et óculis meis fontem lacrimárum, et plorábo die ac nocte? quia frater propínquus supplantávit me, * Et omnis amícus fraudulénter incéssit in me."

In Corde Immaculato

**Comment by APMarcello3** [comment]
Closed by 184c0909d.
