### ISSUE TITLE
Commemorations with Oratio Gregem do not have large initial

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#1115]
Commit 236daf9 fixed the "V." that was appearing at the beginning of commemorations from C4, but introduced a new problem, which is that offices containing a section like the following no longer have a large red initial at the beginning of the oration (which is *Gregem tuum*).

```
[Commemoratio]
!Commemoratio S. Hygini Papæ et Martyris
@Commune/C2:Oratio Gregem
```

I don't understand how this substitution works, because `Commune/C2.txt` doesn't contain an "Oratio Gregem" section, so I leave the problem to someone else to fix.

This is a less serious problem than the one the commit fixed, but it would good to fix the new problem as well for the sake of consistent typography. The problem appears with the 1960 rubrics at Lauds on the following days: 1-11-2018, 1-5-2018, 8-2-2018, 11-19-2018, 12-31-2018 (I test Lauds of every day of 2018).

**Comment by APMarcello3** [comment]
Should be fixed by f9f507c.
