### ISSUE TITLE
Italian Palm Sunday Mass does not 

### ISSUE THREAD

**Issue by rl1234567890** [DivinumOfficium/divinum-officium#1118]
The Italian Mass of Palm Sunday shows the Confiteor &c before the Introit. I don't understand what's wrong in the Italian Quad6-0r.txt It seems to follow the English. Can anybody help?

**Comment by rl1234567890** [comment]
The Italian Mass of Palm Sunday shows the Confiteor &c before the Introit. I don't understand what's wrong in the Italian Quad6-0r.txt It seems to follow the English. Can anybody help?

**Comment by APMarcello3** [comment]
This issue duplicates #927 and #371 and will be appended to the former.
