### ISSUE TITLE
Clean up dockerfile and docs

### ISSUE THREAD

**Issue by benyanke** [DivinumOfficium/divinum-officium#1121]
Minimum-viable-product Dockerfile was merged in #1120 , but need to do some additional documentation and cleanup around this.

 - [x] cleanup `docker/apache/httpd.conf` to only include the needed lines (should be able to get down to ~50 lines I think)
 - [x] Add init system instead of running `httpd-foreground` directly
 - [x] Review env vars / config needed to ensure it's fully covered
 - [x] Add healthcheck
 - [x] Add documentation to `README.md`
 - [ ] Lock perl to 5.10.1

**Comment by mbab** [comment]
Not checked yet, but Perl version **must be** same as on server which I believe is 5.10.1,
to be reliable for testing.

**Comment by hason** [comment]
#1122 solved 1st and 2nd item of the checklist.

**Comment by benyanke** [comment]
Thanks, @Hansen - I'll probably ramp down the healthcheck a little bit since the spider command is going to generate a lot of load.

I was going to ask about that @mbab - I'm working on a new server setup for Divinum Officium, I'll target that.

**Comment by mbab** [comment]
The server and docker version of perl should be same. If server is about to change there is no need to keep 5.10.1.

**Comment by benyanke** [comment]
That's what I was wondering - the docker version I've been working on is what will run on the server in production (when I'm done), so the docker version *is* the server version.

Is there a specific version of perl you'd like me to lock to, @mbab  , or is the latest ok, assuming everything works fine?

**Comment by fiapps** [comment]
Since my server (for the app Breviarium Meum) is stuck at Perl 5.8, I would really appreciate it if code incompatible with that version was not introduced.
