### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hason** [DivinumOfficium/divinum-officium#1125]
Is there any plan to develop a new version to solve architectural problems? There is a 4 year old branch https://github.com/DivinumOfficium/divinum-officium/tree/calcalc and a new project written in python https://github.com/gregordick/divinum-officium-alterum.

**Comment by APMarcello3** [comment]
We are composing a team to fix these problems, and we have a number of programmers interested. Please contact me at canon.missae@gmail.com for further details.
