### ISSUE TITLE
Credits for spanish version

### ISSUE THREAD

**Issue by jesav** [DivinumOfficium/divinum-officium#1142]
Good morning everyone:

I am the person in charge of the spanish translationof the breviary. Some weeks ago, I was contacted by Una Voce Sevilla society. They told me that a new translation of the breviary has been released recently, and put me in contact with publishers. They have given me permission to use their translation for this project.

Therefore, we should rewrite credits for the spanish translation. Since I am not sure about how to, I would request anybody to do so. Credits should be something like this:

Spanish translation is still under development. We sincerely thank publishers of Sapientia Sedei Filii (http://sededelasabiduria.es/western-union/) for their kindly offering of texts from their translation. The Spanish Vulgate translation used is the Petisto-Torres Amat Sacred Bible, revised by Alfonso Mª Gubianas O. S. B., 1935. For the Ordinary of the Mass, we have used the resources hosted on the Una Voce Sevilla website. The Proprium de Tempore are taken from Iglesia de El Salvador's parish blog El rincón litúrgico.

---

La traducción al español está aún en desarrollo. Agradecemos con sinceridad a los editores de Sapientia Sedei Filii (http://sededelasabiduria.es/western-union/) su ofrecimiento desinteresado de los textos de su traducción del breviario. La traducción de la Vulgata que aquí se emplea es la de la Sagrada Biblia Petisco-Torres Amat, en la revisión de 1935 de Alfonso Mª Gubianas, O.S.B. Para el Ordinario de la misa, se han empleado los recursos presentes en la página de la asociación Una Voce Sevilla. Los textos del Propio del tiempo proceden del blog de la Iglesia del Salvador, Toledo.

**Comment by APMarcello3** [comment]
Closed by 6673cb0b5.
