### ISSUE TITLE
Add touch icon for Apple devices when users "Add to Homescreen"

### ISSUE THREAD

**Issue by CodyTeague** [DivinumOfficium/divinum-officium#1168]
This is a pure nicety, but when a user on iOS adds this page to their homescreen, it just shows a preview of the page which isn't very aesthetic.

You can add some lines of code so that when they add it to the homescreen, it has a nice icon: 

Can see here some info: https://stackoverflow.com/questions/5110776/apple-touch-icon-for-websites

Would have to add something like this to homepage's html, with an image as well
```
<link rel="apple-touch-icon" href="/path/to/apple-touch-icon.png">
```

**Comment by APMarcello3** [comment]
Code added by 4cdc9bd.
