### ISSUE TITLE
Incorrect Collect Prayer for St. Peter on August 1st - Divino Afflato

### ISSUE THREAD

**Issue by acatholiclife** [DivinumOfficium/divinum-officium#1180]
The English translation of the first collect under the Divino Afflato rubrics on August 1st says:

"Thou art the shepherd of the sheep, and the Prince of the Apostles, and unto thee are given the keys of the kingdom of heaven."

That is incorrect. You need to insert the proper English translation of: "Deus, qui beátum Petrum Apostolum, a vinculis absolutum, illæsum abire fecísti: nostrórum, quæsumus, absolve víncula peccatórum; et ómnia mala a nobis propitiátus exclude."

**Comment by APMarcello3** [comment]
Closed by 1d8b10171.
