### ISSUE TITLE
Missing Symbol on Antiphon 3 Vespers Reduced 1955 on 8-28-19

### ISSUE THREAD

**Issue by acatholiclife** [DivinumOfficium/divinum-officium#1250]
At least on Reduced 1955 Vespers for 8/28/2019, the symbol to show that the first part of the antiphon is the same as the beginning of the psalm is missing. It is present on other such instances on that page. Just missing from Antiphon 3.

**Comment by APMarcello3** [comment]
Closed by f7a79f04c.
