### ISSUE TITLE
Final Psalm in 8/9/2019 Error in DA for Vespers

### ISSUE THREAD

**Issue by acatholiclife** [DivinumOfficium/divinum-officium#1251]
The final psalm should be psalm 116, not psalm 115. Psalm 115 is for 2nd Vespers.

**Comment by acatholiclife** [comment]
Loco praecedentis Psalmi 116 "Laudate Dominum", in Vesperis Festorum interdum dicitur sequens Psalmus 115.


But first vespers isn't one of those times.

**Comment by APMarcello3** [comment]
It normally displays as such, but in 2019, due to an internal bug, it did not.

**Comment by acatholiclife** [comment]
This has been corrected going forward then and may be closed?
