### ISSUE TITLE
German texts

### ISSUE THREAD

**Issue by Sarto2** [DivinumOfficium/divinum-officium#1286]
As a native German, I can say that the German translations are absolutely horrible, and make no sense. If I may, I would like to help by providing official translations from approved books. Also, I can add a German translation of the psalms according to a Bible translation approved by the Holy See (Allioli Bible).

If someone were so kind as to give me instructions on how to work on the files, I would go right to work :-)

**Comment by APMarcello3** [comment]
Please email me for details. canon.missae@gmail.com
