### ISSUE TITLE
Dynamic date

### ISSUE THREAD

**Issue by Gualterius** [DivinumOfficium/divinum-officium#1289]
On my smartphone I use a bookmark and a shortcut on the startscreen to the Breviary which I now successed to have it actualized everyday by replacing the date in the URL by {datetime;MM-dd-YYYY}. 
In order to save time and data volume, I'd like to anticipate next day's matutinum in the URL. The only hint I found ({datetime;MM-dd-YYYY;1}) doesn't work. Any idea?

**Comment by DLakomy** [comment]
I'm unsure whether I can help, but could you please indicate the source of the hint you've found? I mean `{datetime;MM-dd-YYYY;1}`.

**Comment by Gualterius** [comment]
Try this one:https://www.uptrends.com/support/kb/monitor-settings/dynamic-date-notation-in-url-and-post-contentThank you for trying!Emissum per accessum mobilem ad interrete
-------- Ursprüngliche Nachricht --------Von: DLakomy <notifications@github.com> Datum: 29.11.19  11:17  (GMT+01:00) An: DivinumOfficium/divinum-officium <divinum-officium@noreply.github.com> Cc: Gualterius <walter1956@arcor.de>, Author <author@noreply.github.com> Betreff: Re: [DivinumOfficium/divinum-officium] Dynamic date (#1289) I'm unsure whether I can help, but could you please indicate the source of the hint you've found? I mean {datetime;MM-dd-YYYY;1}.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DivinumOfficium/divinum-officium/issues/1289?email_source=notifications\u0026email_token=AN3GFLMKCMJZ6HXP43FFVQLQWDTWTA5CNFSM4JQVWGFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFOO4PY#issuecomment-559738431",
"url": "https://github.com/DivinumOfficium/divinum-officium/issues/1289?email_source=notifications\u0026email_token=AN3GFLMKCMJZ6HXP43FFVQLQWDTWTA5CNFSM4JQVWGFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFOO4PY#issuecomment-559738431",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by DLakomy** [comment]
If I understand correctly what I've read on the website you've mentioned, the `{datetime;MM-dd-YYYY;1}` substitution is a feature of the uptrends' monitor software. It's a coincidence it works here. I've just checked, that if you type `{whatever}`as a date (it must be in curly braces), the current date is selected.

So the solution would be the implementation of a mechanism in the DO's CGI scripts, which would render it possible to choose the date relative to the current time. Or to solve it client-side, via some JS (a user-specific solution). Or to provide the link allowing to anticipate Matins (probably the best solution, the most readable one, but the most invasive one as well if it's to be done globally, not in just one place).

**Comment by ajmalton** [comment]
Very late to the party: but would a link to tomorrow's Matutinum be sufficient? Placed after the Completorium link?  If it didn't have to be too smart about Nativity or Pasch, just link directly to Matins for tomorrow's date, I think it would be pretty straightforward.

**Comment by FAJ-Munich** [comment]
Once #4193 is deployed, use following for bookmarking:

- Tomorrow's matins:  https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=crastina&command=prayMatutinum
- Today's office: https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=hodie&command=
