### ISSUE TITLE
Store calendar information separately from individual days' data files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DivinumOfficium/divinum-officium#129]
```
Currently, to resolve occurrence and concurrence, the program has to query each 
of the files for the relevant offices. Storing the necessary information 
centrally would:

1. allow the liturgical day to be determined before loading the data files 
(useful for evaluating conditions that depend on the day);
2. speed up the calculation of the day (see below); and
2 bis. remove a significant obstacle to the timely determination of the 
kalendar for an arbitrary date.

Regarding no. 2: this is less of an advantage when actually compiling an hour, 
as the program will have to subsequently access all/most/some of the files 
anyway, but it should help the monthly kalendar display significantly.

The beginnings of this exist in the K*.txt files. We'd need to add rank 
information and data on the temporal cycle, plus other odds and ends.

This is probably not something to be embarked upon any time soon, but I thought 
it was worth bearing in mind for the future.
```

Original issue reported on code.google.com by `igregord` on 30 Jan 2012 at 11:08

**Comment by APMarcello3** [comment]
January 21, 2012 Divino Afflatu Vespers: Commemoration of St. Agnes as the 
preceding Office should come before SS Vincent & Anastasius.

As such, the rule is that except in Tridentine 1570, the commemoration of the 
current office should come before the subsequent office.  In 1570 rubrics, the 
commemorations are based upon the rank of the Office.

**Comment by APMarcello3** [comment]
Sometimes, only one of the office and Mass differs between different sets of 
rubrics, with the other being unchanged. In the current system, if we provide a 
separate file for one, we must also do so for the other, leading to redundancy; 
specifying Mass and office separately (at least optionally) would avoid this. (Cf. issue #149)
