### ISSUE TITLE
Duplicate files in project

### ISSUE THREAD

**Issue by mbab** [DivinumOfficium/divinum-officium#1291]
There are around 14000 files in horas directory and ~5000 of this are copies of (mainly) Latin files.
(3000 are in croatian directory).
Should it be:
cleaned by vernaculars maintainers
cleaned by me
keeped as it is?

**Comment by APMarcello3** [comment]
@mbab Please clean.

**Comment by farribeiro** [comment]
This issue is not good for the project, if not from maintainers because the git objects in the project are still taking up space, especially if you want to untrack them
