### ISSUE TITLE
Any way to extract and compile specific parts of the Office?

### ISSUE THREAD

**Issue by jz533** [DivinumOfficium/divinum-officium#1295]
Not so much of an issue perse, but I did not know where else to ask this. Is there any way to extract and compile on specific parts of the Office? I am new to coding but have a little experience.

In my case, I would like to extract _only_ the non-Scriptural Lessons of Matins from the 1955 or earlier Breviary in English. If need be, I can live with having the Scriptural Lessons included. I am looking to create a physical book, or perhaps an ebook, containing only the homilies and legends to supplement the shortened 1960 Office I pray from a real Breviary (I am sure most of you are familiar that the lessons were often considerably shortened in the 1960s rubrics). So there would need to be the Lessons from the Commons, Proper of the Season, Proper of the Saints, etc. Is something like this theoretically possible? I have browsed around the files here, and found where the Lessons are located, but I have no idea how I would go about extracting them.

**Comment by APMarcello3** [comment]
Cf. issue #1300
