### ISSUE TITLE
Mistreated occurence

### ISSUE THREAD

**Issue by DLakomy** [DivinumOfficium/divinum-officium#1304]
Tomorrow (8th Dec 2019), according to DO, Rubrics 1960, it's _In conceptione+Commemoratio: Dominica II Adventus_.

According to the table of occurence (http://divinumofficium.com/www/horas/Help/rubrics.html) the feast should be transferred, not supersede the Sunday. _Universal 1st cl. feast_ and _1st class Sunday_ give 7, ie. _Office of 2nd, transfer of other_.

**Comment by APMarcello3** [comment]
Please see RG 15: 15. In a case of occurrence, a Sunday of the 1st class is preferred to any feast whatsoever.
The feast of the Immaculate Conception of the Blessed Virgin Mary, however, is preferred to the Sunday of Advent on which it may occur.
With regard to concurrence, the rules given in nos. 104-105 will be observed.

**Comment by DLakomy** [comment]
Many thanks. It's ok then.
