### ISSUE TITLE
Double Amen in English Advent Feria Prayer

### ISSUE THREAD

**Issue by dokeefe9999** [DivinumOfficium/divinum-officium#1307]
Stir up our hearts, O Lord, to make ready the ways of thine Only-begotten Son, that by His coming our minds being purified, we may the more worthily give up ourselves to thy service:
Who with thee liveth and reigneth, in the unity of the Holy Spirit, one God, world without end. Amen.
R. Amen

**Comment by APMarcello3** [comment]
Closed by f8fc2b2
