### ISSUE TITLE
Feast of Stephen final prayer for the Proper seems to be missing text

### ISSUE THREAD

**Issue by dokeefe9999** [DivinumOfficium/divinum-officium#1311]

**Comment by dokeefe9999** [comment]
It looks like the final prayer is missing:

"Jesus Christ, Your Son", at the end of

Grant us, we beseech thee, O Lord, so to imitate what we revere, that we may learn to love even our enemies; for we celebrate the heavenly birthday of him who knew how to pray for his very persecutors to our Lord

**Comment by dokeefe9999** [comment]
It looks like the final prayer is missing:

"Jesus Christ, Your Son", at the end of

Grant us, we beseech thee, O Lord, so to imitate what we revere, that we may learn to love even our enemies; for we celebrate the heavenly birthday of him who knew how to pray for his very persecutors to our Lord

**Comment by APMarcello3** [comment]
Closed by bc6f0f6
