### ISSUE TITLE
Psalter error, 1960, Thursday Matins, psalm 68

### ISSUE THREAD

**Issue by d-a-s** [DivinumOfficium/divinum-officium#1321]
Hello, I'm writing to report an error in Thursday Matins (Feria quinta ad Matutinum). I have checked several old breviaries, and **Psalmus 68, ii** should begin with the verse `In multitudine misericordiae tuae...`.

I believe the error can be traced to this file/line:
https://github.com/DivinumOfficium/divinum-officium/blob/master/web/www/horas/Latin/Psalterium/Psalmi%20matutinum.txt#L97

The numbering of verses is apparently being done by the "bible" verses, and in this case the split happens mid-verse. In other words, verse 14a (Ego vero orationem...) should be the last verse of `68, i`, and `68, ii` should begin with 14b.

So really, these lines should read something like:
```
Salvum me fac, * Deus, quóniam intravérunt aquæ usque ad ánimam meam.;;68(2-14a)
Propter inimícos meos * éripe me, Dómine.;;68(14b-29)
```
rather than `2-13` and `14-29`

I would imagine the 14a and 14b for these verses would also need to be added in the psalm text files, if that's safe to do. I tried looking through the code but I'm not very familiar with Perl, and had a bit of a tough time following it.

I did a search before creating this issue to see if anyone else has reported an issue with psalm 68, and was rather surprised that I didn't find anything. I'm sorry if there was already an issue for this and I missed it.

**Comment by APMarcello3** [comment]
Closed by d15630f. The numbering is off from the Scriptural numbering but is accurate now in terms of printed offices.
