### ISSUE TITLE
Absolution of the Ministers at Mass

### ISSUE THREAD

**Issue by rl1234567890** [DivinumOfficium/divinum-officium#1322]
Although in the 1962 (and earlier) Roman Missal we have 

> Misereátur **vestri** omnípotens Deus, et, dimíssis peccátis **vestris**, perdúcat **vos** ad vitam ætérnam.

on the site we have:

> Misereátur nostri omnípotens Deus, et, dimíssis peccátis nostris , perdúcat nos ad vitam ætérnam.

If we select Rubrics, it appears as:

> Misereátur nostri vestri omnípotens Deus, et, dimíssis peccátis nostris vestris, perdúcat nos vos ad vitam ætérnam.

With vestri, vestris, and vos in red as if they were rubrics. 

I propose we change the text in Ordo.txt and wherever else it appears from

> S. Misereátur nostri (vestri) omnípotens Deus, et, dimíssis peccátis nostris (ve stris), perdúcat nos (vos) ad vitam ætérnam.

to

> S. Misereátur vestri omnípotens Deus, et, dimíssis peccátis vestris, perdúcat vos ad vitam ætérnam.

Will that break anything?

**Comment by APMarcello3** [comment]
Closed by 795483c8b.
