### ISSUE TITLE
Unresolved reference in Officium parvum Beatae Mariae Virginis Jan. 7th 2020

### ISSUE THREAD

**Issue by svieira** [DivinumOfficium/divinum-officium#1323]
> Officium parvum Beatae Mariae Virginis Tempora Nativitatis ~ Commemoratio
> Ad Completorium  1960 Newcalendar
> 1-7-2020

Latin and English include the following `Ant. @Sancti/01-01:Ant 3`:

> Canticle Nunc dimittis
> Ant. @Sancti/01-01:Ant 3
> Canticle of Simeon [4]

I went looking to see how this is assembled so I could put together a PR myself, but I wasn't able to trace how these files get assembled.

**Comment by APMarcello3** [comment]
Closed by 7c0d6cefe.
