### ISSUE TITLE
English Translation for Vespers 1/12/2020 under DA Incorrect

### ISSUE THREAD

**Issue by acatholiclife** [DivinumOfficium/divinum-officium#1324]
One of the collects for Vespers for January 12th under DA is showing in Latin and not English on the English side. The collect that needs to be properly translated is:

Fili, quid fecísti nobis sic? Ego et pater tuus doléntes quærebámus te. Quid est quod me quærebátis? nesciebátis quia in iis, quæ Patris mei sunt, opórtet me esse?

**Comment by APMarcello3** [comment]
Closed by b1026f93e
