### ISSUE TITLE
french traduction for psalms

### ISSUE THREAD

**Issue by sapinpol** [DivinumOfficium/divinum-officium#1325]
I suggest to change the french traductions of the 150 psalms to Fillion version because the current ones are infested with false or counter meaning compared to latin and english. As an example see for yourself psalm 143.
I commit the changes in my local repo and zipped the 150 files :
[psalms1-150-FrenchbyFillion.zip](https://github.com/DivinumOfficium/divinum-officium/files/4053783/psalms1-150-FrenchbyFillion.zip)

**Comment by APMarcello3** [comment]
Merci pour vos corrections. J'ai changé les fichiers.

**Comment by sapinpol** [comment]
Merci !
