### ISSUE TITLE
ical generation

### ISSUE THREAD

**Issue by benyanke** [DivinumOfficium/divinum-officium#1329]
Since the calendar logic exists already, I would really love to see a function which could take advantage of this, and return a link which could be put into a calendar program reading ical format, to provide the liturgical year in your calendar or other iCal client.

For example: the following link could return an ical formatted calendar feed, containing calendar "events" with the liturgical day information from the previous 30 days and the following year.

https://divinumofficium.com/cgi-bin/ical.pl?calendar=trident-1910&daysBefore=30&daysAfter=360

**Comment by sjlehn** [comment]
I would also love to see the ical include pagination for those versions that have published texts (e.g. the Antiphonale and Monastic Diurnal for the monastic version, and whatever the currently published version of the 1962 Roman Breviary is) - essentially making it a digital Ordo. If/when I find some time I might try to look into it myself. 

If #626 is any indication, this may be challenging technically in addition to the decidedly non-trivial work of figuring out the page numbers and where they should be stored.
