### ISSUE TITLE
Final prayer conclusion for S. Petri Nolasci 1/28

### ISSUE THREAD

**Issue by dokeefe9999** [DivinumOfficium/divinum-officium#1342]
The final prayer for the hours of this feast don't mention our Lord Jesus Christ, but they end with "Qui vivis et regnas...".  Should they end with "Per Dominum nostrum Iesum Christum, Filium tuum..."? Or is Jesus in the prayer by implication?

**Comment by APMarcello3** [comment]
This is how the prayer is listed in the printed editions of the breviary and missal.
