### ISSUE TITLE
traduction francais Fillion suite

### ISSUE THREAD

**Issue by sapino** [DivinumOfficium/divinum-officium#1378]
psalms 1-150 : correction de multiples césures, ligne vides enlevées, orthographe.
psalms 210-246 : traduction Fillion comme pour les psaumes 1-150

[psalms1 Francais V2.zip](https://github.com/DivinumOfficium/divinum-officium/files/4139522/psalms1.Francais.V2.zip)

**Comment by APMarcello3** [comment]
Fermé par b629d8dd6951faec723ccd39945b1c6f4a61cd06
