### ISSUE TITLE
Accents in forms of restituo

### ISSUE THREAD

**Issue by rl1234567890** [DivinumOfficium/divinum-officium#1386]
The accents in forms of the verb [restituo](https://logeion.uchicago.edu/restituo) seem wrong to me. 
In web/www/horas/Latin/Sancti/02-05.txt we have **restítuere** and in web/www/horas/Latin/Sancti/11-24.txt we have **restítueret**. However, the u is not a semivowel v. Hence, I believe the accents should be **restitúere** and **restitúeret**. Please correct me, if I am wrong.

**Comment by APMarcello3** [comment]
Closed by 6bdf85bb4.
