### ISSUE TITLE
Remplacement de "allelúja" par "alleluia" et "Allelúja" par "Alleluia" pour les bréviaires français et latin

### ISSUE THREAD

**Issue by sapino** [DivinumOfficium/divinum-officium#1406]
[Francais.zip](https://github.com/DivinumOfficium/divinum-officium/files/4201120/Francais.zip)

**Comment by sapino** [comment]
[Latin.zip](https://github.com/DivinumOfficium/divinum-officium/files/4201128/Latin.zip)

**Comment by APMarcello3** [comment]
Accepté pour le français, mais il faut garder les accents pour le latin.

**Comment by sapino** [comment]
Mea culpa ! Voici le répertoire Latin avec "Allelúia" et "allelúia". Pour le répertoire Français, finalement je vous propose aussi "Allelúia" et "allelúia" avec accents car à part le sous-répertoire sancti tout ou presque est en latin.
[Francais-allelúia.zip](https://github.com/DivinumOfficium/divinum-officium/files/4203685/Francais-alleluia.zip)
[Latin-allelúia.zip](https://github.com/DivinumOfficium/divinum-officium/files/4203686/Latin-alleluia.zip)
