### ISSUE TITLE
1570 Tridentine 

### ISSUE THREAD

**Issue by stmargaret** [DivinumOfficium/divinum-officium#1468]
On the feast of st. Thomas Aquinas I found in Nocturn I  the Lection is Sirach when it’s really the book of wisdom chapter 4

**Comment by stmargaret** [comment]
Which I think there is a mistake for Commune confessoris non pontificis

**Comment by stmargaret** [comment]
It is also missing parts of the sermon of St.Leo Of the transfiguration today

**Comment by APMarcello3** [comment]
Please provide justification. The lections are from the Commune Doctorum, as Aquinas was declared a doctor in 1567.

**Comment by stmargaret** [comment]
I have a 1869 breviary and it calls him confessor

**Comment by stmargaret** [comment]
Your 1910 rubric has the same
