### ISSUE TITLE
"1960 New Calendar"

### ISSUE THREAD

**Issue by Sarto2** [DivinumOfficium/divinum-officium#1469]
Just a quick question: Since the version of the Breviary "1962 New Calendar" isn't an official version of the Breviary, and since it is an experiment - as far as I have come to understand it - should it really be included on the page? I personally find it highly irritating, and I don't really see the use of it. The 1960 version is the last authorized version of the Breviary anyway.

**Comment by APMarcello3** [comment]
The 1960 Newcalendar option has been reformatted to simply be the 1960 calendar with USA propers and a few new offices. It is an option, and it is being kept on the site as it was the original design of the site to respect the wishes of the late Laszlo Kiss.
