### ISSUE TITLE
Suffragia are missing in Passiontide

### ISSUE THREAD

**Issue by peterdiekertz** [DivinumOfficium/divinum-officium#1525]
Tridentine 1570, 1910, and Divino:
In Passiontide, the suffragia at Lauds and Vespers are not shown for Dominica and feriae. I suppose this is because they are called "semiduplex".

**Comment by APMarcello3** [comment]
This is not an error, at least for Divino Afflatu rubrics:

"XXXV. De Commemorationibus communibus seu Suffragiis Sanctorum

1. Commemorationes communes, seu Suffragia de Sanctis, que habentur in
Psalterio post Vesperas Sabbati, dicuntur in fine Vesperarum, et Laudum, ab
Octava Epiphaniae usque ad Dominicam Passionis exclusive"
