### ISSUE TITLE
Prime Psalms: Tridentine 1570 and 1910

### ISSUE THREAD

**Issue by PaulDang1** [DivinumOfficium/divinum-officium#1532]
Holy Thursday and Good Friday: For Prime, it should not be the Ferial Psalms, but the Festal Psalms. So no Psalm 22 on Thursday, and Psalm 21 on Friday. Thanks.

**Comment by APMarcello3** [comment]
December 30, 2020 (transferred Dominica Infra Octavam) no ferial Psalm said, only 53 and 118A and 118B.
