### ISSUE TITLE
Missing commemoration of the vigil of St Matthias at Mass

### ISSUE THREAD

**Issue by gregordick** [DivinumOfficium/divinum-officium#1568]
Outside of leap years, the vigil of St Matthias ought to be commemorated in the Mass of St Peter Damian on the 23rd, but it is not. (It is commemorated correctly at Lauds outside of Lent.)

Reproducer: https://www.divinumofficium.com/cgi-bin/missa/missa.pl?date=02-23-2019

(Split from #465.)

**Comment by gregordick** [comment]
Splitting multiple offices occurring on the same day into separate files, thus allowing them to be transferred separately, is the approach that I've taken for #443.  This could be applied to other problematic cases, too.

**Comment by APMarcello3** [comment]
#1776 addressed by 8eb0c0486.

**Comment by APMarcello3** [comment]
#1917 addressed by 58769a19e.
