### ISSUE TITLE
Wrong Magnificat Antiphon for Vespers on Quasimodo Monday 

### ISSUE THREAD

**Issue by roseannetsullivan** [DivinumOfficium/divinum-officium#1612]
Latin and English Magnificat Antiphons are not the same on Quasimodo Monday Antiphon for Vespers.

Ant. Pax vobis, ego sum, allelúia: nolíte timére, allelúia.
Ant. He who broke the power of hell, subdued himself to the Holy Cross, being girded with power, he rose the third day, alleluia.

**Comment by APMarcello3** [comment]
Closed by a41d3d941.

**Comment by roseannetsullivan** [comment]
Please explain why you closed this? Did you fix the error?

**Comment by roseannetsullivan** [comment]
i just checked. The Latin antiphon for the Magnificat is different from the English on your Vespers for Quasimodo Monday.
