### ISSUE TITLE
Antiphons and psalms for single nocturn Matutinum

### ISSUE THREAD

**Issue by jakubjelinek** [DivinumOfficium/divinum-officium#1617]
I see e.g. for today's Matins in Reduced 1955 mode 9 psalms, is that on purpose?
Seems the first 3 psalms (and if I choose some random Feria with single nocturn like Sep 4th this year, antiphons too) match what is e.g. in Nocturnale Romanum 2002, but the next 3 are what is written for the second nocturn and last 3 for the third nocturn on that day.  I've never seen 9 psalms in a single nocturn yet, 3 or 6 are common.

**Comment by APMarcello3** [comment]
This is accurate for the 1955 books. The 2002 books are not used by this site.
