### ISSUE TITLE
fails in completorium in Spanish

### ISSUE THREAD

**Issue by Darius2309** [DivinumOfficium/divinum-officium#1620]
Is failing to enter completorium in Spanish.

**Comment by APMarcello3** [comment]
The Spanish translation is not yet complete.

**Comment by Darius2309** [comment]
> The Spanish translation is not yet complete.
I know, but before you could enter even if you didn't see everything in Spanish.
I know, but before you could enter even if you didn't see everything in Spanish. I would like to collaborate for the Spanish translation, I have the necessary materials to do it.
