### ISSUE TITLE
Comm. of the Octave of St. Joseph on Doubles of the 2nd Class

### ISSUE THREAD

**Issue by acatholiclife** [DivinumOfficium/divinum-officium#1655]
Under DA, May 3rd is the Finding of the Holy Cross (a Double of the II Class). A commemoration of a common octave should not be made on Doubles of the I or II Class. Yet I noticed at Lauds a Comm of the Octave of St. Joseph. Likewise, this was also included last night on Vespers on May 2nd.

The Octave shouldn't be commemorated on these intra octave days.

**Comment by acatholiclife** [comment]
Any update on if this will be corrected for future years when this occurs?

**Comment by APMarcello3** [comment]
According to the Ordo provided here, what the site displays is correct: http://www.traditio.com/calendar/cal2005.pdf

**Comment by acatholiclife** [comment]
See attached

**Comment by acatholiclife** [comment]
The concurrence table here shows otherwise: https://divinumofficium.com/www/horas/Help/Rubrics/occurrence.gif
