### ISSUE TITLE
Missing form labels and alternative text

### ISSUE THREAD

**Issue by martineizayaga** [DivinumOfficium/divinum-officium#1658]
- /cgi-bin/horas/Ckalendar.pl
    - [x] add 2 form labels
- /cgi-bin/horas/Cofficium.pl
    - [x] add 5 alternative text
    - [x] add 6 form labels
- /cgi-bin/horas/kalendar.pl 
    - [x] add 1 form label
- /cgi-bin/horas/officium.pl
    - [x] add 5 alternative text
    - [x] add 6 form labels
- /cgi-bin/missa/Ckalendar.pl
    - [x] add 2 form labels
- /cgi-bin/missa/Cmissa.pl
    - [x] add 7 form labels
- /cgi-bin/missa/kalendar.pl
    - [x] add 1 form label
- /cgi-bin/missa/missa.pl
    - [x] add 7 form labels

**Comment by martineizayaga** [comment]
Could I be assigned this issue?

**Comment by APMarcello3** [comment]
Please proceed.

**Comment by APMarcello3** [comment]
This commit caused a serious crash.

**Comment by martineizayaga** [comment]
Why was the pull request reverted? If you can, please revert the revert. I’m done with this issue

**Comment by APMarcello3** [comment]
It would be very helpful to us if you could provide a more detailed explanation of what your changes are and what they are aiming to accomplish. I am not sure I am seeing what the aim is of the "form labels".

**Comment by martineizayaga** [comment]
Ah! For sure. I was following the accessibility web standard that every form input should have a corresponding label.
https://www.w3.org/WAI/tutorials/forms/labels/#associating-labels-explicitly

I then hid the labels visually, that way the design is the same, but people with screen readers can now tell what kind of input they are interacting with. I hid the labels with the class `.offscreen` that's taken from this url: https://www.30secondsofcode.org/css/s/offscreen/

**Comment by martineizayaga** [comment]
I also made sure to add empty alt text's for decorative images.
https://www.w3.org/WAI/tutorials/images/decorative/#image-used-as-part-of-page-design

**Comment by APMarcello3** [comment]
Okay. If this is ready to implement, could you submit a new pull? Thank you.
