### ISSUE TITLE
Generic Prayers for Saints Feast Days in Sancti Missa (English)

### ISSUE THREAD

**Issue by dokeefe9999** [DivinumOfficium/divinum-officium#1668]
The English translation of many prayers for Saints feast days show a "generic" prayer that does not mention the saint(s) name(s).  Can I replace these (as I find them) with an appropriate English translation from an approved source?  (If so, I have the Baronius MMIX hand missal for the 1962 Mass, but an online source would be easier and more accurate to work with.)

**Comment by APMarcello3** [comment]
Replace as need be.
