### ISSUE TITLE
Dominica IV Post Pascha Offertory translation in English does not match Latin 

### ISSUE THREAD

**Issue by roseannetsullivan** [DivinumOfficium/divinum-officium#1687]
Dominica IV Post Pascha Dominica IV Post Pascha Offertory translation in English does not match Latin 
Iubiláte Deo, univérsa terra, psalmum dícite nómini eius: veníte et audíte, et narrábo vobis, omnes qui timétis Deum, quanta fecit Dóminus ánimæ meæ, allelúia.
Shout with joy to God, all the earth, sing ye a psalm to his name; give glory to his praise. O look upon me, and have mercy on me: give thy command to thy servant, and save the son of thy handmaid, alleluia. 
The second verse of the English should begin "Come and hear ..." Not "O look upon me ..."

**Comment by APMarcello3** [comment]
Closed by dfa8ca9

**Comment by roseannetsullivan** [comment]
Why did you close this without fixing it?  The second verse in the Offertory the Latin version reads: "veníte et audíte, et narrábo vobis, omnes qui timétis Deum, quanta fecit Dóminus ánimæ meæ, allelúia." The English is a mistake: "O look upon me, and have mercy on me: give thy command to thy servant, and save the son of thy handmaid, alleluia." The second verse in English should be: "come and hear, and I will tell you, all ye that fear God, what great things the Lord hath done for my soul. Alleluia."
