### ISSUE TITLE
1960-Newcalendar and 1964-1967 Missa should default to 1960 rubrics

### ISSUE THREAD

**Issue by APMarcello3** [DivinumOfficium/divinum-officium#1689]
Currently, these structures default to Divino Afflatu, which is incorrect.

**Comment by mbab** [comment]
This patch makes *Newcal* transfer files obsolete but I keeping them now as they are slightly different from their *1960* analogue. If they are proper then yearly transfer can be revoked by another patch.
@APMarcello3 please give me know how to proceed.

**Comment by APMarcello3** [comment]
We will need to keep a mechanism in place so that 1960-Newcal transfer files are independent, since 1960 Newcal will include new saints' feast days as indicated in Cum Sanctissima.
