### ISSUE TITLE
5/15 Missa Lectio is labeled Sapiéntiæ but the reading is Ecclesiasticus

### ISSUE THREAD

**Issue by dokeefe9999** [DivinumOfficium/divinum-officium#1700]

**Comment by APMarcello3** [comment]
<img width="419" alt="Screen Shot 2020-05-15 at 9 56 44 AM" src="https://user-images.githubusercontent.com/11463422/82058211-6e692e80-9692-11ea-95ee-d194dffe3ccb.png">

This is correct.

**Comment by dokeefe9999** [comment]
Thanks!

Is that an old error or was Ecclesiasticus called Sapiéntiæ in the vulgate?

________________________________
