### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by s0n0fg0dinri7** [DivinumOfficium/divinum-officium#1712]
In the Breviary there are some psalms and prayers that are not translated into Spanish or are not well translated and the Missal directly does not work the Latin-Spanish option.

**Comment by APMarcello3** [comment]
The Spanish translation is incomplete. It is a work in progress.

**Comment by s0n0fg0dinri7** [comment]
I'm glad to hear they' re working on the Latin-Spanish translation.
