### ISSUE TITLE
Vigil of Pentecost has regular Saturday readings in the Little Hours.

### ISSUE THREAD

**Issue by dokeefe9999** [DivinumOfficium/divinum-officium#1743]
Have never seen anything but Psalm 118 for Terce, Sext and None on a I. classis feast.  Are these regular Saturday Psalms correct? Or is the feast class incorrect?

**Comment by APMarcello3** [comment]
<img width="476" alt="Screen Shot 2020-05-30 at 2 30 08 PM" src="https://user-images.githubusercontent.com/11463422/83336519-20534e00-a282-11ea-9903-ad4965102aef.png">
