### ISSUE TITLE
Matutin of Sanctae Mariae Sabbato (Newcalendar)

### ISSUE THREAD

**Issue by KPFC** [DivinumOfficium/divinum-officium#1746]
Yesterday, 2020-05-30 the Lectiones 1 and 2 of the Matutin were missing texts, only the opening and conclusive prayers were included, which made them look like this:

V. Iube, Dómine, benedícere.
Benedictio. Nos cum prole pia benedícat Virgo María. Amen.

Lectio 1
V. Tu autem, Dómine, miserére nobis.
R. Deo grátias.

V. Iube, Dómine, benedícere.
Benedictio. Ipsa Virgo Vírginum intercédat pro nobis ad Dóminum. Amen.

Lectio 2
V. Glória Patri, et Fílio, * et Spirítui Sancto.
V. Tu autem, Dómine, miserére nobis.
R. Deo grátias.

I am pretty sure there is something missing.

**Comment by APMarcello3** [comment]
Closed by dea5ab60b
