### ISSUE TITLE
Martyrology in Ad primum Rubrics 1960 English

### ISSUE THREAD

**Issue by jorchard57** [DivinumOfficium/divinum-officium#1775]
The Martyrology appears to be a day ahead. For example, for today, June 8, 2020,  it reads: "June 9th 2020, the 17th day of the Moon, were born into the better life:" I noticed this a few days ago. Is this correct? Thank you.

**Comment by APMarcello3** [comment]
The martyrology is always anticipated by a day. As you will note, the rubric reads: Martyrologium (anticip.).
