### ISSUE TITLE
Wrong benediction at Matins, spanish version

### ISSUE THREAD

**Issue by jesav** [DivinumOfficium/divinum-officium#1800]
At Nocturn III in Matins, the benediction before the Gospel's lection is "Evangélica léctio sit nobis salus et protéctio". Accordingly, it should read in spanish "Que la lectura del Evangelio nos salve y nos proteja". Both benedictions correspond to line 18 in their respective Benedictions.txt file, in Psalterium folder. However, it is displayed instead "Que nos bendiga Aquél que vive y reina sin fin", which corresponds to line 21 in the same file.

**Comment by mbab** [comment]
Two points about source line exp: `!Mt 22, 1-14`

1. You are using short names of Evangelist as `Lc`, `Jn`, `Mt`, `Mc` but in file Translation You have `Mateo|Marcos|Lucas|Juan`, both should be complimentary.
2. Proper format of source is `!Mt 22:1-14`  not `!Mt 22, 1-14`

**Comment by jesav** [comment]
All right, I have corrected the issue noticed at point 1. About point 2, the latter (Mt 22, 1) is the standard format of biblical quoting in spanish texts. Could this format induce any further issues? If not, I would prefer to stick to "Mt 22, 1", if possible.

**Comment by APMarcello3** [comment]
Should be OK now even with the comma syntax.
