### ISSUE TITLE
Spelling with j instead of i in words such as "adjutorium"

### ISSUE THREAD

**Issue by elmonitis** [DivinumOfficium/divinum-officium#1886]
I'm looking to compile a custom ebook for the 1960 hours, but with the j's retained in words such as "adjutorium."  I noticed that the sources spell such words with the j in them, but in the output they are replaced with i's.  Is there a switch or variable somewhere in the scripts that I can modify to output those j's?

**Comment by APMarcello3** [comment]
Please see commit 5ffce465eabd6fd000780067d1d240c134f1df46. These lines could be commented out in your own version to achieve this.
