### ISSUE TITLE
Assumption of Blessed Virgin on Aug 15, shows as Saturday of Mary when options page has 'Language 1' other than latin (eg. english)

### ISSUE THREAD

**Issue by codepoet4** [DivinumOfficium/divinum-officium#1912]
To reproduce - go to options on mobile view for the divine office.  In the options, select 'language 1' to be english.  Select OK and then navigate to August 15th.  You will see the title and office from 'Sanctae Mariae Sabbato ~ IV. classis'.  Go back to options, select 'language 1' to be 'latin'.  Select OK and navigate to August 15th.  You will see the title and office from 'In Assumptione Beatæ Mariæ Virginis ~ I. classis'.

I would expect to see the 'In Assumptione Beatæ Mariæ Virginis ~ I. classis', regardless of the 'language 1' setting.

**Comment by APMarcello3** [comment]
Closed by a416eb9851d5e67dd145e3f5f9313104e918fcc2.
