### ISSUE TITLE
Negated conditionals

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DivinumOfficium/divinum-officium#193]
```
The ability to negate conditionals would be helpful.
```

Original issue reported on code.google.com by `igregord` on 23 Jul 2012 at 8:56

**Comment by fiapps** [comment]
@APMarcello3, it is good practice to indicate why issues are being closed instead of simply closing them. Was the suggested feature implemented? is the feature not needed? impractical?

This will help future users and developers.
