### ISSUE TITLE
Typo in S. Pii X. Matutin

### ISSUE THREAD

**Issue by KPFC** [DivinumOfficium/divinum-officium#1946]
In yesterday's matutin (S. Pii X, 3rd of September) there is a typo in Lectio 2: In Sir 14:12 it says "mnudi" but should say "mundi".
Something of which I am not so sure: Should Sir 14:14 be "particula boni doni non te praetereat" instead of "bono doni" how it is at the moment?

**Comment by APMarcello3** [comment]
Closed by d4d19f9
