### ISSUE TITLE
TEMPORE NATIVITATIS: In Officio feriali — capitulum ad Vesperas [1962]

### ISSUE THREAD

**Issue by miklos1** [DivinumOfficium/divinum-officium#2024]
**What it should be:** In Officio feriali — capitulum ad Vesperas ut die 1 ianuarii (i.e. Appáruit grátia) [Var. in Brev. et Miss. Rom. (1960) §22]

**What it is:** see e.g. January 4, 2021.

**Comment by APMarcello3** [comment]
Closed by 829afcfb9.
