### ISSUE TITLE
Discrepancies / errors at Matins of St Raphael (10-24.txt) in Latin and English

### ISSUE THREAD

**Issue by kormose** [DivinumOfficium/divinum-officium#2058]
Under 1960 rubrics the third readings and responsories at Mattins get jumbled up. 

Both /web/www/horas/English/Sancti/10-24.txt and /web/www/horas/Latin/Sancti/10-24.txt need to be checked. As it stands the current output produces:

**Latin**:
- Lectio1 (Tob 12:1-4) + Responsory1 (In illo témpore...)
- Lectio2 (Tob 12:5-13) + Responsory2 (Egréssus Tobías...)
- Lectio3DA (Tob 12:14-22) + Te Deum

**English:** 
- Lectio1 (Tob 12:1-4) + Responsory1 (At that time the prayers of them)
- Lectio2 (Tob 12:5-13) + Responsory3 (The Angel went in unto Tobias)
- Lectio4 (From the Sermons of St. Bonaventure, the Bishop) + Te Deum

Shouldn't the correct order for both, under 1960 Rubrics, be:

- Lectio1  + Responsory1
- Lectio 2 + Lectio3DA + Responsory 3
- Lectio 4 + Te Deum

Picture of current problems:
<img width="1305" alt="Screenshot 2020-10-24 at 09 49 17" src="https://user-images.githubusercontent.com/31819201/97077760-328daa00-15de-11eb-8a28-eb2b974f31be.png">

Possibly other translations will be affected by this, too?

**Comment by APMarcello3** [comment]
Closed by 9918032f3.
