### ISSUE TITLE
Ninth lesson for commemoration of Sunday in the octave of Christmas missing

### ISSUE THREAD

**Issue by gregordick** [DivinumOfficium/divinum-officium#2125]
Tridentine 1910, 2024-12-29: St Thomas with commem. of the Sunday.  There should be a ninth lesson for the latter, but there isn't.  Split from #1315.

**Comment by APMarcello3** [comment]
The solution to this (per the Marquess of Bute translation): under 1910 rubrics, combine the 8th and 9th reading of St. Thomas, and the 9th reading will be the Gospel pericope and all 3 readings of the homily from Sunday within the Octave with the blessing "Per evangelica dicta".
