### ISSUE TITLE
[Tridentine 1570/1910]: Psalm Antiphons of Saturday Vespers in Advent

### ISSUE THREAD

**Issue by loci1559** [DivinumOfficium/divinum-officium#2135]
f7ad7a61425d63f40aebe9bf91046bb913bc5d5a fixes issue #2131 so that the psalm antiphons of sunday vespers in Advent are now of the season (i.e. the same as lauds of the same sunday). But according to the rubrics the psalm antiphons of saturday vespers in Advent should not be of the following sunday (i.e. of the season) but the per annum saturday vespers psalm antiphons. So saturday vespers in Advent and sunday vespers in Advent should have different psalm antiphons.

**Comment by APMarcello3** [comment]
Closed by b7e26da05e890c7406ea20e7d55b70974fb1380d.
