### ISSUE TITLE
Various Tridentine BVM on Saturday and Suffragium Errata

### ISSUE THREAD

**Issue by APMarcello3** [DivinumOfficium/divinum-officium#2162]
The office of the BVM on saturdays between nativity and candlemas should use the psalm antiphons from 01-01 for lauds and the little hours. (Formerly #2161)

The commemoration Sanctae Mariae Sabbato at vespers on 01-22-2021 should use the seasonal parts of the office: The antiphon should be Magnum hereditátis mystérium instead of Beáta Mater et intácta Virgo and the oration should be Deus, qui salútis ætérnæ instead of Concéde nos fámulos tuos. (#2160)

In Easter-time the only Suffrage said is the Commemoration of the Cross for that Season. (#2159)

The office of the BVM on saturdays should not include the suffragium de cruce because it is not ferial. (#2157)

**Comment by mbab** [comment]
p. 3 & p.4 are still to do
