### ISSUE TITLE
Dec. 7 - St. Ambrose Matins for 1570 and 1910

### ISSUE THREAD

**Issue by PaulDang1** [DivinumOfficium/divinum-officium#2167]
St. Ambrose's 1st Nocturn readings for 1570 and 1910 are wrong; it should be the readings for Bishop-Conferssors, "Fidelis sermo."

**Comment by APMarcello3** [comment]
Closed by 5e1e437

**Comment by PaulDang1** [comment]
Why is this closed? Are you changing it? or not? If not, you are wrong!
