### ISSUE TITLE
[Tridentine 1570]: First Vespers of the Nativity on 12-24 not always displayed

### ISSUE THREAD

**Issue by loci1559** [DivinumOfficium/divinum-officium#2209]
The 1570 version has a problem with vespers on 12-24: sometimes it rightly displays the first vespers of the Nativity but sometimes it instead displays vespers of the feria in Advent. I can only reproduce this for 2020.

**Comment by loci1559** [comment]
Similarly for 12-31-2020 in the 1570 version: sometimes it displays first vespers of the Circumcision, sometimes second vespers of St. Silvester.

**Comment by gregordick** [comment]
@loci1559: Thank you for the report.  I haven't been able to reproduce this, and wondered whether you have any insight into the necessary conditions required to trigger the bug:
* Do you know whether it affects the "Desktop" (`officium.pl`) or "Mobile" (`Pofficium.pl`) versions, or both?
* How do you typically navigate to the office?  For example, from the front page for the day (https://divinumofficium.com/cgi-bin/horas/officium.pl) do you follow the "Vesperae" link immediately, or do you (for example) first view another office, or change the current date or rubrics?
* Do you use the `<hour> persolut.` button presented at the end of each office?
* Do you use your browser's "back" button to navigate between pages?

**Comment by loci1559** [comment]
@gregordick: Thank you for your feedback. I could reproduce this issue for both officium.pl and Pofficium.pl, and for all navigation possibilites that I tried (from the front page, from another office, changing the date, refreshing the page) but I don't use the persolut button or the browser's back button. I could not reproduce this for dates in 2021.
