### ISSUE TITLE
[Tridentine]: Lauds Antiphons Saturday before the Nativity

### ISSUE THREAD

**Issue by loci1559** [DivinumOfficium/divinum-officium#2210]
At the moment the Tridentine version uses the lauds antiphons of the Divino afflatu version »Intuémini« etc. for the saturday before the nativity. But the Tridentine rubrics specify: »Quae autem dicendae essent die, in quo occurrit Festum S. Thomae, dicuntur in Sabbato cum Psalmis Sabbati, quarta Antiphona praetermissa, cujus loco dicitur Antiphona Exspectetur. Nisi Vigilia Nativitatis venerit in Dominica; tunc enim in Sabbato dicuntur Antiphonae de Laudibus Dominicae, quarta praetermissa, cujus loco dicitur Antiphona Exspectetur.« So the lauds antiphons for the saturday before the nativity should either be those of the feria on which the feast of St. Thomas falls (for example in 2020 the lauds antiphons of the monday before the nativity »Ecce véniet« etc.) or those of the fourth sunday in advent (»Cánite tuba« etc.) if the sunday falls on the eve of the nativity. In both cases the fourth antiphon (for the Canticum Moysis) is replaced by: »Exspectétur * sicut plúvia elóquium meum: et descéndet super nos sicut ros Deus noster.«

**Comment by APMarcello3** [comment]
For Vespers 12-30-2020 (1570|1910), the antiphons and psalms should be of 2nd Vespers of Christmas doubled. The chapter onward is of St. Sylvester.

**Comment by APMarcello3** [comment]
Cf. issue #101.
