### ISSUE TITLE
OPBMV - Latin Collects not appearing (Prima, Completorium), Tridentine 1910, Rubrics 1960 - Error: Commune/C10:Oratio 21 is missing!

### ISSUE THREAD

**Issue by doctorlumen** [DivinumOfficium/divinum-officium#2308]
I noticed on 1/21 that the Latin collects at Prime and Compline stopped appearing in the Little Office of Our Lady. Also, the antiphon and Nunc dimittis do not appear at Compline. I tested with the Tridentine 1910 and Rubrics 1960 settings. The English translations DO appear however. 

Commune/C10:Oratio 21 is missing!
Commune/C10:Ant 11 is missing!&psalm(233)
Commune/C10:Ant 11 is missing!

**Comment by APMarcello3** [comment]
Closed by 01ebf1318.
