### ISSUE TITLE
S. Petri Damiani

### ISSUE THREAD

**Issue by KPFC** [DivinumOfficium/divinum-officium#2401]
In my breviary from 1937 (Divino Afflatu) Saint Peter has the liturgical category of Episcopi Confessoris et Ecclesiae Doctoris; while he is only a Confessor here.
For this reasons also the texts are different: Everything is taken from Commune  Confessoris Pontificis except for Nocturn 3 where the homily is Vos estis sal terrae (1 loco Communi Doctorum).

**Comment by APMarcello3** [comment]
Fixed by 0b0794b05.
