### ISSUE TITLE
S. Gregorii I

### ISSUE THREAD

**Issue by KPFC** [DivinumOfficium/divinum-officium#2432]
In my breviary from 1937 the readings for the third nocturn is not taken from the proper of Saints but is a homily by pope Gregory to Matt. 5, 13-19 (Vos estis sal terræ) which is not included in the proper of Doctors. Maybe your source differs, but you might want to look into it. If necessary I can write down the homily.

**Comment by APMarcello3** [comment]
Our two sources both indicate that, under Divino Afflatu rubrics, the III nocturn readings are from the Common of One Pope (Homily on the Gospel "Venit Jesus") with the Responsories of the Common of a Confessor Bishop.

**Comment by peterdiekertz** [comment]
For the record, this confusion arises because
>> "Divino afflatu" in divinumofficium-ese means "calendar of 1942, rubrics immediately prior to the Holy Week reforms". I think. For added confusion, "Trident 1910" means "calendar of 1888, rubrics prior to Pius X".
https://github.com/DivinumOfficium/divinum-officium/issues/511

https://github.com/DivinumOfficium/divinum-officium/issues/512 was a proposal to make the names clearer, but closed without result.

**Comment by APMarcello3** [comment]
It would entail a considerable overhaul of our site to change these labels for the different rubrical structures. Considerable work has been done to make Divino Afflatu reflect the 1954 calendar. I am happy to clarify on our HTML help pages what these names actually reflect.
