### ISSUE TITLE
Orthodox Paschalion?

### ISSUE THREAD

**Issue by palomnik** [DivinumOfficium/divinum-officium#2463]
I am one of at least a few Western Rite Orthodox Christian who use the site and/or the app. We had to stop since the paschalion is out of sync this year.

Would it be possible to implement the Orthodox Paschalion / dates as an option? I have no idea whether this is easy or not.

**Comment by APMarcello3** [comment]
While we welcome our Western Rite Orthodox users, the purpose of the site is to provide the post-Tridentine liturgical texts which, by definition, use the Gregorian reckoning of Easter. We regret any inconvenience.
