### ISSUE TITLE
Missing line in Readme

### ISSUE THREAD

**Issue by frrobert2** [DivinumOfficium/divinum-officium#2493]
In the read me you should add the lines that is in Bold:
 
Production

To pull a pre-built container, pull see docker image divinumofficiumweb/divinumofficium:latest.

**To get the yml file 
$ wget https://raw.githubusercontent.com/DivinumOfficium/divinum-officium/master/docker-compose-prod.yml**

You can also use Docker Compose to load a copy of the container in one command:

docker-compose -f docker-compose-prod.yml up -d

This will download Divinum Officium, and run a local copy on your system, bound to localhost, port 80.

When you are done, stop the container by running:

docker-compose -f docker-compose-prod.yml down

**Comment by APMarcello3** [comment]
Closed by a269a0088.
