### ISSUE TITLE
Location of Dates for Pascha and dates based on Pascha

### ISSUE THREAD

**Issue by frrobert2** [DivinumOfficium/divinum-officium#2494]
I have forked this and I am working on creating a version of Divinium Officium for Western Rite Orthodox.

I have found the directory web/www/horas/Latin/Tabule which has the Ordo information for different years.  But I cannot seem the file that has the date for Pascha and everything that is based on Pascha in terms of dating.

Could you tell me the file and location?

Thank you.

God bless,

Fr. Robert

**Comment by APMarcello3** [comment]
It can be found in ~/cgi-bin/horas/horascommon.pl, lines 127-145.

**Comment by frrobert2** [comment]
Thank you
