### ISSUE TITLE
[Tridentine] Antiphons at Prime through None in Paschaltide Office

### ISSUE THREAD

**Issue by aykalan** [DivinumOfficium/divinum-officium#2503]
At the moment, the antiphons at the hours of Prime, Terce, Sext, and None are a threefold Alleluia for the 1570 and 1910 offices, but in the Tridentine office, these hours in the Sunday and ferial office use a fourfold Alleluia antiphon, that is, "Alleluia, * alleluia, alleluia, alleluia."

**Comment by APMarcello3** [comment]
Closed by 716178b.
