### ISSUE TITLE
Parallel Bea Psalter

### ISSUE THREAD

**Issue by rl1234567890** [DivinumOfficium/divinum-officium#2505]
Although I consider it superior to the Bea (Pius XII) Psalter, the Gallican Psalter can be difficult to understand at times. I found a simple way to display both psalters side by side on my Linux desktop:

cd /usr/local/divinum-officium-read-only/web/www/horas
sudo mkdir Bea
sudo chmod ugo+w Linguae.txt
sudo echo "Bea" >> Linguae.txt
sudo chmod ugo-w Linguae.txt
sudo sed -i "s/Polski-Newer/Polski-Newer,Bea/g" horas.dialog
cd Bea
sudo ln -s ../Latin/Commune
sudo ln -s ../Latin/CommuneM
sudo ln -s ../Latin/Martyrologium
sudo ln -s ../Latin/Ordinarium/
sudo ln -s ../Latin/PiusXII/ psalms1
sudo ln -s ../Latin/Psalterium/
sudo ln -s ../Latin/Regula/
sudo ln -s ../Latin/Sancti
sudo ln -s ../Latin/SanctiM/
sudo ln -s ../Latin/Tempora
sudo ln -s ../Latin/TemporaM/
sudo ln -s ../Latin/PiusXII/ psalms

I'm sure that it can be done on a more elegant way, but you may consider adding this as an option for the Latin geeks, who prefer a paraphrase to a translation.

**Comment by APMarcello3** [comment]
@rl1234567890 Would you add this option to the master branch?

**Comment by rl1234567890** [comment]
> @rl1234567890 Would you add this option to the master branch?

Done in ddee3b7, Father!

**Comment by APMarcello3** [comment]
Thank you!

**Comment by mbab** [comment]
> I'm sure that it can be done on a more elegant way, but you may consider adding this as an option for the Latin geeks, who prefer a paraphrase to a translation.

You can change the name to meaningfull 'Latin-Bea'
and then remove all links apart `psalms1`.
