### ISSUE TITLE
Adding a Cistercian Rite

### ISSUE THREAD

**Issue by Augustinus-Altovadensis** [DivinumOfficium/divinum-officium#2515]
Hi, I'd like to add the traditional Cistercian rite. It would be basically the clone of the Monastic rite with some updates:
- Hymns before Urban VIII.
- Different antiphons etc.
- Minor differences (Deus, in adjutórium in the beginning of vigils, missing Confíteor in Compline etc.)
- Varying doxologies in minor Horas in certain periods
- etc.

I can do the work, but I would appreciate some pointers. To change the texts is not an issue, but to introduce a new rite... I've forked the repository and start playing around. A lot has worked right away (adding a Czech language etc.), but currently, I've hit sort of an impasse. 

I have changed the horas.pl CGI script, on line 1236, I've added a new line:
`  elsif ($version =~ /Ordo Cisterciense/i) { $suffix .= "Cist"; } `

After switching on the Cistercian version, the page stops responding and perl starts cycling somewhere, using 100% of the processor core, slowing down the system to the halt... I have copied all the files in the _Ordinarium_ folder with the "Cist" prefix for both languages I'm using, but that didn't help. 

Could someone point me in the right direction, what else do I need to change for the new rite to work? 

Thanks a lot!
O.A.M.D.G.

**Comment by mbab** [comment]
The problem for Competorium is with condition in specials.pl line 234.

BTW. Monastic *use* pre Urban hymns.

**Comment by Augustinus-Altovadensis** [comment]
> The problem for Competorium is with condition in specials.pl line 234.
> 
> BTW. Monastic _use_ pre Urban hymns.

Thanks for the reply!

So when I add the Cistercian version into the condition like this, it should be OK and the counter will stop increasing ad coelestia Regna? 
`  if ($version =~ /Monastic**|Cistercian**/i) {
        while ($t[$tind] !~ /^\s*V\./) { push(@s, $t[$tind++]); }
      }
      else {
        while ($t[$tind] !~ /^\s*R\.br\./) { push(@s, $t[$tind++]); }
      }
      my @resp = ();
      while ($t[$tind] !~ /^\s*\#/) { push(@resp, $t[$tind++]); }
      postprocess_short_resp(@resp, $lang);
      push(@s, $_) for (@resp);
      next;
    }`

Yes, I know, the Hymns should be the same, but for some reason, they are not identical to what I have in my Cistercian breviary. Take Veni Creátor from the Terce of Pentecost + the Octave. The Monastic version in DivinumOfficium.com shows this for the second stanza:

`Qui díceris Paráclitus,
Altíssimi donum Dei,`

However the pre-Urban VIII. says this:

`Qui Paráclitus díceris,
donum Dei Altíssimi,`

Et cetera. Should I create a pull request for this, or is it OK for the official Monastic version? I don't have the resources, so I cannot check this myself in pre-1963 monastic hymnal...

**Comment by mbab** [comment]
> So when I add the Cistercian version into the condition like this, it should be OK and the counter will stop increasing ad coelestia Regna?
> ` if ($version =~ /Monastic|Cistercian/i) { ...`

For now yes, but I will try to fix this in other way.

> 
> Yes, I know, the Hymns should be the same, but for some reason, they are not identical to what I have in my Cistercian breviary. Take Veni Creátor from the Terce of Pentecost + the Octave. The Monastic version in DivinumOfficium.com shows this for the second stanza:
> 
> `Qui díceris Paráclitus, Altíssimi donum Dei,`
> 
> However the pre-Urban VIII. says this:
> 
> `Qui Paráclitus díceris, donum Dei Altíssimi,`

Our Monastic version is wrong. (We have not old version at all right now, I'll fix this.)

> 
> Et cetera. Should I create a pull request for this, or is it OK for the official Monastic version? I don't have the resources, so I cannot check this myself in pre-1963 monastic hymnal...
[Breviarium Monasticum 1930](https://archive.org/details/breviarium-monasticum-pars-ii/Breviarium%20Monasticum%20-%20Pars%20I)

**Comment by fiapps** [comment]
It occurs to me that if you were to use "Cistercian Monastic" for the name of the version, all of the code that matches `/Monastic/` would already apply to it without any changes. So you would only have to modify the code that applies to the 1963 Monastic Breviary and not to the Cistercian liturgy. This could simplify the work and the resulting code.

**Comment by Augustinus-Altovadensis** [comment]
> It occurs to me that if you were to use "Cistercian Monastic" for the name of the version, all of the code that matches `/Monastic/` would already apply to it without any changes. So you would only have to modify the code that applies to the 1963 Monastic Breviary and not to the Cistercian liturgy. This could simplify the work and the resulting code.


Yes, you are right. However I need to account for the peculiarities of the Cistercian rite and therefore I need proper files for each Hora (and Calendar, which will be a huge pain...). And adding this suffix seems not to work in the moment, when I name it Cistercian office. 

BTW, is there any forum or chat with developers, well you, guys, where I can have some questions? I don't really think that bug reporting is the right place, but the Discussion section is empty, so unused?

I need to account for other things like the doubling of Antiphons (Cistercian rite never doubles any antiphones), missing R.br. in minor horas, one antiphon for Lauds etc. And of course, I could try to find out on my own, but it seems to me that many of you guys know the answer ouf of the bat, and several lines of text here can save me hours of reading the code... Thanks!

**Comment by mbab** [comment]
> BTW, is there any forum or chat with developers, well you, guys, where I can have some questions? I don't really think that bug reporting is the right place, but the Discussion section is empty, so unused?

**Discussion** are not used because they were opened yesterday. :-)
Please use them.
