### ISSUE TITLE
Problem to show translation at the same line

### ISSUE THREAD

**Issue by thadeusoares** [DivinumOfficium/divinum-officium#2554]
For some reason, when I use Portuguese, as the language of translation, from Glória, it inserts the translation in the next line, creating a confusion to accompany the reading.

![image](https://user-images.githubusercontent.com/1102686/124825311-d68b6b80-df49-11eb-82dd-5e043957c156.png)

**Comment by rl1234567890** [comment]
It should be fixed with 7d20249904fb928ae80e1f3e38bd5fc57c1b0645

**Comment by rl1234567890** [comment]
More spaces eliminated with a07af748ae485262e6de2279f615cb2b89efe440. It looks good to me now.
