### ISSUE TITLE
Source for Dominican Rite?

### ISSUE THREAD

**Issue by Geremia** [DivinumOfficium/divinum-officium#2561]
What is the source for the Dominican Rite rubrics? Is it still a WIP?
[web/www/horas/Help/rubrics.html](https://github.com/DivinumOfficium/divinum-officium/blob/master/web/www/horas/Help/rubrics.html) doesn't discuss the Dominican Rite.

**Comment by APMarcello3** [comment]
We are still adding texts from the 1962 Dominican breviary with the 1967 English translation. Help is welcome!

I suggest we move this over to "Discussions"

**Comment by Geremia** [comment]
> I suggest we move this over to "Discussions"
https://github.com/DivinumOfficium/divinum-officium/discussions/2564

I forgot about that new GitHub feature.
