### ISSUE TITLE
Dominican Rite prime antiphon truncated

### ISSUE THREAD

**Issue by Geremia** [DivinumOfficium/divinum-officium#2566]
The antiphon of the first psalm of prime in the Dominican Rite is truncated:

> _Psalms_ {from the Psalter for the day of the week}  
> _Ant._ For thy mercy,  
> _Psalm 25_ \[1\]

It should say:

> _Psalms_ {from the Psalter for the day of the week}  
> _Ant._ For thy mercy, O Lord, is before my eyes; and I am well pleased with thy truth.
> _Psalm 25_ \[1\]

The same holds for the Latin.

**Comment by APMarcello3** [comment]
Closed by f5c8ab79f.
