### ISSUE TITLE
The whole Italian Apostles' Creed is shown instead of "Credo"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DivinumOfficium/divinum-officium#257]
```
What steps will reproduce the problem?
1. Go to the Mass of the day
2. Select Italian

What is the expected output? What do you see instead?

The whole text of the Apostles' Creed is printed. Instead we should only 
see "Credo"


.


```

Original issue reported on code.google.com by `roberto....@gmail.com` on 15 Nov 2014 at 2:30

**Comment by jcaudle** [comment]
I was trying to look into this, but cannot find the text `Io credo` anywhere in the repository. Are we certain we haven't missed something on the server that should be committed here for the Missa program?

**Comment by jcaudle** [comment]
I should also note that I haven't been able to find the other headings generated for `missa.pl`, so it may just be my lack of familiarity with how the script works.

**Comment by rl1234567890** [comment]
divinum-officium/web/www/missa/Italiano/Ordo/Prayers.txt has tje Apostle's Credo

**Comment by rl1234567890** [comment]
The Polish version does not have this problem. It looks similar to the double hymn problem fixed in https://github.com/DivinumOfficium/divinum-officium/commit/56017ad6afbe1654af6d8da1447b256e5f487ddb
Is there something special I should do?
