### ISSUE TITLE
Polish translation of rubrics is very poor and some are missing, making confusion

### ISSUE THREAD

**Issue by piomrex** [DivinumOfficium/divinum-officium#2570]
Polish translation of rubrics is very poor and some are missing, making confusion. Attached corrections, based on Ritus Servandus translation available in Vademecum of EFRR (pl: Vademecum NFRR by rev. P. Wulgaris) and some other books. Also one new file: Ante.txt
[Ante.txt](https://github.com/DivinumOfficium/divinum-officium/files/6889245/Ante.txt)
[Communio.txt](https://github.com/DivinumOfficium/divinum-officium/files/6889246/Communio.txt)
[Ordo.txt](https://github.com/DivinumOfficium/divinum-officium/files/6889247/Ordo.txt)
[Prayers.txt](https://github.com/DivinumOfficium/divinum-officium/files/6889248/Prayers.txt)

**Comment by APMarcello3** [comment]
Closed by 5bc8e6e88.

**Comment by piomrex** [comment]
Thank you APMarcello, it looks you have missed to add one NEW file: Ante.txt (vestment wearing prayers).
