### ISSUE TITLE
2 Commemorations of St. Roman Martyr

### ISSUE THREAD

**Issue by Sarto2** [DivinumOfficium/divinum-officium#2584]
Today (08/08/2021), there are 2 different commemorations of St. Roman Martyr for Vespers (Divino afflatu version).

Commemoratio S. Romani Martyris

Ant. Iste Sanctus pro lege Dei sui certávit usque ad mortem, et a verbis impiórum non tímuit: fundátus enim erat supra firmam petram.

V. Glória et honóre coronásti eum, Dómine.
R. Et constituísti eum super ópera mánuum tuárum.

Orémus.
Præsta, quǽsumus, omnípotens Deus: ut, intercedénte beáto Románo Mártyre tuo, et a cunctis adversitátibus, liberémur in córpore, et a pravis cogitatiónibus mundémur in mente.

Commemoratio S. Romani Martyris

Ant. Qui vult veníre post me, ábneget semetípsum, et tollat crucem suam, et sequátur me.

V. Justus ut palma florébit.
R. Sicut cedrus Líbani multiplicábitur.

Orémus.
Præsta, quǽsumus, omnípotens Deus: ut, intercedénte beáto Románo Mártyre tuo, et a cunctis adversitátibus liberémur in córpore, et a pravis cogitatiónibus mundémur in mente.

**Comment by Sarto2** [comment]
I also think that the order of commemorations isn't correct. Shouldn't St. Jean-Marie Vianney come as the first commemoration, which would then be followed by St. Roman, and then Sts. Cyriacus, Largus and Smaragdus (as this would be their II. Vespers)?

**Comment by gregordick** [comment]
I've proposed a fix in #2593.  St John Mary Vianney should indeed come first as his in the office of the following, but after that the offices are just sorted by rank, and only in the cases of a tie are following offices preferred to preceding offices, so St Romanus comes last, being reduced to the form of a simple.  #2593 doesn't implement this rule -- we're a long way off from being able to support that -- but it does fix the immediate bugs that cause the errors in this particular case.
