### ISSUE TITLE
Gender Change of St. Tiburtius

### ISSUE THREAD

**Issue by Sarto2** [DivinumOfficium/divinum-officium#2588]
The app gives today's Saints as "Ss. Tiburtii et Susannæ Virginum et Martyrum", which makes St. Tiburtius into a Virgin Martyr. The correct title should be "Ss. Tiburtii et Susannæ Virginis, Martyrum".

**Comment by APMarcello3** [comment]
Closed by 5805b958733de53220b39c5490a9b72b2cdabb95.
