### ISSUE TITLE
Octave of the Assumption Fixes

### ISSUE THREAD

**Issue by benyanke** [DivinumOfficium/divinum-officium#2594]
DO has the 1950 Pius XII Office for the days in the Octave of the Assumption for all the older versions. Needs to be fixed.
(Shared from John Rotondi who sent this correction to me)

**Comment by APMarcello3** [comment]
Closed by 44756907.

**Comment by APMarcello3** [comment]
It should be noted that the Marquess of Bute translation does not provide an English translation for these lessons.
