### ISSUE TITLE
Credo 

### ISSUE THREAD

**Issue by rl1234567890** [DivinumOfficium/divinum-officium#2596]
Although file web/www/missa/Latin/Sancti/08-16.txt has 

```
[Rule]
ex C5;
Gloria
```

the[ Credo appears in the Mass. ](https://divinumofficium.com/cgi-bin/missa/missa.pl?&date=8-16-2021&solemn=1&first=1&rubrics=1)

**Comment by APMarcello3** [comment]
Closed by 8284f58dadaef805d19561716e8e90287989937c
