### ISSUE TITLE
No Docker config for AArch64

### ISSUE THREAD

**Issue by jescala** [DivinumOfficium/divinum-officium#2609]
I am unable to load the Docker container on my Raspberry Pi or my Synology NAS. Can we have a build for the ARM 64 architecture?

**Comment by ajmalton** [comment]
In the interim you might try local hosting, which is what I do for development and it works well, and is easy.

Details: https://divinumofficium.com/www/horas/Help/download.html

TLDR: clone the repo, cd to its web/ subdirectory, and run python's http.server with --cgi option.  Then surf to localhost:8000.

**Comment by benyanke** [comment]
Hello,

Maintainer of the docker images here.

I would be interested in pursuing this but I won't have much time in the next few weeks. I'm going to leave this open, but be aware it's a low priority for us.

We're also in the middle of reworking our CI process that builds docker images, so I will keep this in mind as I rebuild that.

In the meantime, I would consider the workaround Andrew mentioned, which would run without containers.

**Comment by benyanke** [comment]
Closing this as not planned. We don't currently have plans to support arm images, but you are free to rebuild the dockerfile if you need.
