### ISSUE TITLE
Version française

### ISSUE THREAD

**Issue by Lecteur01** [DivinumOfficium/divinum-officium#2620]
Bonjour,

Je constate que pour la version française de Divinum Officium, les traductions des trois leçons des Matines (Ad Matutinum  Rubrics 1960) sont en anglais et non en français comme le reste du texte (par exemple ici : https://divinumofficium.com/cgi-bin/horas/officium.pl).
Je remarque aussi que les antennes latines ne sont pas toujours traduites pour les petites heures de tierce, sexte, et none, et restent en latin au lieu d'être en français dans la colonne dédiée.
Enfin, le  martyrologe de l'office de Prime reste aussi toujours en anglais.

Bien cordialement,

Un lecteur francophone.

--

Hello,

I note that for the French version of Divinum Officium, the translations of the three lessons of Matins (Ad Matutinum Rubrics 1960) are in English and not in French like the rest of the text (for example here: https://divinumofficium.com/cgi -bin / horas / officium.pl).
I also notice that the Latin antennas are not always translated for the small hours of tierce, sext, and none, and remain in Latin instead of being in French in the dedicated column.
Finally, the martyrology of the Prime Office is also still in English.

Best regards,

A French-speaking reader.

**Comment by Lecteur01** [comment]
Hello,

I note that for the French version of Divinum Officium, the translations of the three lessons of Matins (Ad Matutinum Rubrics 1960) are in English and not in French like the rest of the text (for example here: https://divinumofficium.com/cgi-bin/horas/officium.pl ).
I also notice that the Latin antennas are not always translated for the small hours of tierce, sext, and none, and remain in Latin instead of being in French in the dedicated column.
Finally, the martyrology of the Prime is also still in English.

Best regards,

A French-speaking reader.

**Comment by APMarcello3** [comment]
Les traductions en français sont sous développement. Donc quand les textes français manquent, le logiciel affiche l'anglais.

**Comment by ajmalton** [comment]
Quant aux antiennes, presentées en latin plutôt qu'en français ou même en anglais: là il s'agit de ce que la version française a retenu quelques textes littéralement en latin, non traduits.

Je suppose que quelqu'un aurait préféré le latin à l'anglais, dans les cas décrits ci-dessus par M le curé où manque une version française.

Il s'en suit une question naturelle: les utilisateurs des vernaculaires préfèrent-ils vraiment l'anglais si non leur langue préférée? Pourquoi pas présenter le latin, non l'anglais, à défaut d'une traduction?

**Comment by fiapps** [comment]
Si l'utilisateur veut le latin, il peut déjà le trouver dans la première colonne. La traduction anglaise offre une alternative à la compréhension du latin.
