### ISSUE TITLE
Callistratus

### ISSUE THREAD

**Issue by rl1234567890** [DivinumOfficium/divinum-officium#2630]
https://github.com/DivinumOfficium/divinum-officium/blob/master/web/www/horas/Latin/Martyrologium1960/09-26.txt

Since the a in the penultimate of Callistratus is short as is also the α in Greek, the Latin accent should fall on the antepenultimate: Callístratus, not Callistrátus. Shall we correct it or is it a special Ecclesiastical usage:

**Comment by APMarcello3** [comment]
Error has been fixed.
