### ISSUE TITLE
DA Vespers for 10-29-2021

### ISSUE THREAD

**Issue by corei8** [DivinumOfficium/divinum-officium#2653]
Should be of the Feria, with suffrage of the Saints.

Right now it is showing Our Lady's Saturday -- Saturday should be the anticipated vigil of All Saints, therefore there is no office of the Blessed Virgin.

**Comment by mbab** [comment]
It is common bug as false Vespere of BMV Sabbato appears on every ferias Fridays.

**Comment by ajmalton** [comment]
On ferial days in the older tradition, surely Vespers of the following day is correct, isn't it?

The ideas that “first Vespers is special for more solemn days” is not, I think, the traditional view: in fact “second Vespers is special for more solemn days” is closer to the truth.

**Comment by gregordick** [comment]
The problem here is that the (anticipated) vigil on the Saturday should make the office of the Blessed Virgin Mary on Saturday disappear completely.

**Comment by rl1234567890** [comment]
Is this bug related to the one I [reported](https://github.com/DivinumOfficium/divinum-officium/issues/2656)?

**Comment by ajmalton** [comment]
Yes, pretty much the same, but not quite.  They are both about Vespers concurrence in the 1910 rubrics.  The combination of anticipation and transfer is just a whisper beyond the capability of the current logic.

But this one #2653 would still be happening even if there was no transfer, as @mbab pointed out.  The #2656 is also reflecting the “transfer” (not really a transfer but treated as one) of Christ the King. Roughly speaking the logic confuses "concurrence" with "occurring on the following day", and sometimes with “on the calendar for the following day”.

**Comment by ajmalton** [comment]
I have (also) fixed this #2653 by now, basically by distinguishing, with a new rank variable, between "concurrent" and "occurring tomorrow", for this purpose only.  It appears to be correct for all the BMV Sabbato cases.  But it's not fully tested yet, and therefore not pushed, because I haven't quite finished the closely related #2656 , and they should be tested together.
