### ISSUE TITLE
Splitted Vespers

### ISSUE THREAD

**Issue by KPFC** [DivinumOfficium/divinum-officium#2665]
At least in DA there is a rule that when two Duplex or two Semiduplex feasts concur with each other who have the same nobility, the Vesper is splitted so that psalms and antiphons are said from the first feast and everything from capitulum to end from the second feast (with commemoration of the first).

Most of the time it is not noticeable because the psalms are of the feria anyway, but eg for the first Vesper of S. Martin the psalms should be of S. Andrea Avellinus (so of the feria).

**Comment by ajmalton** [comment]
I think this is supposed to be handled by the code in horascommon beginning around line 500.  Does that logic never work? Or just not in cases like the above?

**Comment by APMarcello3** [comment]
It appears that 1st Vespers (DA) of St. Martin is displaying correctly, per the following:![20211111_102431.jpg](https://user-images.githubusercontent.com/11463422/141323911-69a3c1b1-0293-41b7-a312-ac8055e32238.jpg)

**Comment by KPFC** [comment]
Yes, the rubrics say "Si dicendæ sind integræ …". The point being that they usually are not to be said "integræ" i. e. "whole" but only when the previous feast has a lower rank or Martini has a higher rank (e. g. as patronage feast).

**Comment by KPFC** [comment]
@APMarcello3 can you please reopen this issue as it is not yet done?
