### ISSUE TITLE
05-25 commemoration of St Urban

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DivinumOfficium/divinum-officium#269]
```
The commemoration (or the full office as it is in 1570) should be different in 
and out of Paschaltide: I think C3p and C2 respectively. This will be best 
dealt with after calcalc.
```

Original issue reported on code.google.com by `igregord` on 8 Mar 2015 at 3:57

**Comment by APMarcello3** [comment]
According to my 1961 Maison Mame Breviarium Romanum, despite the text being the Paschaltide proper, St. Urban's commemoration appears to be the same in and out of Paschaltide.
