### ISSUE TITLE
Missing Commemoratio S. Stephani Protomartyris (2021-12-26, rubrics 1960)

### ISSUE THREAD

**Issue by DLakomy** [DivinumOfficium/divinum-officium#2698]
There is a commemoration on Lauds only. It should be also on Vespers and the Mass (even the solemn one). Reason: rubrics 108 and 109c:

> 108. Commemorationes privilegiata fiunt in
> Laudibus et in Vesperis necnon in omnibus Missis;
> commemorationes vero ordinaria fiunt tantum in
> Laudibus, in Missis conventualibus et in omnibus
> Missis lectis.
> 109. Commemorationes privilegiata sunt com-
> memorationes :
> [...]
> c) de diebus infra octavam Nativitatis Domini;
> [...]

**Comment by APMarcello3** [comment]
From reading the pages of an Ordo from the 1960's, it appears the interpretation was taken that the 2nd class feasts falling within the Octave were not considered the "days within the Octave". This seems to be the approach which the LMS Ordo currently takes: https://lms.org.uk/sites/default/files/u8/december.pdf.
