### ISSUE TITLE
Duplicated "In Ascensione Domini" for 2022

### ISSUE THREAD

**Issue by andriusbal** [DivinumOfficium/divinum-officium#2699]
Laudetur Iesus Christus.

There is duplicated "In Ascensione Domini" for 2022 on June 3rd, while true feast is on May 26th.

**Comment by APMarcello3** [comment]
This error is not able to be duplicated. The day in question is displaying otherwise correctly as the Octave day/Feria V infra hebd. post Asc.

**Comment by andriusbal** [comment]
I have not provided direct link where it happens - my apologies.
At https://www.divinumofficium.com/cgi-bin/missa/missa.pl, when date is set to 6-3-2022, Brave and Edge provide the same result
![div_off_june_3](https://user-images.githubusercontent.com/13737739/147556221-fc8d4fe7-313c-4a22-a2bf-99bf98f4f1a5.jpg)
.

**Comment by KPFC** [comment]
I can reproduce this issue using the 1960 rubrics. Also related or not for the 1955 rubrics it is Dominica post Ascensionem (while I don't know anything about these rubrics this seems curious).

For all of the other rubrics it is correctly displayed.
