### ISSUE TITLE
Dominican Compline messes up in many areas

### ISSUE THREAD

**Issue by KronkyMalonky** [DivinumOfficium/divinum-officium#2700]
Hello! I'm not a coder so apologies for being unspecific, but for the Dominican Compline many things in the English are in the wrong areas, there will be a box with a single response and the psalm in the next, etc. Some of the antiphons in latin aren't complete at the start too.

Many thanks for your work,
God bless!

**Comment by APMarcello3** [comment]
This is a work in progress. Thank you for your patience!
