### ISSUE TITLE
Holy Family in the 1570 and 1910 rubrics

### ISSUE THREAD

**Issue by KPFC** [DivinumOfficium/divinum-officium#2717]
I am not quite sure when the feast of the Holy family was introduced, but it should not have been present in the 1910 nor in the 1570 calendar (as is right now the case if you select them and e.g. 2022-01-09 as date), but are rightly included in the 1954 version. At least it is not included in my 1915 Pustet breviary, so I assume it was introduced later.

**Comment by APMarcello3** [comment]
Closed by 5e845cd42.
