### ISSUE TITLE
Incorrect St. Gregory Homily number

### ISSUE THREAD

**Issue by orbanbalage** [DivinumOfficium/divinum-officium#2759]
`!Homilia 15 in Evangelia`
is the correct number, as in: [Quadp2-0.txt](https://github.com/DivinumOfficium/divinum-officium/blob/2f4512e8afa9842e330cf636ad7c26efd356cf00/web/www/horas/Latin/Tempora/Quadp2-0.txt)

`!5th on the Gospels`
is wrong, as in:
- [Quadp2-0.txt](https://github.com/DivinumOfficium/divinum-officium/blob/207a834e229fd592491a879bbb731f34e6f87103/web/www/horas/Magyar/Tempora/Quadp2-0.txt)
- [11-30.txt](https://github.com/DivinumOfficium/divinum-officium/blob/207a834e229fd592491a879bbb731f34e6f87103/web/www/horas/Magyar/Sancti/11-30.txt)
- [Quadp2-0.txt](https://github.com/DivinumOfficium/divinum-officium/blob/2f4512e8afa9842e330cf636ad7c26efd356cf00/web/www/horas/English/Tempora/Quadp2-0.txt)
- [11-30.txt](https://github.com/DivinumOfficium/divinum-officium/blob/207a834e229fd592491a879bbb731f34e6f87103/web/www/horas/English/Sancti/11-30.txt)

**Comment by APMarcello3** [comment]
Closed by 312a1a8b1
