### ISSUE TITLE
WARNING: Section `Oratio Gregem` ... is missing in ... C4b.txt

### ISSUE THREAD

**Issue by damianoognissanti** [DivinumOfficium/divinum-officium#2761]
In the files C2, C4 and C4b there are no "Oratio Gregem" nor "Postcommunio Gregem" (there are Oratio1, Oratio91 and Postcommunio1 though and it seems the mass at 03-04.txt at least should reference Postcommunio1 according to my Missal, havent gone through them all though).

The following files look for Postcommunio Gregem in C4b:

./web/www/missa/French/Sancti/11-19.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/French/Sancti/01-05.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/French/Sancti/01-11.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/French/Sancti/08-02.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/French/Sancti/05-26.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/French/Sancti/10-07r.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/French/Sancti/10-07.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/French/Sancti/12-10.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/French/Sancti/03-04.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/French/Sancti/01-05r.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/French/Sancti/12-31r.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/French/Sancti/05-27.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Cesky/Sancti/01-05.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Cesky/Sancti/12-10.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Cesky/Sancti/12-31r.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Latin/Sancti/01-05.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Latin/Sancti/01-11.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Latin/Sancti/08-02.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Latin/Sancti/10-07.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Latin/Sancti/01-05r.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/English/Sancti/11-19.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/English/Sancti/01-05.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/English/Sancti/01-11.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/English/Sancti/08-02.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/English/Sancti/05-26.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/English/Sancti/10-07r.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/English/Sancti/03-04rq.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/English/Sancti/10-07.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/English/Sancti/12-10.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/English/Sancti/03-04.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/English/Sancti/01-05r.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/English/Sancti/12-31r.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/English/Sancti/05-27.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Italiano/Sancti/11-19.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Italiano/Sancti/01-05.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Italiano/Sancti/01-11.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Italiano/Sancti/08-02.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Italiano/Sancti/05-26.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Italiano/Sancti/10-07r.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Italiano/Sancti/10-07.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Italiano/Sancti/12-10.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Italiano/Sancti/03-04.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Italiano/Sancti/01-05r.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Italiano/Sancti/12-31r.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Italiano/Sancti/05-27.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Polski/Sancti/05-26.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Polski/Sancti/12-10.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Polski/Sancti/03-04.txt:@Commune/C4b:Postcommunio Gregem
./web/www/missa/Polski/Sancti/05-27.txt:@Commune/C4b:Postcommunio Gregem

And the following look for Oratio Gregem in C2, C4, C4b:

./web/www/missa/French/Sancti/11-19.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/French/Sancti/01-05.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/French/Sancti/01-11.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/French/Sancti/08-02.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/French/Sancti/05-26.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/French/Sancti/10-07r.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/French/Sancti/10-07.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/French/Sancti/12-10.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/French/Sancti/03-04.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/French/Sancti/01-05r.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/French/Sancti/12-31r.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/French/Sancti/05-27.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Cesky/Sancti/12-10.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Latin/Sancti/01-05.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Latin/Sancti/01-11.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Latin/Sancti/08-02.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Latin/Sancti/10-07.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Latin/Sancti/01-05r.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/English/Sancti/11-19.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/English/Sancti/01-05.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/English/Sancti/01-11.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/English/Sancti/08-02.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/English/Sancti/05-26.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/English/Sancti/10-07r.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/English/Sancti/10-07.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/English/Sancti/12-10.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/English/Sancti/03-04.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/English/Sancti/01-05r.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/English/Sancti/12-31r.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/English/Sancti/05-27.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Italiano/Sancti/11-19.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Italiano/Sancti/01-05.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Italiano/Sancti/01-11.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Italiano/Sancti/08-02.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Italiano/Sancti/05-26.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Italiano/Sancti/10-07r.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Italiano/Sancti/10-07.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Italiano/Sancti/12-10.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Italiano/Sancti/03-04.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Italiano/Sancti/01-05r.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Italiano/Sancti/12-31r.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Italiano/Sancti/05-27.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Polski/Sancti/05-26.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Polski/Sancti/12-10.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Polski/Sancti/03-04.txt:@Commune/C4b:Oratio Gregem
./web/www/missa/Polski/Sancti/05-27.txt:@Commune/C4b:Oratio Gregem
./web/www/horas/Magyar/Sancti/05-25.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Magyar/Sancti/12-31r.txt:@Commune/C4:Oratio Gregem
./web/www/horas/Latin/SanctiM/12-31.txt:@Commune/C4:Oratio Gregem
./web/www/horas/Latin/Sancti/01-10.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Latin/Sancti/01-11.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Latin/Sancti/05-25.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Latin/Sancti/12-10.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Latin/Sancti/12-31r.txt:@Commune/C4:Oratio Gregem
./web/www/horas/English/Sancti/01-10.txt:@Commune/C2:Oratio Gregem
./web/www/horas/English/Sancti/01-11.txt:@Commune/C2:Oratio Gregem
./web/www/horas/English/Sancti/05-25.txt:@Commune/C2: Oratio Gregem
./web/www/horas/English/Sancti/12-10.txt:@Commune/C2:Oratio Gregem
./web/www/horas/English/Sancti/12-31r.txt:@Commune/C4:Oratio Gregem
./web/www/horas/Italiano/Sancti/05-25.txt:@Commune/C2: Oratio Gregem
./web/www/horas/Italiano/Sancti/12-10.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Italiano/Sancti/12-31r.txt:@Commune/C4:Oratio Gregem
./web/www/horas/Polski/Sancti/11-19.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Polski/Sancti/01-10.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Polski/Sancti/01-11.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Polski/Sancti/05-26.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Polski/Sancti/05-25.txt:@Commune/C2: Oratio Gregem
./web/www/horas/Polski/Sancti/12-10.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Polski/Sancti/12-31r.txt:@Commune/C4:Oratio Gregem
./web/www/horas/Francais/Sancti/01-10.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Francais/Sancti/01-11.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Francais/Sancti/05-25.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Francais/Sancti/12-10.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Francais/Sancti/12-31r.txt:@Commune/C4:Oratio Gregem
./web/www/horas/Espanol/Sancti/01-10.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Espanol/Sancti/01-11.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Espanol/Sancti/05-25.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Espanol/Sancti/12-10.txt:@Commune/C2:Oratio Gregem
./web/www/horas/Espanol/Sancti/12-31r.txt:@Commune/C4:Oratio Gregem

**Comment by APMarcello3** [comment]
References to "Gregem" are handled by logic in ~/cgi-bin/missa/propers.pl. These all display correctly.
