### ISSUE TITLE
Ash Wednesday ad Primam Chapter

### ISSUE THREAD

**Issue by xpihs** [DivinumOfficium/divinum-officium#2765]
There is an error regarding the Chapter for the Rubrics Prior to 1962: "Reduced 1955", "Divino Afflatu", "Tridentine 1910" "Tridentine 1570". The Chapter should be as on other ferias. "In omnibus autem Feriis et in Vigiliis communibus, extra Tempus Paschale: Capit. Zach. 8,19 Pacem et veritatem diligite, ait Dominius omnipotens. Ash Wednesday is a privileged Feria, but it is not a privileged Vigil. I note that the header reads: Feria IV Cinerum ~ Simplex and yet the Tuesday of Holy Week (Divino Afflatu) reads Feria Tertia Majoris Hebdomadæ ~ Feria privilegiata. Both Offices are Simple (Simplex) as are all ferial offices before 1962. The error does not seem to be repeated in Holy Week. However the opposite error shows itself on the Vigil of the Epiphany which is a privileged vigil (of the second class). This error occurs only in the rubrics "Divino Afflatu" and "Reduced 1955".

**Comment by APMarcello3** [comment]
Chapter and Ash Wednesday title has been fixed by 8886fc806. Vigil of the Epiphany under Divino Afflatu & 1955 rubrics correctly displays as "Semiduplex" which is confirmed by the liturgical books.

**Comment by xpihs** [comment]
That was not the issue with the Vigil of the Epiphany. The issue was the chapter of Prime which is displaying “Pacem et veritatem” instead of  “Regi sæculorum”. That is what I intended.

Under Divino Afflatu, the Vigil is a Privileged Vigil (of the Second Class) There are two classes of Privileged Vigil which is distinct from it being Semiduplex, which it is.


Under Divino Afflatu, Privileged Vigils use the Chapter 1 Tim. 1.17 “Regi sæculorum” not “Pacem et veritatem.” Unless my rubrics are in error.

**Comment by APMarcello3** [comment]
Changed by cf71616.
