### ISSUE TITLE
3-4-2022 St. Lucius I commemoration missing

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#2775]
A correspondent points out to me that with the 1960 rubrics, both St. Casimir and St. Lucius should have been commemorated at yesterday's matins, but only the former was. The LMS ordo confirms he's right. I took a look at the file for 03-04, and it does contain the commemoration of St. Lucius, so I'm not sure what went wrong.

See https://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=03-04-2022&command=prayLaudes&version=Rubrics%201960&testmode=regular&lang2=English&votive=

**Comment by APMarcello3** [comment]
Closed by 12bc2b18a.
