### ISSUE TITLE
In Vigilia Omnium Sanctorum: Prayer not displayed in Spanish

### ISSUE THREAD

**Issue by jesav** [DivinumOfficium/divinum-officium#2786]
Good morning:

As you can see in 10-30-2021, at least for Divino Afflatu rubric, the final prayer before Conclusio for Matutinum is displayed in its English version, not Spanish. However, this very prayer is included in Tempora/10-31.txt in both English and Spanish branches.

**Comment by APMarcello3** [comment]
Closed by fc427991d37a781d1837fb6ffa75b41eb4d3bcad
