### ISSUE TITLE
Typo in prayers to several saints

### ISSUE THREAD

**Issue by jesav** [DivinumOfficium/divinum-officium#2817]
In the spanish version of Officium, there are some typos when praying for the intercession of a couple of saints. I have detected two cases, both of them in Divino Afflatu rubric, at Laudes, in the Oratio before conclusion, at dates 4-26-2021, 4-22-2021:

_Gregem tuum, Pastor ætérne, placátus inténde: et per beátos Cletum et Marcellínum Mártyres tuos atque Summos Pontífices perpétua protectióne custódi; quos totíus Ecclésiæ præstitísti esse pastóres._

Pastor eterno, que cuidas de tu rebaño con amor: guárdalo con tu protección perpetua, por intercesión de San Cleto y Marcelino ***y San N***., mártires tuyos y sumos pontífices, a quienes hiciste pastores de toda la Iglesia. 

The ***-emphasized text should not appear. It seems that the code does not recognize the conjuction «y» (and) as a name connector for the spanish version.

**Comment by APMarcello3** [comment]
Closed by add3023
