### ISSUE TITLE
Inaccuracies in Monastic office?

### ISSUE THREAD

**Issue by thenewmantis** [DivinumOfficium/divinum-officium#2843]
Hello all, I have been praying the office using the books based on the ~1934 Monastic breviary for a couple years now. The books I use are the Antiphonale Monasticum published by Solesmes in 1934, which can be downloaded or viewed [here](https://www.ccwatershed.org/2013/12/04/1934-antiphonale-monasticum-free-pdf-download/)  and the [Monastic Breviary](https://archive.org/details/breviarium-monasticum-pars-ii/Breviarium%20Monasticum%20-%20Pars%20II/page/n9/mode/2up)  from 1929 (used by the monks in Norcia). These books say the same thing as each other but I've noticed a few small discrepancies between them and Divinum Officium (DVO).
If DVO is meant to be using a slightly different source than the 1929/1934 Monastic books, please let me know and I will withdraw this!

One thing that stuck out to me today:

The Antiphonale Monasticum and Breviary, when discussing the Capitulum for ferias in Prime, say:

> In omnibus Dominicis, etiam repositis aut anticipatis, in Vigiliis privilegiatis, in Officio cujuslibet Festi vel Octavae, etiam Simplicis, ac S. Mariæ in Sabb., necnon in in Feriis Tempore Paschali:

Followed by the "Regi sæculórum" Capitulum, and go on to say

>In omnibus autem Feriis et in Vigiliis communibus, extra Tempus Paschale:

And give a different Capitulum, beginning with "Pacem et veritátem".

DVO however gives "Regi sæculórum" for ferias in my experience.

Moreover, a little bit afterwards:

>Post Lectionem Sanctæ Regulæ vel Lectionem brevem dicitur:

And a series of verses and a blessing which are not present in DVO. These are followed by the prayer and recitation of Psalm 129, etc., which DVO _does_ include.

I would be happy to fix these myself and submit a pull request--I am only asking for confirmation that these are errors and not due to use of different sources that I haven't seen; and for permission to conform the output of DVO to the rubrics that my Antiphonale and Breviary specify.

Thank you.

**Comment by APMarcello3** [comment]
I have directed that the Monastic Office, which was originally an idiosyncratic conception of the late Laszlo Kiss, be changed to reflect the 1962 Breviarium Monasticum. The changes you describe in the above issue would not be applicable to the 1962 office.
