### ISSUE TITLE
Translation of Sancta Missa Uses Smaller Font

### ISSUE THREAD

**Issue by rl1234567890** [DivinumOfficium/divinum-officium#2874]
When seen on a cell phone, the translation of the text of the Mass, which  is displayed in the second column, appears in a smaller font than the original Latin. 
![Screenshot_20220423-190836_Brave](https://user-images.githubusercontent.com/11466063/164980181-676be67e-db2b-490b-9cf7-efbd799e9e6f.jpg)
Notice that if one selects and deselects the Rubrics or Solemn buttons, the effect of the bug disappears and reappears. This applies to all languages, not only Italian.

**Comment by maxelbo** [comment]
Hi, I couldn't replicate this bug. I tried in Chrome and Firefox on a Google Pixel 4a(5G) with Android 13, and on an iPhone 12 with iOS 16.2, both on vertical and horizontal screen. Could you provide more details?
