### ISSUE TITLE
Common of apostles paschaltide monastic / tridentine 1570 lauds hymn typo

### ISSUE THREAD

**Issue by jamcmull** [DivinumOfficium/divinum-officium#2883]
In the first strophe, second line "mitet" should read "nitet"
There appears to be two versions of the pre-urban hymn in the code: the first with the correct spelling, the second with the wrong spelling.
https://ecommons.luc.edu/cgi/viewcontent.cgi?article=1651&context=luc_theses pg 150

**Comment by APMarcello3** [comment]
Closed by 2039c44798fbab0037c58d18ccaeffb353f5c923
