### ISSUE TITLE
Vigils are not anticipated if they fall on a Sunday

### ISSUE THREAD

**Issue by peterdiekertz** [DivinumOfficium/divinum-officium#293]
As far as I know, vigils were anticipated already pre-1910 on the Saturday before, if they fell on a Sunday.
It does not work at least for today, Sun 9 Aug 2015, where it gives the Vigil of St. Lawrence; the program tries to output a ferial office made up from the Sunday texts, which of course doesn't work (at Mattins, after the 12 psalms of the I nocturn, there is some gibberish created out of versicles, followed immediately by the psalms of the II & III nocturn, and the homily for the vigil).

**Comment by gregordick** [comment]
Thanks. This is a long-standing problem, but it will be fixed on the calcalc branch, where the calendar-resolution logic is currently being rewritten. This is planned to be ready (for some definition of 'ready'!) by Michaelmas.

**Comment by Kyprwl** [comment]
This issue looks fixed in relation to St Lawrence, but on Saturday 28 the vigil of St Andrew isn't showing up. That should be anticipated this year, shouldn't it?

**Comment by gregordick** [comment]
Indeed it should.  This will be fixed when the `calcalc` branch is eventually merged, which did not happen at Michaelmas!  Work is continuing.

**Comment by igneus** [comment]
I would like to try to make the calendar-resolving module(s) relatively general, self-contained, testable, and cover it with unit-tests.
Would such a contribution be welcome or would it right now be rather additional pain for the dev team?

**Comment by gregordick** [comment]
This is the work that's currently in progress on the `calcalc` branch.  Unit tests exist but are a bit patchy: see https://travis-ci.org/DivinumOfficium/divinum-officium.  Contributions of any and all sorts are certainly welcome, though!

**Comment by petermottola** [comment]
Not sure if you want to file this as a separate issue or as part of this one on Vigils, but: in the 1960 rubrics vigils that fall on Sunday should be commemorated at Lauds but are not, or at least are not in the case of 28 June 2015 where the site reads "Dominica V Post Pentecosten ~ II. classis, Commemoratio ad Laudes tantum: In Vigilia Ss. Petri et Pauli Apostolorum" but does not give the text of the oration.  Number 31 of the general rubrics reads "These vigils [of the 2nd class] are preferred to liturgical days of the 3rd and 4th class.  If impeded, they are commemorated, according to the rubrics."

**Comment by gregordick** [comment]
> in the 1960 rubrics vigils that fall on Sunday should be commemorated at Lauds

Is it not the case that Sundays admit only of privileged commemorations and of commemorations of II. cl. feasts (R.G. 111)?

**Comment by petermottola** [comment]
RG 111 b reads "on 2nd class Sundays, only one commemoration is admitted, namely of a 2nd class feast, which, however, is omitted is a privileged commemoration is to be made."  The Vigil of Peter & Paul is a day of the 2nd class, so I think for that reason the site is correct in titling 6/28/15 "Dominica V Post Pentecosten [...] Commemoratio [...] In Vigilia Ss. Petri et Pauli Apostolorum".  But if the commemorations mentioned RG 111b do not include vigils then the change needs to be made in the other direction, removing that text from the top of the page.

**Comment by gregordick** [comment]
> But if the commemorations mentioned RG 111b do not include vigils then the change needs to be made in the other direction, removing that text from the top of the page.

The table of occurrence at the front of my 1962 Desclée breviary directs that vigils be omitted on Sundays, so I think that removing that text is the thing to do here, as you suggest.
