### ISSUE TITLE
Ascensiontide Vespers DA

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#2931]
May 31: I am sure that this is a non-trivial technical challenge, but: the commemoration of St Petronilla is only at Lauds at Low Mass as on all DII class feasts. (By the way, for whatever reason it says "For ST Petronilla," not "S. or "St." in sentence-style capitalization).

June 1: according to 1954, St Angela Merici takes precedence over the octave, transferred from the previous day. II Vespers are of the following octave day (I Vespers of the feast), com. of the preceding and of the following.

June 3: Vespers should have been of Feria VI  post Octavam Ascensionis as on Sunday (v. Dominus, ant. Haec locutus sum) com. of St Francis Caracciolo. I don't fully understand the rubric, but it's what both the 1939 and 1954 ordines available have (St Lawrence Press for 1939, the "Benedicamus Domino" ordo from Poland and the "Restore the '54" from Australia all agree).

**Comment by APMarcello3** [comment]
1) We do not have the ability to remove commemorations for solemn Masses. Capitalization has been fixed.

2) Celebration of St. Angela Merici has been fixed.

3) Fixed

Closed by 2651d99e9.
