### ISSUE TITLE
Vesper of June 24th 2022

### ISSUE THREAD

**Issue by KPFC** [DivinumOfficium/divinum-officium#2937]
The Nativity of John the Baptist is correctly transferred to June 25th since it is the "less noble" in comparison to Holy Heart. But shouldn't the Vesper then also be of the "nobilior" i. e. Sanctissimi Cordis DNIC with commemoration of John? I am not sure myself though, so could someone else look into this as well?

**Comment by APMarcello3** [comment]
Closed by 3a1eb98
