### ISSUE TITLE
Commemoration in collect does not include name of saint for 2022-07-27

### ISSUE THREAD

**Issue by milodubois** [DivinumOfficium/divinum-officium#2963]
No mention of S. Pantaleonis Martyris in Latin or English for today's collect, 27 July 2022.

The collect as rendered from `https://www.divinumofficium.com/cgi-bin/missa/missa.pl` reads as follows:

"Collect
V. The Lord be with you.
R. And with thy spirit.
Let us pray.
O God, Whose providence never fails to set things in order, we humbly beseech You to remove from us whatever is harmful and grant whatever is for our benefit.
Through Jesus Christ, thy Son our Lord, Who liveth and reigneth with thee, in the unity of the Holy Ghost, God, world without end.
R. Amen.

Let us pray.
Commemoratio S. Pantaleon Martyr
Grant, we beseech You, almighty God, that through the intercession of Your blessed **Martyr N.**, we may be delivered from all afflictions of the body and cleansed from all evil thoughts of the mind.
Through Jesus Christ, thy Son our Lord, Who liveth and reigneth with thee, in the unity of the Holy Ghost, God, world without end.
R. Amen."

Note that it is usual function that this placeholder is replaced with the actual name when one visits the website.

Grace and peace,
Deo gratias,
TADMN

Milo

**Comment by APMarcello3** [comment]
Closed by c88bc7d05.
