### ISSUE TITLE
Last Gospel of Aug 9 (DA)

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#2969]
The Last Gospel on Aug 9, St John Vianney, comm. of the Vigil of St Lawrence and of St Romanus, is the proper Gospel of the Vigil (Matth. 16:24-27), not the Prologue of St John.

**Comment by APMarcello3** [comment]
Closed by 8db239cec6c94fee973229c9ddaf300d680086e2

**Comment by APMarcello3** [comment]
Cf. 4fe5501
