### ISSUE TITLE
Vespers 8-12-2022 Divino Afflatu

### ISSUE THREAD

**Issue by xpihs** [DivinumOfficium/divinum-officium#2971]
There should be a Commemoration at Vespers for the Ss. Hippolyti et Cassiani Martyrum as in 2021.

This is likely due to the error the following day which has erased the Simplex Feast of these Martyrs concurring with the anticipated Vigil.

**Comment by xpihs** [comment]
It doesn’t appear that the changes have been updated through the system.

Respectfully,

Rev. Canon Smith

**Comment by APMarcello3** [comment]
Cf. fe4c280658ea45a397024d63aec6787962d7daa4
