### ISSUE TITLE
Commemorations on Sep. 23

### ISSUE THREAD

**Issue by rl1234567890** [DivinumOfficium/divinum-officium#3005]
Hi,

Today is an Ember Day. Should there be a commemoration of St. Thecla, beside that of St. Linus for Lauds and Mass? At least Father commemorated both at Mass.

**Comment by KPFC** [comment]
As per the general rubrics (https://divinumofficium.com/www/horas/Help/Rubrics/General%20Rubrics.html#16):

111. The plan for admitting commemorations is this:
c) on other 2nd class liturgical days, only one commemoration is admitted, namely either one privileged or one ordinary commemoration;

So no, only St. Linus would be commemorated.
