### ISSUE TITLE
"epubgen2.sh -m" & EofficiumXhtml.pl

### ISSUE THREAD

**Issue by Geremia** [DivinumOfficium/divinum-officium#3059]
@imjagpul Your changes to EofficiumXhtml.pl in [158e405ff](https://github.com/DivinumOfficium/divinum-officium/commit/158e405ff5450eec3515c3eb5b28269bc6f3d583) aren't consistent with [EofficiumXhtml.pl#L290](https://github.com/DivinumOfficium/divinum-officium/blob/e207e2c81fcbcfae3085b6960886dfa1ec4a83a9/standalone/tools/epubgen2/EofficiumXhtml.pl#L290) and [EofficiumXhtml.pl#L358](https://github.com/DivinumOfficium/divinum-officium/blob/e207e2c81fcbcfae3085b6960886dfa1ec4a83a9/standalone/tools/epubgen2/EofficiumXhtml.pl#L358). EofficiumXhtml.pl always prints:
```html
<br />
<a href="01-06-2022-9-Missa.html"></a>
```
How can EofficiumXhtml.pl detect if the "-m" option is passed to epubgen2.sh?

_Originally posted by @Geremia in https://github.com/DivinumOfficium/divinum-officium/discussions/3058_

**Comment by imjagpul** [comment]
I see. I hardcoded them there as a workaround, because the links in the generated files did not work correctly, probably because of the "Ante" and "Post" links. 

I'll see if I can fix the -m switch by the end of this week.

**Comment by imjagpul** [comment]
I fixed the link depending on the switch. It works somehow, and the epubs can be opened on the PC. 

For now it is in this branch:
https://github.com/imjagpul/divinum-officium/tree/epubgen-missale

However the produced epubs do not pass validation and the kindlegen cannot convert them; I assume that means that some devices won't be able to open them. There is something wrong with the tags. I'll take another look next weekend and open a PR when it is fully functional.

**Comment by Geremia** [comment]
@imjagpul <blockquote>However the produced epubs do not pass validation and the kindlegen cannot convert them; I assume that means that some devices won't be able to open them. There is something wrong with the tags. I'll take another look next weekend and open a PR when it is fully functional.</blockquote>I get an issue, too, when viewing the EPUBs on [KOReader](https://koreader.rocks/): the Missa text doesn't appear. Calibre's ebook-edit can automatically fix the EPUBs, enabling KOReader to display the Missa text.

**Comment by imjagpul** [comment]
There were HTML headers missing in the missale text, which is corrected with PR #3153 

The mass texts are still not fully valid XHTML, but it should not matter, as it seems to work now (tested with KOReader and Kindle Oasis).
