### ISSUE TITLE
3rd Sunday of Advent Dec. 11, 2022, Vespers, Commemorations Divino Afflatu

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#3068]
The commemorations are in the opposite order from what's presented: the octave of the Immaculate Conception, then the pope.

~~There are two other issues: one, the octave commemoration is made from I Vespers as the octave resumes the next day on the general calendar, but the Lauds antiphon is currently displayed. Two, as far as I can tell, this is indeed a case where the antiphon Dum esset summus Pontifex is used. There is only one commemoration of a confessor bishop, so the Lauds antiphon Euge, serve bone wouldn't be needed (this is the one currently given).~~

Fixed the incorrect date in the title.

**Comment by MRoth1910** [comment]
Egads! I thought I had clicked through to Vespers, and I did not. The antiphons are correct, but they're still in the wrong order. The octave is first, then Pope St Damasus is commemorated.

**Comment by APMarcello3** [comment]
Following the Ordo found here: http://www.traditio.com/calendar/cal2212.pdf it appears the commemoration of the Pope comes first ...

**Comment by MRoth1910** [comment]
Hmm. My ordo and [this one](https://ordo.restorethe54.com/ordo/2022/12/11/) both have octave, then St Damasus as the octave is resumed as a concurring office commemorated first, whereas if a Sunday of Advent falls on Dec 10, then the order would be St Damasus, then the octave, since a double (even, as far as I can tell, the simplified doubles) is ranked higher than days within most octaves.

**Comment by MRoth1910** [comment]
I found an ordo for Vilnius from 1938; it also has octave, St Damasus and not.

**Comment by MRoth1910** [comment]
Saturday, Dec 10, 2022: commemorations are made **of the octave** from II Vespers (which is currently listed, but in the last place) and then of St Damasus.

Monday, Dec 12,, 2022: correct.

Tuesday, Dec 13, 2022: correct.

Wednesday, Dec 14, 2022: correct, but the collect is that of the 3rd Sunday as on the other ferial days (this is indicated in the breviary itself, not just in the ordo — and not all historical ordines do so)

When Saturday is Dec 11, the prayers are St Damasas, **then** the octave. I checked another ordo, from 1937; obviously, they could make mistakes too, but generally speaking the sources all agree…
