### ISSUE TITLE
Calendar for all years after 2015 is broken

### ISSUE THREAD

**Issue by peterdiekertz** [DivinumOfficium/divinum-officium#309]
It works for all other states of the calendar.

**Comment by rl1234567890** [comment]
Somebody wrote to me and told me the feast of Christ the King for 2016 is not reported. I assume this is the same problem and a new issue does not need to be opened.

**Comment by gregordick** [comment]
The problem is that the transfer tables were calculated by Laszlo Kiss up until the end of 2015 only.  The `calcalc` branch makes these tables unnecessary.  Before the end of the year I will either merge the branch or (as is looking increasingly likely!) generate tables for 2016.

**Comment by gregordick** [comment]
Retitling this to make it a catch-all bug for manifestations of the missing transfer tables after 2015.

**Comment by gregordick** [comment]
Transfer tables have been pushed.  Please let me know of any errors.  I'll leave this issue open until I've updated the ordo.

**Comment by APMarcello3** [comment]
At least until calcalc is implemented, for any year for which there is no transfer table, Divino Afflatu should default to another version (presumably 1955) rather than display nothing. For example, consider the Divino Afflatu kalendarium for 2024.
