### ISSUE TITLE
Common of non-virgins lacks antiphon for Benedictus

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3095]
The recent cleanup of C7a seems to have been a little too zealous, because St. Monica now has no Ant 2.

See https://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=5-4-2022&command=prayLaudes&version=Rubrics%201960&testmode=regular&lang2=English&votive=

**Comment by FAJ-Munich** [comment]
Dear @APMarcello3 ,
This error is a very strange behaviour in the code: In C7a.txt, I had referenced Commune/C7 globally on line 1. Hence, I presumed all local links like the reinstated one for [Ant 2] are unneccessary. In addition, I would imagine that these links are neccessary in the Latin txt-files only as these should be used in the translations as well. 
Strangly, this error only occurs for the Benedictus Antiphon but not the Magnificat Ant. 
As time permits, I'll check where this behaviour comes from and why it did not occur yet in the cleanups for the other communes C1 through C6.
