### ISSUE TITLE
Epubgen2 error - line 188?

### ISSUE THREAD

**Issue by ilheranson** [DivinumOfficium/divinum-officium#3127]
When attempting to generate .epub files [Divino Afflatu rubrics, for 2023-2024] with the Docker method (On a Mac, if that makes a difference), it generates epubs with an error message in place of the content.
The error messages:

“This page contains the following errors:error on line 37 at column 5: Extra content at the end of the document
Below is a rendering of the page up to the first error.”

“Software error:
Undefined subroutine &horas::setvrbar called at /var/www/standalone/tools/epubgen2/../../../web/cgi-bin/horas/horas.pl line 188.

For help, please send mail to this site's webmaster, giving this error message
and the time and date of the error.”

It was a lot for me to figure out how to navigate the terminal, so this is something beyond me to fix. Perhaps someone here can help me out with this?

**Comment by imjagpul** [comment]
I'm on it.

I have reproduced this error today as well (on Windows / WSL), it looks more like a breaking change in the core (horas.pl), not in the generator script itself (it works fine with older versions).

**Comment by imjagpul** [comment]
Fixed in the linked PR, it should work after the PR gets merged. 

I generated the [Divino Afflatu version](https://breviarium.srubarovi.cz/da.html) if it helps.

**Comment by rl1234567890** [comment]
It does not work for the Mass

**Comment by ilheranson** [comment]
> Fixed in the linked PR, it should work after the PR gets merged.
> 
> I generated the [Divino Afflatu version](https://breviarium.srubarovi.cz/da.html) if it helps.

Thank you!

**Comment by imjagpul** [comment]
> It does not work for the Mass

As posted to #3059 , the generator now works for the Mass, too.

I believe this issue can be closed.
