### ISSUE TITLE
23 July: Saturday Commemoration of St. Liborius

### ISSUE THREAD

**Issue by petermottola** [DivinumOfficium/divinum-officium#313]
The Commemoration of St. Liborius on 23 July traditionally has a different Collect when the feast falls on Saturdays.  This distinction was removed in 1962 (or so witnesses my 1963 Collegeville breviary), but is preserved erroneously.  Cf. e.g. 7-23-2011.

**Comment by APMarcello3** [comment]
Closed by  cf7527c
