### ISSUE TITLE
[Epub] Incorrect links on top of hours

### ISSUE THREAD

**Issue by jperon** [DivinumOfficium/divinum-officium#3134]
When generating an epub with epugen2, the links at the beginning of hours don’t include "Matutinum" any more, but the "Laudes" link points to Matutinum, "Prima" to Laudes and so on.

**Comment by Geremia** [comment]
I get all kinds of incorrect links when using KOReader.
Calibre's ebook-edit can automatically fix the problems in the EPUB. Here's an example error it reports:

> Error [1 / 310]
> 01-01-2023-9-Missa.html (line: 1 column: 10)
> A parsing error in an HTML file means that the HTML syntax is incorrect. Most readers will automatically ignore such errors, but they may result in incorrect display of content. These errors can usually be fixed automatically, however, automatic fixing can sometimes "do the wrong thing".
> Try to correct all fixable errors automatically
> 
> Re-run check
