### ISSUE TITLE
matins reading for week of Jan 9, 2023

### ISSUE THREAD

**Issue by 834659** [DivinumOfficium/divinum-officium#3138]
The matins readings on divinum-officium are different from those for the priest's breviary for 1962. The former has readings from 1 Corinthians and the latter from Romans. Please explain the discrepancy.

**Comment by APMarcello3** [comment]
![Screenshot_20230113-151134_OfficeSuite.jpg](https://user-images.githubusercontent.com/11463422/212410707-6d743e89-f2e6-4e7c-9196-1423c3223b02.jpg)
