### ISSUE TITLE
Deo gratias is missing at None on the feast of St. Bridget

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3225]
7bfcf3207 removed `$Deo gratias` from `[Capitulum Nona]` of `horas/Latin/Commune/C7a.txt`. Consequently, the feast of St. Bridget (which is not celebrated this year) lacks "Deo gratias" after the chapter at None. See https://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=10-8-2024&command=prayNona&version=Rubrics%201960&testmode=regular&lang2=English&votive=

Was the above change made to fix some other issue, or was it just a mistake?

**Comment by fiapps** [comment]
The fix (33173ef) has restored Deo gratias, but the chapter is now in Latin in the English column (see the link in the initial report).

**Comment by APMarcello3** [comment]
Fixed by 5110023db.

**Comment by APMarcello3** [comment]
https://github.com/DivinumOfficium/divinum-officium/commit/42967a5538a65d1f9c5b28c9c4a2fb8d222812dc
