### ISSUE TITLE
an't use string ("") as a HASH ref while "strict refs" in use horascommon.pl line 1690.

### ISSUE THREAD

**Issue by jeremychua** [DivinumOfficium/divinum-officium#3238]
This error occurs after commit 4144b19 / fix 3234/5

Can't use string ("") as a HASH ref while "strict refs" in use at /standalone/tools/epubgen2/../../../web/cgi-bin/horas/horascommon.pl line 1690.
For help, please send mail to this site's webmaster, giving this error message and the time and date of the error.

Error occurs running ./epubgen2.sh on Arch Linux via the terminal.

**Comment by mbab** [comment]
If You don't need missa in output look at: https://mbab1.gitlab.io/divinumofficium.epub/
