### ISSUE TITLE
Rank of Trinity Sunday

### ISSUE THREAD

**Issue by mkbertrand** [DivinumOfficium/divinum-officium#3251]
Trinity Sunday should be Duplex II Class for 1910 and 1570.

**Comment by APMarcello3** [comment]
This is incorrect, per the Marquess of Bute breviary.

**Comment by mkbertrand** [comment]
What is labelled as 1910 is based off of the 1888 Pustet according to https://www.divinumofficium.com/www/horas/Help/versions.html and this version labels Trinity as second class.  Trinity was raised to first class by St. Pius X in 1911 (see Acta Ap. Sedis, III, 351)

**Comment by mbab** [comment]
What I found is [1580](https://archive.org/details/breviariumromanum1580/page/n27/mode/1up) and [1888](https://archive.org/details/p1breviariumroma00cathuoft/page/n49/mode/1up) books list it as  **DOMINICAE PRIMAE classis**.

**Comment by mkbertrand** [comment]
![image](https://github.com/DivinumOfficium/divinum-officium/assets/94151976/424f83ee-0d9c-48f6-bc2e-d9c425f975d6)
![image](https://github.com/DivinumOfficium/divinum-officium/assets/94151976/4f95c6b5-e905-436c-9ced-4389e0441743)
The books you just cite them list them as Double of the Second Class, as well as Sunday of the First Class.  They're not mutually exclusive, but calling it a Double of the First Class is incorrect.
