### ISSUE TITLE
"Dark mode" on macOS

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#3265]
I'm not sure if I'm missing something, but:

The black background and white text looks terrible. I would like to turn it off. I would even go so far as to say that I would like it removed entirely — normally, I prefer dark mode, and that's my default for macOS, but background and white text looks terrible. But if people really want it, I would settle for an easy-to-locate setting that is remembered with the rubrical choices.

Also, the menus to change the office rubrics, the language of the right-hand column, and to choose a votive Mass are now white-on-white…
<img width="519" alt="Screenshot 2023-06-13 at 22 44 24" src="https://github.com/DivinumOfficium/divinum-officium/assets/68782573/6abe6603-719c-4e35-9923-2f072dd6587a">

**Comment by mbab** [comment]
Did You try turn off _Contrast background_ option?

**Comment by MRoth1910** [comment]
@mbab I did once you pointed it out. But because I can't see the OK button, it took me multiple tries to fix. And while it fixed the date contrast, the other menus are still white-on-white.

@APMarcello3 well, the website which I use multiple times a week (and to which I contribute as I can, according to my abilities) is now essentially unusable on my main device. I don't know who asked for this change, and I don't want to take things away if people really wanted it. But it's not working.

The problem is that the change probably won't stick. I not-infrequently come back to find that the site reverted to 1960 from Divino Afflatu, then I change it back to DA, and after I click on the Ordo, it switches to 1960 again. What a headache. (I unchecked "contrast background" but then it's checked again.)!

To put it mildly, touching the website's aesthetics isn't something to be done considering the fragility of it.

[image](https://github.com/DivinumOfficium/divinum-officium/assets/68782573/3e39e294-9fb7-4ad5-9d44-f0926f49c705)

[image](https://github.com/DivinumOfficium/divinum-officium/assets/68782573/a635b99e-f773-4c76-b3b3-9f46cadb47ce)

![image](https://github.com/DivinumOfficium/divinum-officium/assets/68782573/667bdd97-bf84-4726-a086-8a469d55d00c)

**Comment by APMarcello3** [comment]
@MRoth1910 The website reverts to 1960 because the 1960 code of rubrics is normative.

**Comment by MRoth1910** [comment]
Which doesn't address the entirety of my complaint.

The website reverting to 1960, in between visits, is annoying but I could in theory live with it, but I then change the office _**back**_ to Divino Afflatu which is promptly ignored when changing "tabs". That's not cool.

Never mind the fact that the "normative" question is beside the point — if someone wants to use Divino Afflatu for whatever reason, for prayer or otherwise, well, who cares? The site should be accurate — and I am the first to recognize how hard this is to do — and functional. Currently its functionality has been reduced.

Anyway, I don't see how this change is good or useful — again, in what way are white-on-white menus useful? I'll prescind from how awful I think the dark mode is. That part is broken and should be fixed.

**Comment by mbab** [comment]
I'm sorry for all Your troubles introduced in last changes, I'm willing to help, but You even didn't specify software You are using. Did You try other browser?

Issue with returning to 1960 can be caused by refusing cookies.

**Comment by MRoth1910** [comment]
I did forget to specify the version: Ventura 13.4, in both Safari and Chrome (both up to date).
