### ISSUE TITLE
Sundays of Lent incorrect rank

### ISSUE THREAD

**Issue by mkbertrand** [DivinumOfficium/divinum-officium#3308]
Sundays II, III, IV of Lent are meant to be II Class as per 1888 Breviary but are I Class in Divinum Officium.
![image](https://github.com/DivinumOfficium/divinum-officium/assets/94151976/a8a7cddc-4bd4-4c9d-8488-0899ffc14c48)

**Comment by FAJ-Munich** [comment]
This is addressed in my pull request from just now as well. #3309
