### ISSUE TITLE
More errors caused by recent changes

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3320]
1. With the 1570 rubrics, 11-2 is now the second day in the octave of All Saints instead of All Souls: https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=11-2-2023&command=prayVesperae&version=Tridentine%201570&testmode=regular&lang2=English&votive=
2. Easter Sunday Matins now has _Ille nos benedicat_ instead of _Evangelica lectio_ before the Gospel reading (1960 rubrics): https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=4-9-2023&command=prayMatutinum&version=Rubrics%201960&testmode=regular&lang2=English&votive=

**Comment by APMarcello3** [comment]
Closed by 2 most recent commits.

**Comment by FAJ-Munich** [comment]
> With the 1570 rubrics, 11-2 is now the second day in the octave of All Saints instead of All Souls:

... and that is exactly what it should be! All Souls day has not been superseding the day in the octave until Divino Afflatu but it was merely commemorated by the Office of the Dead being said at Vespers on Nov 1 and after Laudes on Nov2. If Nov 2 is a Sunday, then the Office of the Dead has been shifted by one day, i.e., Vespers at Nov 2 Sunday and Mat+Laud at Nov 3 Monday Lauds. 
![image](https://github.com/DivinumOfficium/divinum-officium/assets/60485740/fcd9ddf3-f73b-4bb7-8af1-07f8088fa8e3)

**Comment by fiapps** [comment]
I find that surprising, but the breviary page you show seems clear.
