### ISSUE TITLE
Sept. 21 St. Matthew 1910 rubrics

### ISSUE THREAD

**Issue by PaulDang1** [DivinumOfficium/divinum-officium#3376]
For the First Nocturn of Matin readings for St. Matthew, it should be Ezechiel 1:1-17.

**Comment by APMarcello3** [comment]
Closed by ed1454851392ae8ef7b538df3db73d799ed683e9

**Comment by APMarcello3** [comment]
Closed by ed1454851392ae8ef7b538df3db73d799ed683e9
