### ISSUE TITLE
Transferred Responsories of the Sundays of Advent

### ISSUE THREAD

**Issue by petermottola** [DivinumOfficium/divinum-officium#338]
In a 1946 breviary I see a rubric for the Second Sunday Advent that instructs that the responsories for the first Nocturn of Matins, if impeded, are transferred to the first weekday in which the ferial cycle of the Scriptures occurs, omitting any other responsory.  The text is as follows:
"Rensponsoria hujus Nocturni, si hac nocte dici non pouterint, ponuntur prima die infra hebdomadam, in qua Lectiones de Scriptura dici contingat, omissis aliis Responsoriis in eadem Feria secus recitandiis.  Quod fit etiam in reliquis hebdomadis Adventus."

Looking at 8 and 9 December 2013 it can be seen that the responsory "Jerusalem cito" is not properly transferred.  I'm unsure how far back this rubric held sway (though it certainly no longer applies for 1960), but it looks like some new logic will need to be written to make sure this is handled properly for each feria of Advent.  I am also uncertain as to why this rubric is only listed in the Second week of Advent rather than the first, unless perhaps they anticipated that the Immaculate Conception was practically the only case that would cause this to happen.

**Comment by gregordick** [comment]
Pre-Divino, no feasts could beat an Advent Sunday.  With Divino, the first Sunday of Advent became a greater Sunday of the first class, yielding to no feast, but the remaining Sundays were of the second class, yielding to doubles of the first class.

The Sundays of Septuagesimatide are likewise of the second class, and the lessons, responsories and antiphons of the whole season float around quite a bit.
