### ISSUE TITLE
1910 September 29 (St. Michael) Issue of First Nocturn Readings and Responsories

### ISSUE THREAD

**Issue by PaulDang1** [DivinumOfficium/divinum-officium#3382]
It's funny that the first Nocturn readings and responsories are that of Esther and the ferial day! The Divino Afflatu rubrics are working fine, so I wonder what's wrong. The code is correct, as far as I can tell.

**Comment by APMarcello3** [comment]
Closed by 35cd5c995963ac5826c5e1c31868bedc38b24173
