### ISSUE TITLE
 Commemoration at Vespers of Nov 5, 2023 (Divino Afflatu)

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#3416]
Under 1911, the rubric is that if, at Vespers of a Sunday or of another feast, the office the following day is of the day within the octave, then the antiphon and verse are from I Vespers (if not, then it is from II Vespers). This is the case at Vespers of Sunday, Nov 5, 2023: the next day (Monday, Nov 6) is aa day within the octave of All Saints, so the antiphon should be Angeli, archangeli with the verse as at I Vespers, but those of II Vespers are given.

**Comment by APMarcello3** [comment]
Closed by 876c01293
