### ISSUE TITLE
1888 Tridentine rankings need to be checked

### ISSUE THREAD

**Issue by PaulDang1** [DivinumOfficium/divinum-officium#3421]
November 9, Dedication of St. Savior, is a Double for 1888.

**Comment by APMarcello3** [comment]
This is incorrect (cf. Breviarium Romanum Autumnalis, 1906)

![image](https://github.com/DivinumOfficium/divinum-officium/assets/11463422/5857139a-6b03-4cb3-9c7b-da9b61930e69)

**Comment by FAJ-Munich** [comment]
Since @PaulDang1 has been referring to 1888 specifically, @APMarcello3 , I would not call it incorrect:
![11-09_1888](https://github.com/DivinumOfficium/divinum-officium/assets/60485740/414f6eb9-5e85-450a-8a54-b335157a5f57)
(cf. Breviarum Romanum, Pars Autumnalis, 1888)

**Comment by APMarcello3** [comment]
A decision has been made to transfer to the 1906 edition and changes will be made to reflect this going forward.

**Comment by FAJ-Munich** [comment]
Is the 1906 version available for free download on the internet as well just like the 1888? Otherwise it would be hard to support without access to the source.

**Comment by mbab** [comment]
https://archive.org/search?query=breviarium+romanum+1906

I prepared 1906 calendar file but i'm afraid to introduce changes as transfer tables need to be changed.
@FAJ-Munich do You have some automation tool for transfer tables?

Here is diff
```							      >	02-11=02-12=Ss. Septem Fundatorum Ordinis Servorum B. M. V.=3
03-25=03-25=In Annuntiatione Beate Mariæ Virginis=5=	      |	03-25=03-25=In Annuntiatione Beate Mariæ Virginis=6=
							      >	03-27=03-27=S. Joannis Damascene Confessor=3=
							      >	03-28=03-28=S. Joannis Capistrano Confessor=2=
05-27=05-27=S. Bede Venerabilis Pries Confessor=4=	      |	05-27=05-27=S. Bede Venerabilis Pries Confessor=3=
07-05=07-07=Ss. Cyrilli et Methodii Pont et Conf=3=	      |	07-05=07-05=S. Antonii Mariae Zacharia Confessor=3=
							      >	07-07=07-07=Ss. Cyrilli et Methodii Pont et Conf=3=
08-25=08-25=S. Ludovioci Confessoris=3=			      |	08-25=08-25=S. Ludovioci Confessoris=2=
09-14=09-14=In Exaltatione Sanctae crucis=5=		      |	09-14=09-14=In Exaltatione Sanctae crucis=4=
11-17=11-17=S. Gregorii Thaumaturgi Episcopi et Confessoris=3 |	11-17=11-17=S. Gregorii Thaumaturgi Episcopi et Confessoris=2
12-15=12-15=In Octava Immaculatae Concept Beatae Mariae Virgi |	12-15=12-15=In Octava Immaculatae Concept Beatae Mariae Virgi
12-29=12-29o=S. Thomae Episcopi et Martyris=2=		      |	12-29=12-29o=S. Thomae Episcopi et Martyris=3=
```

**Comment by FAJ-Munich** [comment]
Hi @mbab 
Thanks for the link, I'll check it out. 
Regarding the new calendar file and transfer tables, I am almost done with the new occurrence/concurrence/commemorations routine. Hopefully I can open the pull request by the ending the week. 
As one important feature, I have programmed a possibility to transfer offices without their attached commemorations and giving them the chance to inherit commemorations from their transferred date. 

One open topic is exactly to go over the transfer tables to make use of the new feature. Doing this for the 1906 table is then probably a wise decision.
