### ISSUE TITLE
Vernacular commemorations appearing in Latin

### ISSUE THREAD

**Issue by APMarcello3** [DivinumOfficium/divinum-officium#3453]
![Divinum Officium Laudes.png](https://github.com/DivinumOfficium/divinum-officium/assets/11463422/97e2aae4-758e-4522-bbdd-8a8bb0b85639)

From a correspondent. The French translations are given in the respective files but these appear in Latin. I suspect the new commemoration logic may be causing this issue.

@FAJ-Munich would you kindly investigate?

**Comment by FAJ-Munich** [comment]
Just saw that the Latin [Commemoratio] in other cases also supersedes the Vernacular... 
I'll investigate further in the code

**Comment by APMarcello3** [comment]
@benyanke could perhaps give some insight as he is working on this issue.

**Comment by benyanke** [comment]
Hi All - just rolled the deployment manually, and will continue to work on improving the deployment automation.
