### ISSUE TITLE
"Vespera de Officium occurente" replaces identification of commemoration at vespers

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3458]
At Vespers, the annotations "Vespera de Officium occurente" and "Vespera de Officium occurente; nihil de sequenti" have become common. With the 1960 rubrics, this is usually stating the obvious, but there may be no harm in that.

Where there is a commemoration, however, these notices take its place. So on [12-21-2023](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=12-21-2023&command=prayVesperae&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=), instead of "Commemoratio: <span class='liturgical-color-purple'>Feria VI Quattuor Temporum Adventus", we have "Vespera de Officium occurente". The commemoration is made in the proper place, but there's no notice of it in the heading as there formerly was.

**Comment by FAJ-Munich** [comment]
> With the 1960 rubrics, this is usually stating the obvious,

I agree this info is overkill in 1960 version. Am going to remove but keep when it is different.

> So on [12-21-2023](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=12-21-2023&command=prayVesperae&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=), instead of "Commemoratio: Feria VI Quattuor Temporum Adventus", we have "Vespera de Officium occurente".

I removed the Vespers annotation to avoid stating wrong commemorations of Simplex (pre-1960) or Commemoration ad Laudes tantum at 2nd Vespers. Didn't remember to keep the recurring Tempora. Am going to fix it.

**Comment by fiapps** [comment]
It doesn't look to me as though this is completed. I'm still seeing "Vespera de Officium occurente" instead of "Commemoratio: Feria V infra Hebdomadam III Adventus" [on divinumofficium.com](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=12-21-2023&command=prayVesperae&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=).

**Comment by fiapps** [comment]
This actually is fixed in my fork, so I'm guessing that deployment of the fix to www.divinumofficium.com failed. As far as I'm concerned, this issue is indeed completed.
