### ISSUE TITLE
Issues with the identification of commemorations in the heading of hours

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3459]
This report regards testing with the 1960 Rubrics.

Previous to the recent changes to commemoration handling, the heading or title at the top of hours would show the name of the saint in the vernacular. Now it is in Latin: "S Chrysogoni Martyris" instead of "S Chrysogonus Martyr" ([11-24](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=11-24-2023&command=prayLaudes&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=)), "S Eusebii Confessoris" instead of "S Eusebius Confessor" ([08-14](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=8-14-2024&command=prayLaudes&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=)), etc.

This appears to be caused not by a bug in the new code, but by an oversight in the process of separating the vernacular commemorations into separate *cc.txt files (669c0b1966d4636cdbb20d364e6ff057567c6c3d): in the \[Rank\] section, they have a Latin name for the celebration instead of a vernacular one, in the above and many or all other cases. In my opinion, the vernacular names of the commemorated celebrations should be recovered from the diffs for that commit and any others used to create the *cc.txt files.

I also note two other changes that are not necessarily errors.

1. "Commemoratio ad Laudes tantum" in the heading has usually become "Commemoratio": this is accurate but less complete information. Example: [08-11 Lauds](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=8-11-2023&command=prayLaudes&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=)
2. The split of the temporal and sanctoral cycles into separate files for the Octave of Christmas means that the heading now gives notice of commemorations on these days, e.g., "Commemoratio: Die tertia post Nativitatem" ([12-27](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=12-27-2023&command=prayLaudes&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=)). This is a positive development, in my view, although it would be better if the days of the octave had vernacular names in the vernacular data files.

**Comment by FAJ-Munich** [comment]
> Previous to the recent changes to commemoration handling, the heading or title at the top of hours would show the name of the saint in the vernacular.

I never had this kind of behaviour before implementing the new logic? I just checked an old branch and don't see the verancular unless I go to "compare versions". 

> This appears to be caused not by a bug in the new code, but by an oversight in the process of separating the vernacular commemorations into separate *cc.txt files

For most of the `*cc.txt` I have put the vernacular in so this is not the cause. (Admittingly, I forgot to to do in the earliest files I've produced for testing.) However, the second line is set solely from the Latin files in the precedence() algorithm.  I am not aware that I have changed that behaviour to the previous version. Nonetheless, I agree it makes sense to translate this second headline as well, whenever the title itself is translated because "lang1" is in the vernacular.

> 1. "Commemoratio ad Laudes tantum" in the heading has usually become "Commemoratio": this is accurate but less complete information. Example: [08-11 Lauds](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=8-11-2023&command=prayLaudes&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=)

I am going to bring that info back. 

> 2. ... it would be better if the days of the octave had vernacular names in the vernacular data files.

similar to above on the vernacular 2nd headings.

**Comment by FAJ-Munich** [comment]
This commit (https://github.com/FAJ-Munich/divinum-officium/commit/c8471ed5d557515efc934a78921456edf3752a88) should address the "ad Laudes tantum" issue. I see way more cases than before but think these are correct. Please check if my solution is "overkill" and covers too many cases.

For the Sunday in the Octave of Nativity, this year on Dec 31st, please advise if any Commemorations shall appear ad Laudem:  die Octava? Silvester?

**Comment by fiapps** [comment]
> > Previous to the recent changes to commemoration handling, the heading or title at the top of hours would show the name of the saint in the vernacular.
> 
> I never had this kind of behaviour before implementing the new logic? I just checked an old branch and don't see the verancular unless I go to "compare versions".

What I said was based on testing my fork, which has no intentional difference in functionality from the main repo in this regard. It may be that divinumofficium.com was not previously showing the name of the commemorated celebration, as you say. I'd need to clone the official repo and test with it.

> > This appears to be caused not by a bug in the new code, but by an oversight in the process of separating the vernacular commemorations into separate *cc.txt files
> 
> For most of the `*cc.txt` I have put the vernacular in so this is not the cause. (Admittingly, I forgot to to do in the earliest files I've produced for testing.) However, the second line is set solely from the Latin files in the precedence() algorithm. I am not aware that I have changed that behaviour to the previous version. Nonetheless, I agree it makes sense to translate this second headline as well, whenever the title itself is translated because "lang1" is in the vernacular.

I apologize: I incorrectly thought the problem was universal because it happened in every case I investigated, and I only investigated cases in which a difference was reported. Some `*cc.txt`files do have a vernacular name, but in others it was lost in the process of conversion. Here are some examples in `horas/English/Sancti`:

- [`01-11cc.txt`](https://github.com/DivinumOfficium/divinum-officium/blob/master/web/www/horas/English/Sancti/01-11cc.txt) has "S. Hyginus Papae et Martyris" in `[Rank]`. The commemoration that used to be in `01-11.txt`had "Commemoration of St. Hyginus, Pope and Martyr".
- [`08-14cc.txt`](https://github.com/DivinumOfficium/divinum-officium/blob/master/web/www/horas/English/Sancti/08-14cc.txt) has "S. Eusebii Confessoris" in `[Rank]`. The commemoration that used to be in `08-14.txt`had "Commemoration of S. Eusebius, Confessor".
- [`09-15cc.txt`](https://github.com/DivinumOfficium/divinum-officium/blob/master/web/www/horas/English/Sancti/09-15cc.txt) has "S. Nicomedis Martyris" in `[Rank]`. The commemoration that used to be in `09-15.txt`had "Commemoration of St. Nicomedes, Martyr".

Other cases I found in 669c0b1966d4636cdbb20d364e6ff057567c6c3d are the Deutsch, Espanol, and Francais `09-15cc.txt` and the Italiano `08-14cc.txt`.

**Comment by fiapps** [comment]
> This commit ([FAJ-Munich@c8471ed](https://github.com/FAJ-Munich/divinum-officium/commit/c8471ed5d557515efc934a78921456edf3752a88)) should address the "ad Laudes tantum" issue. I see way more cases than before but think these are correct. Please check if my solution is "overkill" and covers too many cases.

Testing this with a subset of my test cases, I find that it fixed all problem cases and added "ad Laudes tantum" on 08-14, where it probably should have been there all along.

**Comment by FAJ-Munich** [comment]
> ... `01-11cc.txt`, `08-14cc.txt` in English and `09-15cc.txt` in several vernaculars

This list sounds very plausible as these were my earliest test cases for coding. Thanks for the list!

**Comment by fiapps** [comment]
FWIW, vernacular commemoration names have returned in my fork.

**Comment by FAJ-Munich** [comment]
> vernacular commemoration names have returned in my fork

Would you be so kind to share a screenshot of how it is supposed to look like please.

**Comment by fiapps** [comment]
> > vernacular commemoration names have returned in my fork
> 
> Would you be so kind to share a screenshot of how it is supposed to look like please. I guess the vernaculars went missing from your developments by the same cause as issue #3453

@FAJ-Munich Either I was wrong about it coming back, or it disappeared again after a further change. In any case, the headline and comment line are consistent now that both are always in Latin (when `lang1`is Latin).
