### ISSUE TITLE
1570 rubrics: 11-5-2022 Vespers are now Dominica XXII Post Pentecosten I. instead of III. Novembris

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3464]
Since I know very little about Tridentine rubrics, I report this as something I noticed without being able to say whether it is a bug or an improvement. As a premise, I've now cloned the official repo and checked out c044962cf11899082e49ece5b6c546a809c2bba6 (the commit just before the commemoration changes were merged) so I can verify that changes I'm seeing with my fork also affect the official repo.

At that commit, the vespers of 11-5-2022 used to be "Dominica XXII Post Pentecosten III. Novembris ~ Simplex Dominica anticipiata". [Now](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=11-5-2022&command=prayVesperae&version=Tridentine%20-%201570&testmode=regular&lang2=English&votive=) they are "Dominica XXII Post Pentecosten I. Novembris ~ Semiduplex Dominica minor". This changes the psalms and antiphons.

On the positive side, most of the changes I'm seeing with the 1570 rubrics are the proper vernacular (Polish in this case) replacing English translations. I assume this is due to the consolidation of data files.

**Comment by FAJ-Munich** [comment]
Apperantly, the routine for adding the weeks from Aufust to November fails to realise we're saying Vespers of tomorrow and adds the I. Novembers which is correct until None of Nov. 5. 
Am going to look at it later. 

On a general notice, as mentioned in the pull request with the new Occurrence routine, I priorised the Transfer tables valid in 2023 and 2024 only. In other years, there are still significant changes to the transfer tables to be expected (especially for 1570 version).

**Comment by FAJ-Munich** [comment]
_Simplex Dominica anticipiata_ was wrong and so was _I. Novembris_   
The correct one is **III. Novembris - Semiduplex Dominica minor**
