### ISSUE TITLE
Saturday Advent Preces Feriales at Vespers (Divino Afflatu)

### ISSUE THREAD

**Issue by APMarcello3** [DivinumOfficium/divinum-officium#3476]
From a correspondent (attention @FAJ-Munich ):

"I was looking at the Divino Afflatu section of the breviary today and I noticed a rubrical error, namely that the preces are said in vespers today. In Divino Afflatu rubrics, preces are never said in vespers on Saturday, even in seasons of penance, because Saturday vespers is normally first vespers of Sunday, and preces feriales are never said in the Sunday office. And if the Sunday is overridden by a high feast, that would also prevent the preces from being said in Saturday vespers."

**Comment by FAJ-Munich** [comment]
I just checked and old branch of mine and this is no new behaviour of the code. (Would have surprised me as I did not touch the preceding function). 

Either way, I am happy to investigate into that mentioned rubric as the correspondent sounds convinced he knows what he is talking about.
