### ISSUE TITLE
1960 rubrics: second commemoration (St. Canute) missing on January 19

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3477]
On January 19, there should be two commemorations at Lauds with the 1960 rubrics: first _Commemoratio Ss. Marii, Marthæ, Audifacis, et Abachum Martyrum,_ then _Commemoratio S. Canuti Martyris._ The [second one is missing](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=1-19-2024&command=prayLaudes&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=). Perhaps when the simplex is reduced to a commemoration, the commemoration already in a \[Commemoratio\] section is lost.

**Comment by fiapps** [comment]
[9-1 Lauds](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=1-19-2024&command=prayLaudes&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=) looks like another case of this.

**Comment by FAJ-Munich** [comment]
There has been a part in the code I recycled which limits commemorations in 1960 rubrics to at most one. As I am not well versed in these, what you are saying is that this limitation I had found in the code is to narrow?

**Comment by FAJ-Munich** [comment]
I just realised, this issue has had nothing to do with the restricting routine mentioned above. It has been an oversight of mine when recombining the Vespers and Laudes commemorations back together. **Mea culpa!**
