### ISSUE TITLE
Did St. Thomas of Canterbury become a duplex between 1888 and 1906?

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3480]
`Pofficium.pl`shows 12-29-2023 as a semiduplex in the 1570 and [1888 version](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=12-29-2023&version=Tridentine%20-%201888&testmode=regular&lang2=English&votive=)s, but [a duplex in the 1906 version](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=12-29-2023&version=Tridentine%20-%201906&testmode=regular&lang2=English&votive=). Is that correct or an error in the calendar file?

**Comment by APMarcello3** [comment]
![messages_0](https://github.com/DivinumOfficium/divinum-officium/assets/11463422/65d9208f-f047-434e-9906-9fbfeee3cc5c)
