### ISSUE TITLE
Missing commemorations of II class Sundays on I class feasts with 1960 rubrics

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3486]
Commemorations of Sundays are privileged (108 a in the general rubrics), and on I class feasts only one commemoration is permitted, and only if it's privileged (111 a). So when a I class feast falls on a II class Sunday, the Sunday must be commemorated, and this is done at Lauds and Vespers (see tabella occurentiae). This is not happening on [6-24-2018](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=6-24-2018&command=prayLaudes&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=), [11-1-2020](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=11-1-2020&command=prayLaudes&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=), [8-15-2021](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=8-15-2021&command=prayLaudes&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=), and probably in general.

**Comment by APMarcello3** [comment]
N.B. Christus Rex is an exception to this principle, as it is a feast of Our Lord.
