### ISSUE TITLE
1570 rubrics seem to have II Vespers of Sunday instead of I Vespers on Saturday 11-4-2023

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3496]
For the [Vespers of Saturday, 11-4-2023](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=11-4-2023&command=prayVesperae&version=Tridentine%20-%201570&testmode=regular&lang2=English&votive=), I now see what looks to me like II Vespers, with the headline "Dominica XXIII Post Pentecosten II. Novembris ~ Semiduplex Dominica minor" and psamody beginning with Psalm 109. Previously (c044962cf), this was "Dominica XXIII Post Pentecosten II. Novembris ~ Simplex Dominica anticipiata" and the psalmody began with Psalm 143.

**Comment by FAJ-Munich** [comment]
Hi @fiapps 
Yes what you observe is intended. What looks like II Vespers is the II vespers of the day within the octave (semiduplex) which – a capitulo – goes over into I vespers of the Sunday which is also Semiduplex. 

The Tridentine rubrics are truly a piece of art: as Saturday is festal, the psalmody of the vespers at the beginning of Sunday does not suddenly become Ferial. Like a Simplex in the Sanctorale, Sunday offices only commenced at the chapter. The cases of a "A capitulo de seq." are far more abundant in Tridentine rubrics than after Divino Afflatu. On Saturday Nov 4 in Divino Afflatu we have the absurd situation of concurrence between the Duplex feast S. Caroli Ep. & Conf. with the Semiduplex Sunday (privileged by DA) resulting in a Ferial psalmody despite all the festivity.
