### ISSUE TITLE
Order of commemorations changed with Divino afflatu at 6-12-2024 Vespers

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3497]
I don't know whether the new or old behavior is correct, so I draw attention to the change so someone competent in the Divino afflatu rubrics can decide.

Previously (c044962cf), with the Divino afflatu rubrics on 6-12-2024, the Octave of the Sacred Heart was commemorated first, followed by S. Joannis a S. Facundo. [Currently](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=6-12-2024&command=prayVesperae&version=Divino%20Afflatu%20-%201954&testmode=regular&lang2=English&votive=#Vespera9) the order of these commemorations is reversed, so that the saint comes first and then the octave.

**Comment by APMarcello3** [comment]
Cf. General Rubrics, IX (De Commemoratione), n. 11. Doubles take precedence over common octaves in the order of listing commemorations. So the site now displays correctly.
