### ISSUE TITLE
Should Divino afflatu use Sunday psalmody on Monday 6-13-2022 Vespers for the Duplex of St. Basil?

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3498]
This is another one that has to be judged by someone competent in the Divino afflatu rubrics.

Previously (c044962cf), with the Divino afflatu rubrics on 6-13-2022, the psalmody at Vespers was from the weekday (114, 115, …). [Now it's the Sunday psalmody](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=6-13-2022&command=prayVesperae&version=Divino%20Afflatu%20-%201954&testmode=regular&lang2=English&votive=#Vespera2) (109, 110, …). In both cases, the headline is "S. Basilii Magni Confessoris et Ecclesiæ Doctoris ~ Duplex".

**Comment by FAJ-Munich** [comment]
This one is well spotted. For DA the Commune Antiphones in the "A capitulo" cases have to be excluded where the psalmody is Ferial.

**Comment by fiapps** [comment]
Thanks for the fix. I've now reported all the issues that concerned me and deployed the new code.

**Comment by FAJ-Munich** [comment]
@fiapps  Thanks for pointing out all these oversights on my side. I would never have been able to spot them in such a short period of time and fix them if on my own.
