### ISSUE TITLE
Prayers at the foot of the altar not omitted in some translations

### ISSUE THREAD

**Issue by theodotk** [DivinumOfficium/divinum-officium#3513]
Looking at February 2 and Ash Wednesday I notice that translations into several languages don't omit prayers at the foot of the altar after procession/imposition of ashes, namely:
- Czech
- French
- Ukrainian
This seems independent on whether a language has a translation of propers on that day or not.
And this leads to mismatch with Latin text.

**Comment by APMarcello3** [comment]
Closed. It is necessary that the prayers at the foot of the altar be labelled as Incipit in every translation for this to function appropriately.

**Comment by mbab** [comment]
And translation of _Incipit_ should be provided in `Prayers.txt`
