### ISSUE TITLE
Collects for office during the octave of Pentecost (DA, at least)

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#3521]
The days in the octave of Pentecost have proper collects except for Thursday, which simply repeats that of the feast, but Ember Wednesday and Ember Friday also have this collect, when it should be proper (also, I'm looking at Vespers specifically in case that helps narrow things down).

**Comment by APMarcello3** [comment]
@FAJ-Munich This appears to be a logic error.

**Comment by FAJ-Munich** [comment]
The responsible code for that in `specials.pl` is in **line 1141**
```
if ( ($rule =~ /Oratio Dominica/i && (!exists($w{Oratio}) || $hora =~ /Vespera/i))
    || ($winner{Rank} =~ /Quattuor/i && $version !~ /196/ && $hora =~ /Vespera/i))
  {
    my $name = "$dayname[0]-0";
    if ($name =~ /(Epi1|Nat)/i && $version !~ /monastic/i) { $name = 'Epi1-0a'; }
    %w = %{setupstring($lang, subdirname('Tempora', $version) . "$name.txt")};
  }
```
This part of the code literally goes back to the inital import according to the GitHub blame functionality.
