### ISSUE TITLE
Espaces insécables

### ISSUE THREAD

**Issue by Sanctusmarcus** [DivinumOfficium/divinum-officium#3546]
La typographie française n'est pas respectée - il faut des espaces insécables avant les ? ! ; :
Je ne peux pas modifier directement ce document apparemment.

https://github.com/DivinumOfficium/divinum-officium/blame/2cb2f86e8f765c2d8a3cda73aed33049f30dfa54/web/www/horas/Francais/Tempora/Nat31.txt#L29

**Comment by APMarcello3** [comment]
Certes, vous pouvez ajouter les espaces avant la ponctuation pour les textes en français. Faites attention seulement aux lignes de code comme [Rank] ou [Rule], où il faut garder l'orthographe sans espace. Il me semble dans le lien que vous étiez sur une autre branche du répo créée par FAJ-Munich.
