### ISSUE TITLE
Die Octavæ Nativitatis Domini is identified as "II. classis" (1960 rubrics)

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3558]
A correspondent pointed out to me that the headline for the octave day of the Nativity says it's II class (e.g., [I Vespers](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=12-31-2023&command=prayVesperae&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=), [Lauds](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=01-01-2024&command=prayLaudes&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=), [II Vespers](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=01-01-2024&command=prayVesperae&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=)). The texts seem to be correct, and I Vespers of the octave day is correctly recognized as having higher priority than 31 December, so it seems this is more of a cosmetic issue than a functional one.

**Comment by APMarcello3** [comment]
This error was corrected by 14f5368 and should be in the process of being propagated to the live site.

**Comment by FAJ-Munich** [comment]
> so it seems this is more of a cosmetic issue than a functional one.

The headline is "calculated" in a separate function `setheadline()` of `horascommon.pl` and has no influence on the determination of the text of the office at all. That's why, mostly, when odd rankings appear in the headline, it is a "cosmetic issue"
