### ISSUE TITLE
II Vespers of Epiphany 2024 (DA)

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#3560]
At II Vespers, there is a commemoration of the following feast of the Holy Family and of the Sunday within the octave. Currently those are not displayed.

**Comment by FAJ-Munich** [comment]
Epiphany has always been ranked in the database at "7" which excludes all commemorations and in concurrence at 2nd Vespers all except Duplex I. cl. 
So this and the following issue with the Tridentine version should be silver by lowering the rank in the database to "6.5". 

NB: My desktop is broken so I'm currently not able to edit myself. Just here on GitHub mobile.

**Comment by APMarcello3** [comment]
It is possible to edit on GitHub Mobile (on Android, at least) or, if you could post the change to resolve #3561, I would be happy to copy-paste.

**Comment by FAJ-Munich** [comment]
#3561 should be fixed simultaneously by the same change, I think and hope

**Comment by APMarcello3** [comment]
#3561 was not impacted by the commit closing #3560.
