### ISSUE TITLE
Missa (Divino Afflatu version) is broken

### ISSUE THREAD

**Issue by FAJ-Munich** [DivinumOfficium/divinum-officium#3569]
once clicking on the "Solemn" option, with the latest commits (since Dec 31) the Server goes into an "Internal Server Error"

**Comment by FAJ-Munich** [comment]
Is this really going to be resolved with some undeployed commit?
![image](https://github.com/DivinumOfficium/divinum-officium/assets/60485740/14c5ba9a-dab4-4614-a0b5-921497768f80)

**Comment by APMarcello3** [comment]
Was this not resolved by 6e16182? There has been a serious lag with commits being uploaded to the live site, with @benyanke addressing the situation.

**Comment by FAJ-Munich** [comment]
> Was this not resolved by [6e16182](https://github.com/DivinumOfficium/divinum-officium/commit/6e1618254ffbdcf067172cf5d814462c93610c9d)? 

Now, it works on my localhost; sorry for the confusion. I finally can test locally again and can have a look at #3561 later tonight. I am surprised the rank change for the Epiphany hasn't been enough to get the commemoration of that Sunday back to Vespers.
