### ISSUE TITLE
mobile part of the site is not working

### ISSUE THREAD

**Issue by pizzonia** [DivinumOfficium/divinum-officium#3576]
Hi, it looks that currently the mobile part of the site has some problem.
For example the following link does not show anything.
https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=1-7-2024&version=Rubrics%201960%20-%201960&testmode=regular&lang2=Italiano&votive= 
Thank you
Maurizio

**Comment by APMarcello3** [comment]
We cannot duplicate this error.
