### ISSUE TITLE
Antiphon and Versicle for commemoration at Vespers of St Maurus, Sun Jan 14 2024 (DA)

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#3577]
In the DA rubrics (don't quote me on anything before or after for this one), the same antiphon or versicle cannot be used twice in a divine office. The offices of two confessors are commemorated at this Vespers, the concurring office of St Paul the First Hermit, then in the last place, that of St Maurus whose office is only commemorated.

So we have already used Similabo eum and the versicle Amávit eum. Therefore, the breviary (I'm looking at mine) prescribes Euge from Lauds with the versicle ℣. Os justi meditábur sapiéntiam. ℟. Et lingua ejus loquétur judícium.

I can't think, off of the top of my head, of any other cases on the general calendar… It can get more complicated than this, there's also a rubric for two offices of virgins commemorated at the same office, and for more than two, but those are much rarer.

**Comment by MRoth1910** [comment]
Accessing the site via BrevMeum shows the correct antiphon and versicle, but the main website still yields Sacerdos et pontifex.

**Comment by APMarcello3** [comment]
Sometimes it does take time for the changes to appear on the live site. Be assured the site has been refreshed.
