### ISSUE TITLE
Ordo Praedicatorum - 1962 - wrong offices for First Week After Epiphany

### ISSUE THREAD

**Issue by aklusman** [DivinumOfficium/divinum-officium#3580]
I've noticed the offices (and header) for the Ordo Praedicatorum - 1962 is giving the "Feria <x> infra Hebdomadam I post Epiphaniam ~ IV. classis" (where <x> is II, III, IV, V, VI) for Jan 8-12.  I think it is supposed to be of the particular day (so, January 8th, etc) like in 1960.  

I poked around the code and tried to figure out what is causing the issue, but was unable to solve it.  The "Feria <x> infra Hebdomadam I post Epiphaniam" is the same as in the "Reduced - 1955", for what that is worth.

**Comment by APMarcello3** [comment]
The OP office is very incomplete. We are aware of these limitations and will be working on them.

**Comment by aklusman** [comment]
Can it be slowly improved?  I'm willing to help improve the code (particularly the OP office).  I've been trying to familiarize myself with the workings of the code and backend, but it's been slow-going (as you undoubtedly know).  I'm just not really sure why the OP-1962, which inherits its kalendar from 1960, wouldn't follow 1960 in the choice of dates.  I tried to poke around the code and resolve it, but wasn't able to.

**Comment by APMarcello3** [comment]
We would most welcome your assistance.

**Comment by aklusman** [comment]
@mbab , I notice that the OP1962 Vespers is not "Die Duodecima Januarii ~ IV. classis", but rather "Feria VI infra Hebdomadam I post Epiphaniam ~ IV. classis".  The preceding hours are correct, though.   I tried to figure out the resolution, but I'm still getting familiar with how the code operates.  Figured I'd mention it to you since you fixed it last time...
