### ISSUE TITLE
Vespers of Jan. 13 is wrong

### ISSUE THREAD

**Issue by PaulDang1** [DivinumOfficium/divinum-officium#3601]
It should be 1st Vespers of the Holy Name of Jesus and only one commemoration: the 2nd Sunday after Epiphany. Commemoration of St. Felix is omitted this year. Neither is the Octave-Day commemorated.

**Comment by APMarcello3** [comment]
The 1954 calendar has Holy Name celebrated on 2 January 2024. Is this correct?

**Comment by PaulDang1** [comment]
I forgot to say the Tridentine 1906 rubrics, not Divino Afflatu. Sorry for not clarifying that. 

----- Original Message -----
From: "Albert P. Marcello, III" ***@***.***>
To: DivinumOfficium/divinum-officium ***@***.***>
Cc: PaulDang1 ***@***.***>,  Author ***@***.***>
Date: Sun, 14 Jan 2024 02:24:43 -0800
Subject: Re: [DivinumOfficium/divinum-officium] Vespers of Jan. 13 is wrong (Issue #3601)
