### ISSUE TITLE
Error in generating 1570/1910 epub file

### ISSUE THREAD

**Issue by ProspectorV** [DivinumOfficium/divinum-officium#3605]
Hi, in generated files for rubrics 1570 and 1910 display this message:

Status: 500 Content-type: text/html
Software error:
Can't load tempora for unknown version Trident 1910 at /var/www/standalone/tools/epubgen2/../../../web/cgi-bin/horas/../DivinumOfficium/Directorium.pm line 85.
For help, please send mail to this site's webmaster, giving this error message and the time and date of the error.

**Comment by mbab** [comment]
Fixed with 16d3cdd

Also please check https://mbab1.gitlab.io/divinumofficium.epub/
