### ISSUE TITLE
Martirology erroneous displayed 

### ISSUE THREAD

**Issue by Nokel81** [DivinumOfficium/divinum-officium#3636]
Language 1: English (doesn't happen if set to Latin)
Rubrics: 1960
Day: February 20 2024
Hour: Vespers

**Comment by Nokel81** [comment]
@APMarcello3 why is this not planned? Did I not give enough information? It is clearly a bug in the English format since it does not show up when viewed both Latin and English together

**Comment by APMarcello3** [comment]
We cannot reproduce this error.
