### ISSUE TITLE
1960 "2020 - USA" feasts during Lent

### ISSUE THREAD

**Issue by APMarcello3** [DivinumOfficium/divinum-officium#3659]
According to the decree "Cum Sanctissima", the following feasts may trump the ferial day during Lent under 1960 rubrics: 

MARCH

6          Ss. Perpetua and Felicity, Martyrs
7          St. Thomas Aquinas, Confessor and Doctor of the Church
9          St. Frances of Rome, Widow
12        St. Gregory I, Pope, Confessor and Doctor of the Church
21        St. Benedict, Abbot
24        St. Gabriel the Archangel

APRIL

11        St. Leo I, Pope, Confessor and Doctor of the Church
14        St. Justin Martyr

Provision had previously been made to celebrate these feasts under 1960 rubrics during Lent using the former "Newcal" option (now 2020 - USA), with the "Rubrics 1960" option simply displaying the ferial day. However, at some point during the recent logic changes to commemorations et al., this no longer became possible. It is unclear to me how to even make this a possibility using the conditional rubrics anymore. Help would be appreciated.

**Comment by FAJ-Munich** [comment]
From a quick browsing of some files through the App:

In `dialogcommon.pl`, the "predicate" `innovata` still looks for `NewCal` and needs to look for `2020` or `USA` instead. 

Secondly, the rankings of these feasts have to be raised, conditionally `(rubrica innovata)`, to a rank above `3.9` but below `5`. I'd suggest to give it a try with `3.91`. 

If the file already has a conditional rank `(rubrica 196)` it is trial and error to see if the innovata rank has to come before or afterwards in the `.txt`

Fingers crossed!

**Comment by APMarcello3** [comment]
I have attempted this solution but to no avail.

**Comment by FAJ-Munich** [comment]
It works on my `testchanges` branch. Are we talking about just the Office or the Mass or both?

**Comment by fiapps** [comment]
The office of March 21, 2024 is now showing up as the feast of St. Benedict with 1960 rubrics, so I don-t think the ranks are right yet.

https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=3-21-2024&command=prayLaudes&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=

**Comment by fiapps** [comment]
Looking at a2e8a1e24fddd365e676896ba737d55fc979b15b, the problem is that the `rubrica Rubrics 1960`conditional should not have been eliminated for 03-21 or 03-24, because these are rank 4 generally and need to be lowered to rank 3 with the 1960 rubrics. The others should be OK because they are rank 3 generally and with 1960 rubrics.

**Comment by APMarcello3** [comment]
Also, on such permissible III class feasts during Lent, the 1st benediction is incorrectly displaying as "Evangelica lectio".
