### ISSUE TITLE
Wrong 1st nocturn responsories for non-pontiff doctors in 1954

### ISSUE THREAD

**Issue by xmarteo** [DivinumOfficium/divinum-officium#3666]
Select 3-7-2024 (Thomas Aquinas, confessor, doctor, NOT pontiff), Divino Afflatu 1954, Hodie, Matutinum.

Resp. 2 and 3 are those for a doctor who is also a pontiff. The readings are correct.

I can't make sense of "rubrica innovata" in Sancti/03-07.txt and the redirection game between 03-07 -> C5a -> C5 (which has the correct RR/) or C4a (which does not) etc.

**Comment by APMarcello3** [comment]
What specifically is appearing incorrectly and what should properly appear?

**Comment by xmarteo** [comment]
C4 [Responsory2] (Ecce sacérdos magnus) and C4 [Responsory3] (Jurávit Dóminus) appear, incorrectly.

C5 [Responsory2] (Justus germinábit) and C5 [Responsory3] (Iste cognóvit) should appear instead.

Other C5 responsories (for nocturns 2 and 3) appear correctly.
