### ISSUE TITLE
Leonine Prayers in Trident 1570?

### ISSUE THREAD

**Issue by lemtom** [DivinumOfficium/divinum-officium#367]
When viewing the Sancta Missa according to the Tridentine Calendar of 1570, the Leonine Prayers (_PRAYERS ORDERED BY THE POPE Leo XIII_) are shown. Leo XIII instituted these prayers in 1884.

Since they are absent in 1967 (because of their suppression) and in the “1960 New Calendar”, should it not follow that they ought to be absent in 1570 as well?

**Comment by gregordick** [comment]
> Since they are absent in 1967 (because of their suppression) and in the “1960 New Calendar”, should it not follow that they ought to be absent in 1570 as well?

This sounds sensible.  Do you want to look into writing a patch?  I haven't looked at the code, but it's probably a small change, given that we already handle the omission for 1967.  It might even be handled in the office template and so not require any code changes.

**Comment by lemtom** [comment]
I have been looking through the code and the templates, but I fear their workings are too complicated for me.

**Comment by gregordick** [comment]
No problem.  It will be addressed at some point in the future.  Thanks for noticing it and raising the bug!
