### ISSUE TITLE
English translation missing on Feria quinta in coena Domini

### ISSUE THREAD

**Issue by QuoPrimum24** [DivinumOfficium/divinum-officium#3698]
For the Propers of the day listed above, where it should have been translated into the vernacular (English, in my case), there is Latin on both sides--images are attached.

[Chrism Mass propers error.pdf](https://github.com/DivinumOfficium/divinum-officium/files/14791067/Chrism.Mass.propers.error.pdf)

[Holy Thursday propers error.pdf](https://github.com/DivinumOfficium/divinum-officium/files/14791038/Holy.Thursday.propers.error.pdf)

If needed, I can post another file that has the necessary translations.

**Comment by APMarcello3** [comment]
Kindly email the text to canon.missae@gmail.com
