### ISSUE TITLE
Wrong doxology for the office of Prime in Eastertide (Rubrics 1960 - 1960)?

### ISSUE THREAD

**Issue by youakrim** [DivinumOfficium/divinum-officium#3711]
In the 1961 Liber Usualis, p. 808 (https://gregobase.selapa.net/sources/3/993.png), it says the doxology of the Prime hymn in Eastertide is the same as Tierce (e.g _Præsta pater piissime_). However on the DO website it uses the regular doxology for Prime (e.g. _Deo Patri sit glória_). Am I missing something?

**Comment by APMarcello3** [comment]
This may be a misprint in the Liber. Many 1961 Libers were printed with obsolete rubrics. The site follows the Breviarium Romanum. Cf. 1960 Rubrics 188. "Each hymn is always said with the conclusion assigned it in the Breviary. There is no change of ending by reason of a feast or a season."
