### ISSUE TITLE
Last Gospel of St Justin for Divno Afflatu — source?

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#3712]
On April 14, when this falls on a Sunday, DO gives a proper Last Gospel for the feast of St Justin. What is the source for this? St Lawrence Press doesn't give a proper Last Gospel, nor does the Polish Benedicamus Domino ordo. Stercky doesn't list it in the list of gospels that, by their nature (e.g. St Mary Magdalene or St Martha) or by decree (double major feasts or lower of the BVM, the Holy Angels) are considered "truly proper" for the purposes of reading the text on a Sunday where the feast is commemorated.

It does appear to me that the text is proper to the day (unless I'm mistaken), but this is the sort of thing which I would have thought that, above all, Stercky would catch. Is there perhaps a decree of the SCR of which we're (I am) simply ignorant?

**Comment by MRoth1910** [comment]
Again on 4/28, the Last Gospel is "proper" but I see no evidence for this in the St Lawrence Press Ordo; Restore the 54 also has a proper last Gospel for 4/21 (clearly wrong; St Anselm's Mass is taken entirely from the common). And this text is also said on the feast of St Titus, so it appears elsewhere and is not one of those listed in Stercky as an exception.

The Polish Benedicamus Domino ordo does not have a proper Last Gospel on 4/21 and on 4/28; I believe that this is correct.

**Comment by APMarcello3** [comment]
Could you kindly provide us with this list from Stercky?

**Comment by MRoth1910** [comment]
Sure. P. [498](https://archive.org/details/ManuelDeLiturgieSterckyTomeI/page/n254/mode/1up?view=theater). (My translation, but all emphases Stercky's.)

"When one must not say, at the end of the Mass, the gospel of a Sunday, of a major feria, of a vigil, or of one of the octaves enumerated above*, one says as the Last Gospel, the Gospel of the _first_  of the commemorated offices having a Gospel _strictly_ proper.

1) Have a gospel which is strictly proper: All the Masses of mysteries and of feasts : a) of Our Lord, except the Mass of the Dedication of a church with the Gospel _Ingressus Jesus_; b) of the Blessed Virgin, except the Mass of the Assumption with the Gospel _Intravit Jesus in quoddam castellum_; c of the Holy Archangels and Guardian Angels; d) of Saint John the Baptist; e) of Saint Joseph, spouse of the BVM; et of the 12 Apostles.

2º the Masses of the Holy Innocents, of Saint Mary Magdalene, Penitent; of Saint Martha, virgin; of the Commemoration of all holy Popes [NB this predates the **Common** of Popes, so I don't know exactly what he means]; and all votive Masses listed in the _Missale Romanum_ under the (I), but not those mentioned under (2) ad visersa and which begin with the Mass _pro eligendo Summo Pontifice._ [I truly don't think that we'll ever need to consider this.]**

3º the Masses of the day within the octave and of the octave day of the feast of SS Peter and Paul; this Gospel of the day within the octave must be recited as the Last Gospel the _first_ day where one commemorates the octave, even if one says the Mass and Office of the octave on the following days.

2) The Gospels of the feasts of Saint Marc, of Saint Luke, and of Saint Stephen, nor that of the Conversion or the Commemoration of Saint Paul are not strictly proper. 

2. One does not say as the Last Gospel a gospel which is only _appropriated_, nor one borrowed from a _Common,_ nor the gospel of a day within the octave when this is the gospel of the feast.

*at all Masses, even votive, where one commemorates a Sunday, even anticipated or transferred with its office; of a feria of Lent or the Ember Days; of Rogation Monday; of a day within a privileged octave of the I class… on the condition however that this is not the gospel of the Mass or its beginning… (the rest of this note is my elision): one says the Last Gospel of the office commemorated first (i.e. of a feria with a proper gospel and a vigil or of two vigils) or, if this is the same as that of the Mass, then the second is read as the Last Gospel; this is omitted at either conventual Mass if there are two conventual Masses. The Last Gospel is of Saint John on the vigil of Christmas coinciding with the IV Sunday of Advent; on feasts falling the 2nd, the 3rd, or 4th of January when those are a Sunday; at Mass where one commemorates the previous Sunday impeded and moved without the office to the first free day of the week…

**the Masses of the Trinity, of the Angels, of Saint Joseph, of SS Peter and Paul, of the Apostles, of the Holy Ghost, of the Blessed Sacrament, of the Holy Cross, and of the Passion.

**Comment by APMarcello3** [comment]
@FAJ-Munich

**Comment by FAJ-Munich** [comment]
I am definately not an expert for the **Sancta Missa** parts of the code and database as I haven't looked at it properly ever before.
Nonetheless, lines 1167 – 1185 of `propers.pl` contain
```
sub Ultimaev : ScriptFunc {
  my $lang = shift;
  my ($t, %p);

  if ($version =~ /(1955|196)/ || !exists($commemoratio{Evangelium})) {
    our %prayers;
    $t = $prayers{$lang}->{'Ultima Evangelium'};
  } else {
    %p = (columnsel($lang)) ? %commemoratio : %commemoratio2;
    $t = $p{Evangelium};
  }

  if ($t && $t !~ /^\s*$/) {
    $t =~ s/\((.*?)\)/setfont($smallfont, $1)/eg;
    $t =~ s/\n/\n\$Gloria tibi\n/;
    $t = "$t\$Deo gratias";
  }
  return $t;
}
```
Since it only checks `!exists($commemoratio{Evangelium}`, any database file, which contains the `[Evangelium]` hash element directly, is going to lead to a proper last gospel to be displayed. Implementing a proper logic for the above – not just a quick and dirty solution – first one should compare the various rubrics in the Missale pre- and post Divino Afflatu (probably editio typica 1920 should do for the latter; does one know a pdf version of a former one?).

**Comment by APMarcello3** [comment]
https://archive.org/details/missale-romanum-1862/

**Comment by MRoth1910** [comment]
So, I think I have the answer. Paul Cavendish asked if I'd dug up anything. He found a 1929 ordo which agrees with his for this year, and the Polish Benedicamus Domino: the Last Gospel is that of Saint John in these cases.

> I didn't really understand it, after having done some research and thinking about it. Matthew Hazell's table of readings yields one result for the pericope in question; the entries are from the 1962 missal, so it's imperfect, but I think that it's correct to say that this is a gospel text read only once. But doing a search just for Lk. 12 revealed the answer.
> 
> The Polish folks at Benedicamus Domino agree with you and the 1929 ordo, as they don't have proper Last Gospels for any of these three Sundays. I double-checked Stercky, who gives the list of those feasts (e.g. St Mary Magdalene and St Martha, the common of the BVM, etc.) where the pericope is truly proper or is considered so as a legal fiction for the sake of honoring the feasts, as we had last September 24 with Our Lady of Mercy. The various clerics who oversaw these things over the years must therefore have considered that, even with one verse lopped off, the text appointed for St Justin to be the same as the text of the common which begins at v. 1 of the same chapter and ends with v. 8, at the same place, read in Mass no. III of several martyrs outside of Paschal Time.
> 
> I do have a possible explanation for the systematic nature of the error by the well-meaning folks at Restore the 54: someone read the rubric for the commemoration of the Lenten feria and misinterpreted it, because all three Sundays (April 14, 21, and 28) which I checked have a proper Last Gospel, which can't be right, as the Mass of Saint Anselm is entirely from the common. Divinum Officium had a proper Last Gospel on the 14th and 28th; the second is wrong, based on my understanding, because the text from Luke 10, "Designavit Dominus", is also read on the feast of Saint Titus.

Now getting that to work for April 14 when it falls on a Sunday of Paschal Tide is trickier…

**Comment by mbab** [comment]
will this work?

add something like `noEvengeliumProper` to `Rule` section in all Commune files and those in Saint which required
and add guard as
```
if ($version =~ /(1955|196)/ || !exists($commemoratio{Evangelium}) || $commemoratio{Rule} =~ /noEvengeliumProper/.) {
```

**Comment by APMarcello3** [comment]
Would it perhaps be better to include a line of logic such as properUE which would refer to the transfer table, and a list of days in that year with proper last gospels (due to whatever reason) could be provided therein?

**Comment by FAJ-Munich** [comment]
I'm a little bit puzzled about the rubrics on this now. 
In the 2005 reprint of the Missale 1920, I read in rubric XIII, § 2:

> Deinde legitur Evangelium S. Joannis **In princípio,** præmisso **Dóminus vobíscum**, et **Inítium**, ut moris est: quod Evangelium numquam prætermittitur in Missa, nisi quando fit de Festo in aliqua Dominica, vel Feria, quæ habet Evangelium proprium, quod legitur ejus loco.

Doesn't that mean that (pre-Divino) only "when Feasts occur on any Sunday or a Feria, which has a proper Gospel (i.e., Lent and Q.T.), then the latter is read in place of S. Joannis"? _But Sanctoral Feasts do not get any Last Gospel?_

Only with _Additiones et Variationes in Rubricis Missalis_, rubric IX, § 3, this is introduced by

> Denique, si nullum Dominicæ, Feriæ, Vigiliæ, aut alicujus ex Octavis supra, num. 1, recensitis, Evangelium in fine Missæ fuerit legendum, dicitur ultimum pariter Evangelium Missæ sive Officii primo loco inter cetera, quæ Evangelium stricte proprium (et non appropriatum, vel ex aliquo Communi assignatum, vel per Octavam e Festo repetitum) habeant, commemorati.

So the solution has to distinguish between pre- and post-DA? 
Either way, whenever the Gospel is from a Commune, the current code should be smart enough already. The issue arises when the Gospel is not from the Commune, yet also assigned to a different feast, like in the case of St. Titus and S. Pauli a Cruce sharing the same Gospel, isn't it?

Regarding @mbab 's solution, I guess one has to see which way around, there are less exceptions to be coded in the rules. With a `Evangelium appropriatum` rule or with a `Evangelium stricte proprium` rule
