### ISSUE TITLE
Prime for Easter Sunday missing Alleluias (3×)

### ISSUE THREAD

**Issue by Geremia** [DivinumOfficium/divinum-officium#3718]
Prime for Easter Sunday simply has the following, with only one "Allelúia":

> [Incipit](https://www.divinumofficium.com/cgi-bin/horas/officium.pl?date=4-1-2024&command=prayPrima#Prima2)
> ℣. Deus ✠ in adiutórium meum inténde.
> ℟. Dómine, ad adiuvándum me festína.
> Glória Patri, et Fílio, * et Spirítui Sancto.
> Sicut erat in princípio, et nunc, et semper, * et in sǽcula sæculórum. Amen.
> Allelúia.

Shouldn't it be: "Allelúia, allelúia, allelúia"?

Also, a concluding "Allelúia, allelúia, allelúia" is missing after [the 3<sup>rd</sup> psalm](https://isidore.co/divinum/cgi-bin/horas/officium.pl#Prima6), right before the "[Versus (In loco Capituli)](https://www.divinumofficium.com/cgi-bin/horas/officium.pl?date=4-1-2024&command=prayPrima#Prima7)" section.

**Comment by APMarcello3** [comment]
The psalms of Prime on Easter are said without the threefold Alleluia. This is the case both antecedent and subsequent to the 1955 changes.![20240420_063135.jpg](https://github.com/DivinumOfficium/divinum-officium/assets/11463422/8e0fec0b-6edc-427b-8edd-e63ded9f5caf)
