### ISSUE TITLE
C7a Responsory Sexta is in Latin when English is requested

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3734]
For some reason, the English translation of Responsory Sexta for C7a is not being found, so Latin is substituted. Perhaps this has to do with the recent simplification of commons for Eastertide. Here is a case that is failing:

https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=5-4-2024&command=praySexta&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=

I looked into it a little, but I don't understand the problem. C7a gets the responsory from C7, which in turn gets it from C6. This works for the responsories at Terce and None, but not at Sext.

**Comment by APMarcello3** [comment]
The capitalization of "Deus" in Latin was being clobbered by the code, which automatically adds the "Alleluia" for the Paschaltide texts. d32db27, which had not been propagated to the modern languages, remedies this.

https://github.com/DivinumOfficium/divinum-officium/commit/666990fc01464e713fb544eb4bd603f3b522b3cd
