### ISSUE TITLE
More extra line breaks

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3760]
Here are some more unnecessary line breaks I found recent changes have added. 

- Extra line break at the end of the table cell containing Capitulum Responsorium Versus: There are two `<br>` after the verse at [Terce](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=8-13-2024&command=prayTertia&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=), [Sext](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=8-13-2024&command=praySexta&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=), and [None](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=8-13-2024&command=prayNona&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=) of 8-13-2024. This is unnecessary but doesn't look bad.
- Extra line break after Hymnus in [Vespers of the Immaculate Conception](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=8-15-2024&command=prayVesperae&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=): there are two line breaks after Hymnus in the Latin column, but only one after Hymn in the English column. 9-8-2024, which has the same hymn, has the same issue. This case looks bad because the Latin has a line break the English does not.

**Comment by APMarcello3** [comment]
@mbab
