### ISSUE TITLE
Collect of Trinity 5-25-2024 (DA and possibly other versions)

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#3797]
The collect at Vespers is not given correctly. DO gives that of the 1st Sunday after Pentecost, which is repeated below. They are both correct on Sunday evening 5-26.

Also, the translation for the Trinity collect needs "thou hast" where it has "you have" as it switches back to the usual thou/thee/thy pronouns halfway through.

**Comment by APMarcello3** [comment]
@FAJ-Munich

**Comment by FAJ-Munich** [comment]
I've found the culprit and why it happens only on Saturday.
