### ISSUE TITLE
Emissa.pl doesn't handle `nofancychars`.

### ISSUE THREAD

**Issue by Geremia** [DivinumOfficium/divinum-officium#3802]
[`epubgen2.sh`:313](https://github.com/DivinumOfficium/divinum-officium/blob/master/standalone/tools/epubgen2/epubgen2.sh#L313) passes `nofancychars=$NOFANCYCHARS` to the `$EMISSACMD`, but [`Emissa.pl`](https://github.com/DivinumOfficium/divinum-officium/blob/master/web/cgi-bin/missa/Emissa.pl) doesn't do anything with it.

**Comment by APMarcello3** [comment]
@mbab

**Comment by mbab** [comment]
missa part doesn't support nofancychars option at all
