### ISSUE TITLE
Vigil of St John the Baptist 2024 (DA)  & other anticipated vigils which are not just commemorated 

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#3814]
The vigil, anticipated on Saturday, is commemorated correctly at Lauds, but neither the proper IX lesson nor the Mass commemoration (with a proper Last Gospel) are shown.

**Comment by FAJ-Munich** [comment]
additonally to be checked:  

- 07-24 in 2022
- 08-13 in 2022
- 10-27 in 2024
- 10-31 in 2027
- 11-29 in 2028

**Comment by APMarcello3** [comment]
07-24-2022: no proper Ult Evang; no proper 9th lect.
08-13-2022: no proper Ult Evang
10-27-2024: OK
10-31-2027: OK
11-29-2028: no proper Ult Evang; no proper 9th lect.

**Comment by APMarcello3** [comment]
@FAJ-Munich bump

**Comment by FAJ-Munich** [comment]
> 07-24-2022: no proper Ult Evang; no proper 9th lect. 

I've added the 9th lectio from C1v according to 1942 book; is the Evang from the Commune also considered proper to be added ad missam?

> 08-13-2022: no proper Ult Evang 

just saw there is a double commemoration of S. Hippolit to be fixed in Tridentine; 
The vigil is said at Mass (DA) version so no need to change anything here?

> 10-27-2024: OK 
> 10-31-2027: OK 

> 11-29-2028: no proper Ult Evang; no proper 9th lect.

may fault: the anticipation is in 2020; nonetheless, there seems to be an issue with the number of collects at Mass in 2028 as there are 4 of them? is that correct?

**Comment by APMarcello3** [comment]
@MRoth1910

**Comment by FAJ-Munich** [comment]
For Missa, the $transfervigil logic is not implemented yet. Have drafted it for Vigil of Assumption in Trid version now. Hope to finish it by tomorrow.

**Comment by MRoth1910** [comment]
St Lawrence Press gives the last gospel of the vigil for 7/23/2022.

For 8/13/2022, Restore the 54 and St Lawrence give the 2nd collect of Ss Hippolytus and Cassian, 3rd of the Holy Ghost. St Eusebius is accidentally transferred on DO with the entire vigil.

For 11/29/2028: there is a rubric explaining how to handle all variations. On weekdays outside of Advent, 2nd oration of St Saturinus, 3rd of the BVM. In Advent, commemoration of the Advent feria, then St Saturinus. If it's a Saturday where the vigil is anticipated (I believe that this has to be outside of Advent because of what follows): omit St Saturinus; 2nd collect of the BVM Concede, 3rd Ecclesiae or pro Papa.

So the 2020 version was not correct as it has A cunctis and Concede.

**Comment by FAJ-Munich** [comment]
> In Advent, commemoration of the Advent feria, then St Saturinus. 

This is harder to achieve and requires some tinkering with the ranking of the vigil. For in the Office, it is of the Feria with Commemoration of the Vigil ad Missam tantum. Restore54 confirms, mass of the Vigil just how DO has the Vigil Mass of S. Thomas though.
