### ISSUE TITLE
Martyrology problems (with 1960 rubrics)

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3826]
On [November 2](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=11-2-2024&command=prayPrima&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=), the martyrology title has disappeared, and the following have been added (I don't have a martyrology handy to verify that they should be omitted, but they were up to now with the 1960 rubrics):
> ℣. Pretiósa in conspéctu Dómini.
> ℟. Mors Sanctórum eius.
> Sancta María et omnes Sancti intercédant pro nobis ad Dóminum, ut nos mereámur ab eo adiuvári et salvári, qui vivit et regnat in sǽcula sæculórum.
> ℟. Amen.

During the Triduum (e.g., [Holy Thursday](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=3-28-2024&command=prayPrima&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=)), the marytrology should not be read, at least not with the 1960 rubrics, but it is being read.

**Comment by APMarcello3** [comment]
@FAJ-Munich

**Comment by FAJ-Munich** [comment]
> On [November 2](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=11-2-2024&command=prayPrima&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=), the martyrology title has disappeared, and the following have been added (I don't have a martyrology handy to verify that they should be omitted, but they were up to now with the 1960 rubrics):
> 
> > ℣. Pretiósa in conspéctu Dómini.
> > ℟. Mors Sanctórum eius.
> > Sancta María et omnes Sancti intercédant pro nobis ad Dóminum, ut nos mereámur ab eo adiuvári et salvári, qui vivit et regnat in sǽcula sæculórum.
> > ℟. Amen.

I checked Breviarum 1942 and the reprint of the Martyrology on [introibo](https://introibo.net/download/brevier/martyrologium_latein.pdf). In my opinion, the rubric is slightly vague 

> Deinde in Choro legitur Martyrologium, ut ibi suo loco notatur. Deinde etiam extra Chorum, ..., subjungitur : V. In memória ...

However, from the structure of the prayer and Versicle, logically it replaces "Pretiosa" & "Sancta Maria ...". So I change it back to how it used to be on DO.

> During the Triduum (e.g., [Holy Thursday](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=3-28-2024&command=prayPrima&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=)), the marytrology should not be read, at least not with the 1960 rubrics, but it is being read.

Indeed, should always be omitted. Apparently, I checked Monastic only which does still omit it.
