### ISSUE TITLE
The Capitular Office appears at Prime with the 1960 rubrics

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3827]
The Capitular Office has been added at Prime on every day (see [today](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=6-5-2024&command=prayPrima&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=), for example), even though it is not part of Prime with the 1960 rubrics. I suspect this bug was introduced by @FAJ-Munich's PR #3820 \[Single Ordinarium for all versions / languages (Prima)\].

**Comment by APMarcello3** [comment]
The heading "De Officio Capituli" does appear in the 1961 edition. ![Screenshot_20240605-122430_OfficeSuite.jpg](https://github.com/DivinumOfficium/divinum-officium/assets/11463422/57f76a96-2b3d-46ee-93df-cbe5b66da471)

**Comment by fiapps** [comment]
I apologize for the erroneous report. I saw a lot of changed lines and thought much more was going on here than just the addition of a section division.
