### ISSUE TITLE
Oremus should not precede orations in the office of Holy Saturday (1960 rubrics)

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3836]
"Domini exaudi…" and "Oremus" are appearing in the hours of Holy Saturday with the 1960 rubrics (e.g., [Laudes](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=3-30-2024&command=prayLaudes&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=), [Terce](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=3-30-2024&command=prayTertia&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=). The rubrics in the breviary say the oration should immediately follow the silent Pater, without Oremus.

I imagine this has to do with the fact that before 1955, the Easter Vigil was celebrated in the morning.

**Comment by APMarcello3** [comment]
Closed by [0ddea46](https://github.com/DivinumOfficium/divinum-officium/commit/0ddea46e796f28e1a45bfefd17ee337822466b2a)
