### ISSUE TITLE
02-01-2025 1960 rubrics

### ISSUE THREAD

**Issue by APMarcello3** [DivinumOfficium/divinum-officium#3858]
@FAJ-Munich There should be no commemoration of St. Ignatius at 1st Vespers of Purificatio BMV.

Also the following requires implementation for 02-02 at least for 1960 rubrics: "Quando hoc festum occurrit in dominicis in Septuagesima, aut Sexagesima, aut Quinquagesima, ad Horas sumuntur antiphonae de Laudibus, psalmi vero de dominica, retentis tamen ad Primam psalmis 117, 118i, 118ii."

This would apply for the years 1964 & 2048.

**Comment by APMarcello3** [comment]
1735c9c745 removes the needless commemoration of 02-01 S. Ignatii at 1st Vespers of Purificatio BMV; however, the headline title must be removed. This commit also ensures (by entry into the dominical letter E transfer table) that 02-02 trumps the Gesima Sundays and does not commemorate them; however, for these years the antiphons are not yet appearing at the minor hours as should be the case.

**Comment by FAJ-Munich** [comment]
am almost finished with it

**Comment by APMarcello3** [comment]
@FAJ-Munich Still not working; see Ordo and Officium for 02-02-2025.

**Comment by FAJ-Munich** [comment]
has been affected by #3874 ... * mea culpa *
