### ISSUE TITLE
Oratio imperata on World Mission Sunday (DA)

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#3899]
The orations from the votive Mass from the propagation of the faith are also said under the DA rubrics, even when a double feast is commemorated such that ordinarily there would be no third oration (and if there were three, the priest does not to add a third oratio; he can choose the oratio imperata as the prayer ad libitum, or he may say both).

Anyway, currently only the commemoration ordinarily made is listed for Oct 20, 2024.

**Comment by APMarcello3** [comment]
@mbab

**Comment by APMarcello3** [comment]
24ea0a1d60

**Comment by MRoth1910** [comment]
![image](https://github.com/user-attachments/assets/fd5ad370-47c3-4c46-b0dd-7a0ab7d1492a)

The prayer pro propaganda fidei is said in the 3rd place, but the website puts it 2nd. Confirmed checking against the St Lawrence Press Ordo. Restore the '54 left it out entirely; oops.

**Comment by APMarcello3** [comment]
@mbab and/or @FAJ-Munich
