### ISSUE TITLE
Two commemoration errors (rubrica 1960)

### ISSUE THREAD

**Issue by APMarcello3** [DivinumOfficium/divinum-officium#3907]
@FAJ-Munich 

1) 06-28-2019:  For this instance, the commemoratio de sequenti is not of a Sunday.

2) 06-29-2024: Debet esse commemoratio Dominicae VI post Pentecosten,  ad Vesperas. Cf. Tabula Concurrentiae.

**Comment by FAJ-Munich** [comment]
@APMarcello3  the publishing of the docker image failed but I don't undertand why. The code changes are so tiny and work locally.

**Comment by APMarcello3** [comment]
@benyanke Any ideas?

**Comment by FAJ-Munich** [comment]
I triggered a re-run of the workflow in actions and now it passed. Still strange behaviour.
