### ISSUE TITLE
Wrong responsories on Simple Feast Matins?

### ISSUE THREAD

**Issue by Aurelianus24** [DivinumOfficium/divinum-officium#3932]
In the Tridentine breviary, the responsories on simple feasts are taken from the common (see below). On the website they are taken from the lectio continua, as in the ‘60. 

In Officio autem trium Lectionum, quando fit de Festo, et in Feriis Temporis
Paschalis, quod est inter Dominicam in Albis et Ascensionem (excepta Feria
secunda Rogationum, in qua ponitur tertium Responsorium), dicuntur duo
Responsoria, quia post tertiam Lectionem dicitur Te Deum Que Responsoria in
Festis sumuntur de Communi Sanctorum, et in dictis Feriis Temporis Paschalis,
quando alia propria non assignantur, sumuntur de Dominica in qua primo sunt
posita, hoc ordine : secunda et quinta Feria, primum et secundum Responsorium
primi Nocturni: Feria tertia et sexta, primum et secundum Responsorium secundi
Nocturni: Feria quarta primum et secundum Responsorium tertii Nocturni.

**Comment by APMarcello3** [comment]
@mbab
