### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by daviduhden** [DivinumOfficium/divinum-officium#3935]
When I try to access the "Missale" and "Ordo" sections I get the following errors:

![missa](https://github.com/DivinumOfficium/divinum-officium/assets/149145202/7436621e-3e76-45d0-993b-8dc578ddb31e)
![kalendar](https://github.com/DivinumOfficium/divinum-officium/assets/149145202/de812ee3-4d0a-4b3f-9cce-c76d23fa3f99)

**Comment by APMarcello3** [comment]
@FAJ-Munich
