### ISSUE TITLE
Error in epubgen2

### ISSUE THREAD

**Issue by rl1234567890** [DivinumOfficium/divinum-officium#3937]
When I run
./epubgen2.sh

I get 

[Sun Jul  7 14:48:58 2024] EofficiumXhtml.pl: Can't load tempora for unknown version Rubrics 1960 at /usr/local/divinum-officium-read-only/standalone/tools/epubgen2/../../../web/cgi-bin/horas/../DivinumOfficium/Directorium.pm line 88.

Any idea?

**Comment by FAJ-Munich** [comment]
Yesterday, I have renamed the Missa version names to match the Horas versions. It's now called `Rubrics 1960 - 1960`

**Comment by FAJ-Munich** [comment]
I've just seen the commit has been reverted so now the roubgen should work again using the old version name.

**Comment by rl1234567890** [comment]
It works for me, thanks! The issue can be closed, as far as I am concerned.
