### ISSUE TITLE
Mass 1955 01-05-2024 missing but files are there

### ISSUE THREAD

**Issue by d4h0y0sr** [DivinumOfficium/divinum-officium#3942]
Hi, the mass of 01-05-2024 for Reduced 1955 the proper is not displaying it says "Introitus is missing", but i can see the file 01-05.txt and 01-05r.txt there with the information. I dont know what could be the reason because in Rubrics 1960 it works fine.

Thanks.

**Comment by FAJ-Munich** [comment]
Works fine for me on the offical website and my local copy.

**Comment by FAJ-Munich** [comment]
Well. Actually it's an issue for all of 2nd January through 5th January due to the abolishment of the octaves and the vigil.
Are the 1960 masses "die xx januarii" already applicable in the 1955 version? Don't know that?
