### ISSUE TITLE
Possible issue: Mass 10-25displaying wrong lectures

### ISSUE THREAD

**Issue by d4h0y0sr** [DivinumOfficium/divinum-officium#3945]
So, For the mass of october 25  file is 10-25.txt which have the correct information, nevertheless in 1955 and 1960 website is displaying totally different lectures (lecture and evangelium)

**Comment by APMarcello3** [comment]
Under 1955 & 1960 rubrics the Mass to be said can be the feria or the commemorated saint. The website defaults to the ferial Mass for these rubrical structures.
