### ISSUE TITLE
Issues with Polish Translation and Translation Gaps "Ad Completorium" and "Ad Matutinum"

### ISSUE THREAD

**Issue by pietrushnic** [DivinumOfficium/divinum-officium#3954]
Essentially, my problem is that when using Rubrics 1960 - 1960, I encounter some "weird" but maybe correct words in Polish translation (e.g., in Ad Completorium 7-17-2024, "boć", "djabeł"; some seem to be the result of automatic translation), so I would like to verify things with the sources. I'm willing to obtain those resources (buy books) or analyze things available publicly myself if that helps.

Other problem types occur in Ad Matutinum 07-18-2024, where Lectio 3 has only an English version. From what I see in Ad Matutinum, fragments are often not translated. Does it make sense to improve that? What is the reason for the lack of translation? How can I help fix that?

**Comment by APMarcello3** [comment]
@mbab

**Comment by pietrushnic** [comment]
Is the lack of Polish translation in some Lectio of "Ad Matutinum" a valid issue, or do you consider it a non-issue because the translation is incomplete?

Examples:

### Rubrics 1960 - 1960 Ad Matutinum 07-15-2024

1.  After Lectio 1, English instead of Polish:
```
℟. Remember, O Lord, thy covenant, and say unto the destroying Angel: Stay now thine hand;
* That the land be not utterly laid waste, and that thou destroy not every living soul.
℣. Even I it is that have sinned, and done evil indeed; but these sheep, what have they done? Let thine anger, I pray thee, O Lord, be turned away from thy people.
℟. That the land be not utterly laid waste, and that Thou destroy not every living soul.
```

2. After Lectio 2, English instead of Polish:
```
℟. Hearken, O Lord, unto the cry and to the prayer which thy servant prayeth before thee today, that thine eyes may be open and thine ears attend;
* Toward this house day and night.
℣. Look down from thine high and holy place, O Lord, even from heaven thy dwelling.
℟. Toward this house, day and night.
℣. Chwała Ojcu i Synowi, * i Duchowi Świętemu.
℟. Toward this house, day and night.
```

3. Lectio 3 not translated

### Rubrics 1960 - 1960 Ad Matutinum 07-16-2024

1.  After Lectio 1, English instead of Polish:

```
℟. Lord, when thy people shall turn again to thee, and shall pray unto thee in this house;
* Then hear Thou in heaven, O Lord, and deliver them out of the hand of their enemies.
℣. If thy people sin against thee, and turn again, and repent, and come and pray unto thee in this house.
℟. Then hear Thou in heaven, O Lord, and deliver them out of the hand of their enemies.
```

2.  After Lectio 2, English instead of Polish:

```
℟. And it came to pass when the Lord would take up Elijah into heaven by a whirlwind
* Elisha cried, and said: My father, my father, the chariot of Israel, and the horsemen thereof.
℣. And as they still went on, and talked, behold, there appeared a chariot of fire, and horses of fire, and parted them both asunder, and Elijah went up by a whirlwind into heaven.
℟. Elisha cried, and said: My father, my father, the chariot of Israel, and the horsemen thereof.
```

Does such a report make sense to you? If I can do it better, please give me an example.

Yesterday, I found this: https://www.divinumofficium.com/www/horas/Help/credits.html, which explains what books are used for translation and what could be added to contribution documentation. Quite a lot of them are publicly available. Explaining how to use those to correct a given section could lead to a well-informed community and more contribution if that is needed. Still, there may be better uses of your time if the community is small. I need that guidance to determine which book is correct for which section of Breviary and decide if a given Polish word is an anachronism or a translation issue. Without guidance, I will have to spend time on that, slowing down my contribution.

**Comment by APMarcello3** [comment]
@pietrushnic The project is well underway; therefore it is superfluous to open a separate issue. @mbab can provide details on submission of Polish texts.

**Comment by pietrushnic** [comment]
> @pietrushnic The project is well underway; therefore it is superfluous to open a separate issue.

Understood.

> @mbab can provide details on submission of Polish texts.

I'm looking for that.

**Comment by mbab** [comment]
@pietrushnic To co się wyświetla po angielsku,  nie jest jeszcze przetłumaczone - bo nie udało się znaleźć tłumaczeń w domenie publicznej. Archaizmy językowe i staropolska pisownia, pochodzą ze źródeł i wg mnie tak powinno zostać.

**Comment by pietrushnic** [comment]
> @pietrushnic To co się wyświetla po angielsku, nie jest jeszcze przetłumaczone - bo nie udało się znaleźć tłumaczeń w domenie publicznej.

Jest jakiś plan jak do tego podejść? Uważam, że posiadanie tekstu łacińskiego i polskiego w dwóch kolumnach obok siebie jest bardzo pomocne i powoduje, że divinum-officium oferuje unikalną wartość której nie daje  żadne inna pozycja, choć moja wiedza jest tu ograniczona i może równie dobre źródła istnieją.

> Archaizmy językowe i staropolska pisownia, pochodzą ze źródeł i wg mnie tak powinno zostać.

Zdecydowanie się zgadzam, ale czasami mam wątpliwości czy mam do czynienia z archaizmem czy błedem automatycznego tłumaczenia (jeżeli takowe gdziekolwiek było używane, bo może mi się tylko wydaje). Jak znajdę konkret to podeślę, aby wytłumaczyć o co mi chodzi. 

Odnośnie źródeł to co jest dla mnie ważne to źródła dla Matutinum i Completorium, abym mógł nie zadawać zbędnych pytań tylko sprawdzić samemu, a jeżeli coś do poprawy bym znalazł to albo zrobił kontrybucję samemu, albo podesłał erratę z odpowiednimi odnośnikami.

**Comment by mbab** [comment]
Źródła o ile istnieją, są podane w credits, nie które tłumaczenia są autorskie.
Jeśli chodzi o rubryki 1960, to w Matutinum nie są przetłumaczone tylko lekcje o świętych i niektóre responsoria.

**Comment by pietrushnic** [comment]
Sporo pozycji jest wymienionych w credits i niestety nie potrafię ich bezpośrednio połączyć z zawartością Matutinum i Completorium. Wydaje mi się, że chodzić może o:

```
Breviary hymns, except for Te Deum, come from books: Hymny brewjarza rzymskiego oraz patronału polskiego : przekład i objaśnienia, written by Bronisław Gładysz, and Mszał Rzymski z dodaniem Nabożeństw Nieszpornych prepared O. G. Lefebvre, polish translation corrections x. dr Stefan Świetlicki i x. Henryk Nowacki. 
```

Pierwszy wydaje się być [tutaj](https://polona.pl/item-view/0bd2e199-660c-442a-af17-dc27947103f7?page=6), może warto zlinkować?

Drugi chyba można zakupić [tutaj](https://www.ceneo.pl/147836031), chociaż widać, że jest to trudno dostępna pozycja. [Tu](https://3dom.pro/18903-mszal-rzymski-z-dodaniem-nabozenstw-nieszpornych-1949-r-o-g-lefebvre.html) jest plan sprzedaży wznowionej edycji.
