### ISSUE TITLE
Divino afflatu should not have a commemoration in Sunday Matins

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3991]
A correspondent reports:

> I’ve noticed the last several weeks (or months) that the app has been replacing the 9th lesson at Matins with the shorter reading of the Saint(s).  This is not done according to the DA rubrics on Sunday. They are only commemorated at Lauds and Mass.

Looking at [last Sunday's Matins](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=8-11-2024&command=prayMatutinum&version=Divino%20Afflatu%20-%201954&testmode=regular&lang2=English&votive=) on the website, I see that there is indeed a commemoration as the ninth lesson. I am not familiar with the DA rubrics, so I leave it to your judgment to decide whether or not this is a bug that needs to be corrected.

**Comment by APMarcello3** [comment]
@FAJ-Munich

**Comment by FAJ-Munich** [comment]
Indeed, no. 5 of Title IV of Additiones & Variationes says:

> 5. Porro, si in Dominicis majoribus que sub ritu semiduplici aut duplici
majore recoluntur, occurrat Officium duplex majus aut minus, vel Semiduplex, vel
Festum aut dies Octava simplex, fit de Dominica cum Commemoratione Officii
occurrentis, juxta Rubricas, omissa IX Lectione ipsius Officii. Idem fit in
Dominicis minoribus, nisi in Dominicis per Octavam quamlibet privilegiatam II ordinis occurrat Festum duplex I classis et in die quidem Octava quod sit
Ecclesiæ universalis, aut in aliis Dominicis occurrat Festum quodvis Domini
aut quodlibet Duplex I vel II classis; quibus in casibus, ut supra, num. 2,
dictum est, fit de Festo, cum Commemoratione et IX Lectione Dominicæ. 

Under Tridentine rules, the 9th lesson only gets omitted on Sundays with a ninth response, I.e. without TeDeum. 

@mbab  I'm still on vacation, maybe you can take care of this for Divino Afflatu version in the meantime?
