### ISSUE TITLE
Commemoration of St. Lawrence's octave in Latin instead of English

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#3996]
With the "Tridentine - 1906" rubrics, the [commemoration of the octave of St. Lawrence at Lauds](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=8-16-2024&command=prayLaudes&version=Tridentine%20-%201906&testmode=regular&lang2=English&votive=#Laudes12) appears in Latin instead of English in the lang2 column. This is odd because the commemoration of the octave of the Assumption that precedes it is in English, and there are English texts for the feast of St. Lawrence.

**Comment by APMarcello3** [comment]
Closed by 7208223858cfa4ccd79a71da47886bd0245816b6
