### ISSUE TITLE
Preparatio Communionis and following parts improperly rendered in Masses

### ISSUE THREAD

**Issue by mmolenda** [DivinumOfficium/divinum-officium#400]
Preparatio Communionis and following parts improperly rendered in Masses in Latin column when full Mass is turned on and Rubrics are turned off. Example: http://divinumofficium.com/cgi-bin/missa/missa.pl?date=3-6-2016

![screen shot 2016-01-12 at 00 22 49](https://cloud.githubusercontent.com/assets/5938800/12249876/05615e46-b8c3-11e5-971a-b49ba51177cc.png)

**Comment by mbab** [comment]
Same as #386 ?
so fixed with c7b6ad9

**Comment by gregordick** [comment]
This was a regression introduced by 50d9f88.  The fix to #386 fixes the symptom, but there's still an extra line-break within the 'Preparatio Communionis' cell in Latin.

**Comment by mbab** [comment]
Differences in cell 'Preparatio Communionis' disappear when rubrics (Iungit manus.) and (Extendit manus.) are added to translations.

**Comment by gregordick** [comment]
Great, thanks.  We can close this, then.
