### ISSUE TITLE
Accents missing in prayers of pre-DA versions

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#4034]
(Setting liceity and all that aside)

If I go to the Tridentine office (I believe all versions, but I usually pick 1906) to take a collect that was subsequently changed **after** not only Divino Afflatu but during the reign of Pius XII, namely the collect of a holy pope, despite the prayer being one from the appropriate common used for other saints under DA1954, the accents are missing.

It looks like accents are there for the rest of the prayers including collects of suffrages removed in 1911. The prayer is correctly accented for the classical Assumption office as well.

I was wondering if there is perhaps an easier way to fix this than adding accents in every case. That seems tedious.

**Comment by APMarcello3** [comment]
The project of adding accents is ongoing for all pre-1960 texts.

**Comment by MRoth1910** [comment]
Bizarre response to be honest and a bit irritating because I am clearly missing something — this requires manual intervention for each one?

As far as collects go, I've yet to encounter this with anything DA. So as I said, that's a bit of a bizarre response (and if we were using 1939 for DA instead of 1954, this would be fixed already… so here we are).
