### ISSUE TITLE
duplicate numbering in the verses

### ISSUE THREAD

**Issue by tapatianbeast** [DivinumOfficium/divinum-officium#4035]
There is duplicate numbering in the verses that has been happening for some days in the 1960 rubrics![image](https://github.com/user-attachments/assets/c2577825-23e8-4c9a-870a-73750259c0c3)

**Comment by FAJ-Munich** [comment]
These two Breviary verses are indeed Verse 20 in the Vulgata. So this duplication is intentional. 
Besides, all Psalms are gradually receiving a double check as part of issue #838

**Comment by tapatianbeast** [comment]
I understand that, but it completely ruins the reading because the Latin and vernacular verses are not side by side.

**Comment by FAJ-Munich** [comment]
> I understand that, but it completely ruins the reading because the Latin and vernacular verses are not side by side.

The issue you are referring to is independent of the verse numbering. I just checked Thursday matins "Monastic 1963" and Friday matins "Rubrics 1960" version that makes use of Psalm 77. The Latin and English verse numberings are identical, e.g., Verse 20 is split in two. 

However, Latin is typically much shorter than most vernaculars as it is a precise and exact language. So everytime an English verse overruns into an extra line, there will be another "difference of one line" in the start of the following verse. As this depends on the wideness of the screen you use and also the font size, it is impossible to address this universally.
