### ISSUE TITLE
discrepancies in the verses

### ISSUE THREAD

**Issue by tapatianbeast** [DivinumOfficium/divinum-officium#4036]
There are discrepancies in the verses between the English and vernacular languages. I can see that there are two identical number verses in the Latin psalter, but I don't understand why they don't align with the numeration vernacular language.

![image](https://github.com/user-attachments/assets/4e35a53e-093d-42fa-8e24-1aae440f92d9)

**Comment by APMarcello3** [comment]
Cf. Issue #838

**Comment by tapatianbeast** [comment]
There's a verse missing in the Spanish version. It's not a matter of split or duplicate verses in Latin psalter. And this isn't the only canonical hour when this issue arises.
