### ISSUE TITLE
Litania

### ISSUE THREAD

**Issue by mbab** [DivinumOfficium/divinum-officium#407]
In `Major Special` '[Litania]', '[LitaniaM]', '[LitaniaT]' are same apart one coma. Is it correct?

**Comment by gregordick** [comment]
Probably not!  The 'M' variant is used for the monastic office and the 'T' variant for 1570, so presumably Laszlo must have had some reason for adding this, but I don't know what the differences should be.  I suppose the way to find out is to consult some appropriate breviaries.

**Comment by APMarcello3** [comment]
Closed by 47e2ade90
