### ISSUE TITLE
Names of commemorated popes are no longer translated

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#4072]
@FAJ-Munich 5d1a6014c140f6cd860f1678f5cb5463dd8037b8 eliminated the `[Rule]` section from many or all vernacular files. In general, I think this is a good thing, because the vernacular should be generated with the same rules as the Latin text. However, the deletion of rules like `CPapaM=` eliminated the translation of the names of commemorated popes. So, for example, at [Lauds on January 5 with 1960 rubrics](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=1-5-2024&command=prayLaudes&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=#Laudes9), the English translation of the oration for the commemoration now refers to "blessed Telésphorum thy Martyr" instead of "blessed Telesphorus thy Martyr" as it previously did.

A quick fix would be to restore the `[Rule]` section, but it would probably be better to create a new section to store the translation of the name of the person commemorated. Another solution that might work would be to use a substitution in the vernaculars to replace only the name of the commemorated pope in the `[Rule]` section.

**Comment by FAJ-Munich** [comment]
yes, I realised myself today as well..  pushing a fix now
I agree a new has should be created next. Let's fix it first
