### ISSUE TITLE
Missing Vespers Commemorations infra 8vam when Sancti are interspersed 

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#4105]
Pope St Damasus, as a semidouble with no particular importance, takes the ferial psalms etc.** but then is celebrated from the chapter on both the 10th and the 11th (as it outranks both the preceding and following days infra octavam). The octave and the feria are commemorated at the end per the rubrics (antiphon of II Vespers on the 10th, antiphon of I Vespers on the 11th). Currently the DA version is as in the Tridentine office with everything from the common, but the octave commemoration is omitted.

The octave commemoration is also omitted in the latter two versions of the Tridentine office, but that is a mistake…

**unless I'm missing something about the common of popes, since the site uses the 1954 recension of DA; I am pretty sure however that this is just a bug and that you only take material from the common if the pope in question is a double of the I or II class feast.

**Comment by FAJ-Munich** [comment]
As per the 1942 books and "restore the 54" I'd say you are right.

The changed Psalms vor S. Damasi have been added to database file `12-11.txt` by @APMarcello3  on Dec 11, 2020 as per commit 4a1b18fb94bd042a8b04feb3a3f4af0c618f40b8 . So, maybe there is a reason by 1954?

**Comment by APMarcello3** [comment]
I am not aware of any such reason, so @FAJ-Munich please go ahead and make the change.

**Comment by FAJ-Munich** [comment]
... the issue concerns more than just Dec 10/Dec 11, e.g. Aug-17. I'll take care of it but have to test smartest solution first
