### ISSUE TITLE
Missing verses in translations of Vexilla Regis

### ISSUE THREAD

**Issue by DLakomy** [DivinumOfficium/divinum-officium#411]
The verse "O Crux, ave" in the hymn "Vexilla Regis" contains one verse which is variable, depending on the liturgical season. Non of the translations provides the other than the Lent one. The missing ones are for May 3rd and September 14th.

I'm able to provide the missing verses in English and Polish (I will create a PR in a moment).

**Comment by gregordick** [comment]
> I'm able to provide the missing verses in English and Polish (I will create a PR in a moment).

Merged with thanks.  This bug can stay open to cover the other languages.

**Comment by peterdiekertz** [comment]
For the record, I just added the German translation of the hymn with all 3 variants (so only the Hungarian 3 May variant remains missing).
