### ISSUE TITLE
Compline of Nov 1 (DA)

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#4112]
Compline of Nov 1 is not of the feast under the DA reform; it only takes the Sunday psalms etc. when Nov 1 falls on Saturday. There is a special Compline of the Dead (abolished in 1960 as the office of the Dead begins with Matins like almost every other day of the year.

**Comment by APMarcello3** [comment]
@FAJ-Munich

**Comment by FAJ-Munich** [comment]
> Compline of Nov 1 is not of the feast under the DA reform; it only takes the Sunday psalms etc. when Nov 1 falls on Saturday. 

The 1942 book says for II Vespers of All Saints: 

> _Omnia ut in I Vesperis, sed loco ultimi Psalmi dicitur Ps. 115 **Crédidi**, ut ibidem notatur._ ... _Post Vesperas diei dicuntur Vesperæ et Completorium Defunctorum, ut inferius notatur_ ...

Then for All Souls it starts:

> _In II Vesperis Omnium Sanctorum ... post Versum **Benedicamus Dómino**, immediate dicuntur Vesperæ Defunctorum ..._

In so far, I wonder which book says differently?

> There is a special Compline of the Dead (abolished in 1960 as the office of the Dead begins with Matins like almost every other day of the year.

That's exactly how the website does show it right now:
https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=11-01-2024&command=prayCompletorium&version=Divino%20Afflatu%20-%201954&testmode=regular&lang2=English&votive=

**Comment by MRoth1910** [comment]
It did not show it earlier. I don't know what to tell you.
