### ISSUE TITLE
(clean code) base hash not used as data.text does not have a base column

### ISSUE THREAD

**Issue by d4h0y0sr** [DivinumOfficium/divinum-officium#4115]
Directorium.pm has an issue because data.txt does not have a base column.

sub load_data_data() function init the _data hash:

$_data{$ver}{base} = $base;

as data.txt does not have a base column, thus this value is always empty.

this affects get_kalendar, get_transfer, get s_transfer and get_tempora, as they are always returning '' and last line is never reach:

```
  my $ver = $_data{$version}{base};
  return '' unless $ver;
  return get_kalendar($ver, $day);
```

**Comment by FAJ-Munich** [comment]
The feature is in the code for 10 months now but not yet used by the official repository; it might well be used by some private forks. 
In view of #423, it should remain part of the code.
