### ISSUE TITLE
Incorrect Benedictio

### ISSUE THREAD

**Issue by mbab** [DivinumOfficium/divinum-officium#413]
Benedictio in Matutinum pre1960 is taken incorrectly in polish and probably other languages if Lectio is from Evangelium. 
The reason is hard coded regular expresion in Latin/English eq.:

``` perl
if ($w =~ /\!(Matt|Mark|Marc|Luke|Luc|Joannes|John) [0-9]+\:[0-9]/i) {$a[2] = $benedictio{Evangelica};}                                                  
elsif ($a[2] =~ /(evang|Gospel)/i) { $a[2] = $a[5]; }
```

I can try to prepare patch but it will need add to `Translate.txt` section contains uniform which can be used in regexp. This should match translation form of word Evangelica used in Benedictio and 'Lectio sancti Evangelii secundum'.

In latin

```
[Evangelica_regexp]
Evang
```

In polish

```
[Evangelica_regexp]
Ewangeli
```

In english

```
[Evangelica_regexp]
Gospel
```

Also in german `Translate.txt` file `[Nocturn 3]` 6th Benedictio is duplication of 3rd not proper translation, it is possible solution for a case of above bug but not proper one.

**Comment by gregordick** [comment]
Does the first regex (matching the evangelists' names) also need translated?  At a cursory reading it looks like this is the one that identifies when a reading *is* a Gospel reading, and the second is for the case (e.g. in ferial offices) where the third lesson is not a Gospel reading.

In an ideal world we would replace the entire subroutine with something much more robust, but that's probably too much work.

**Comment by peterdiekertz** [comment]
"Also in german Translate.txt file [Nocturn 3] 6th Benedictio is duplication of 3rd not proper translation, it is possible solution for a case of above bug but not proper one."
I think I edited something there when a wrong benediction showed up somewhere; thinking I had maybe copied sth wrongly. It may quite possible have been because of this bug.

**Comment by mbab** [comment]
I checked Latin texts and all lectio matching evangelist names has previous line match `evangel` word, so one regexp it enough. *All* means apart C12A and C12n which has Special Benedictio.

I'm to weak at Rules to rewrite whole subroutine :-)
