### ISSUE TITLE
Wrong reference in Missa/05-17 S. Paschalis Baylon Conf.

### ISSUE THREAD

**Issue by mmolenda** [DivinumOfficium/divinum-officium#4131]
Everything except Collect should come from Missa Os iusti, de Communi Confessoris non Pontificis (C5).
Currently Lectio, Evangelium and Postcommunio come from Commune Abbatis: Os iusti II (C4c)

**Comment by APMarcello3** [comment]
f9f1574a66e645e38da3471471bf67dec4cfb683
