### ISSUE TITLE
Wrong collect in Missa/06-25 S. Gulielmi Abbatis

### ISSUE THREAD

**Issue by mmolenda** [DivinumOfficium/divinum-officium#4133]
This proper should have its own collect, not one from Commune (C4c):

> Deus, qui infirmitáti nostræ ad teréndam salútis viam in Sanctis tuis exémplum et præsídium collocásti: da nobis, ita beáti Guliélmi Abbátis mérita venerári; ut ejúsdem excipiámus suffrágia et vestígia prosequámur.
Per Dominum…

**Comment by APMarcello3** [comment]
9f99bad67e01c1893a4ac4153d0aee40b438a3b4
