### ISSUE TITLE
Wrong oration on 7–12 January when they follow the first Sunday after Epiphany

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#4137]
According to the 1960 rubrics, the ferial days 7–12 January take the oration from Epiphany unless they follow the first Sunday, in which case they use the oration of that Sunday. This used to work until a week or two ago, but now these days have the oration of Epiphany even when they follow the first Sunday, e.g., [Lauds of January 10, 2023](https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=1-10-2023&command=prayLaudes&version=Rubrics%201960%20-%201960&testmode=regular&lang2=English&votive=). This isn't a problem in 2025, when January 12 will be the first Sunday after Epiphany, but it is a problem in most other years.

**Comment by APMarcello3** [comment]
@mbab and/or @FAJ-Munich

**Comment by FAJ-Munich** [comment]
`æ` in epiphaniæ does no longer match itself. strange
