### ISSUE TITLE
No prayer for responsible for state in Good Friday

### ISSUE THREAD

**Issue by mmolenda** [DivinumOfficium/divinum-officium#414]
Lack of prayer for responsible for state in Good Friday:
- before 1955 – _Oremus et pro Christianissimo Imperatore nostro (…)_
- after 1955 – _Oremus et pro omnibus res publicas moderantibus (…)_

**Comment by mmolenda** [comment]
@gregordick can you please confirm? If it's the case, I can add missing parts for Latin and English and Latin or English for vernaculars to avoid breaking of the structure.

**Comment by gregordick** [comment]
You're right.  It should come between the prayer for clergy and the prayer for catechumens. No idea why it's missing!  Please fix it if you can.

**Comment by mmolenda** [comment]
I'll push a fix along with Polish translation of Good Friday.

**Comment by gregordick** [comment]
@mmolenda's fix has been merged (thanks!) but Italian and Hungarian need translated from the English placeholders.
