### ISSUE TITLE
Collect ex Proprio Sanctorum in Monastic Office?

### ISSUE THREAD

**Issue by benjekman** [DivinumOfficium/divinum-officium#415]
I was very happy to find Divinum Officium (via the BrevMeum app) and to see that there's an option for the Monastic Office. But when I switch back and forth I can see that in the 1960 Rubrics there's a collect {ex Proprio Sanctorum}, which is for St Sebastian today, but in the pre-Trid Monastic option the collect is {ex Proprio de Tempore}. Why is this the case?

All the best,

b.

**Comment by gregordick** [comment]
The "Pre-Trident Monastic" uses a conjectured sanctoral calendar from the year 500.  It was an experiment by the original author of Divinum Officium.  In the long term I think it would be better to follow a real calendar!
