### ISSUE TITLE
Orations on Sundays of Advent and on ferias (DA and earlier)

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#4153]
The orations of the season during Advent, on Sundays and for ferias, are of the BVM and then either the prayer for the church or for the pope.

Currently they are listed as of the BVM vel ad lib, then either the oration for the church or the pope is displayed. At the very least, the second should not be labeled that way.

**Comment by APMarcello3** [comment]
4b555b6c108371c43f51fb7ed5a65577febe5c9c
