### ISSUE TITLE
Daily Mass for the dead issues

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#4159]
I'm on Divino Afflatu normally but I also checked 1960.

Days where a Mass for the dead should be allowed do not pull up the Mass for the dead correctly. The propers are there, but the full ps 42, the usual Agnus, and the prayer Domine qui dixisti are displayed (I believe and just peeked at the SSPX ordo to confirm that the former days of the octave of All Saints, the 5th through 8th, allow for this Mass, unless impeded by Sunday or a proper feast).

Shoot even if the days aren't allowed, there are cases where one may be allowed to say that Mass anyway so I'm not worried about the calendar problems, just that the texts display correctly.

**Comment by APMarcello3** [comment]
@FAJ-Munich @mbab
