### ISSUE TITLE
Wrong verse numbering in the Canticle of the Three Young Men

### ISSUE THREAD

**Issue by agheieff** [DivinumOfficium/divinum-officium#4169]
The numbering of the verses in the Canticle (Psalm 210) is wrong in all the languages except Danish. The marking before it says Dan 3:57-88,56, but the actual verses are numbered 57-75,56. This is because most lines contain two verses, with the "laudate et superexaltate eum in saecula." part omitted.

I checked this in the psalms1/ directories

I would make a PR, but I'm not familiar with the project's composing logic to be sure it won't break something

**Comment by APMarcello3** [comment]
Cf. issue #838
