### ISSUE TITLE
Easy way to get a link

### ISSUE THREAD

**Issue by rl1234567890** [DivinumOfficium/divinum-officium#417]
It would be nice to have an easy way to obtain a  link for a given hour, on a certain date, with a certain language, choice of rubrics, etc.

**Comment by luc--** [comment]
It would be useful, but the website uses POST methods with many arguments (for example in `kalendar.pl` of `web/cgi-bin/missa`) :
```HTML
<BODY VLINK=$visitedlink LINK=$link BACKGROUND="$htmlurl/horasbg.jpg" > 
<FORM ACTION="kalendar.pl" METHOD=post TARGET=_self>
<INPUT TYPE=HIDDEN NAME=setup VALUE="$setupsave">
<INPUT TYPE=HIDDEN NAME=date1 VALUE="$date1">
<INPUT TYPE=HIDDEN NAME=kmonth VALUE=$kmonth>
<INPUT TYPE=HIDDEN NAME=kyear VALUE=$kyear>
<INPUT TYPE=HIDDEN NAME=date VALUE="$odate">
<INPUT TYPE=HIDDEN NAME=command VALUE="$command">
<INPUT TYPE=HIDDEN NAME=officium VALUE="$officium">
<INPUT TYPE=HIDDEN NAME=testmode VALUE="$testmode">
<INPUT TYPE=HIDDEN NAME=browsertime VALUE="$browsertime">
```

Won't the URL be too long with GET methods (as described [here](https://boutell.com/newfaq/misc/urllength.html))?

**Comment by luc--** [comment]
The mobile version uses GET by default : for example, <http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=8-10-2016&command=prayMatutinum&version=Rubrics%201960&testmode=regular&lang2=English&votive=>

**Comment by luc--** [comment]
Also exists with missa : <http://divinumofficium.com/cgi-bin/missa/missa.pl?lang2=Polski&Propers=1&date=3-26-2016>

**Comment by rl1234567890** [comment]
Is there a way do get a link for the Requiem and for an hour of the Office of the Dead?

**Comment by gregordick** [comment]
> Is there a way do get a link for the Requiem and for an hour of the Office of the Dead?

For the office, add `&votive=C9`, and for Mass, `&votive=Defunctorum`.  E.g.

http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=10-14-2018&command=prayVespera&version=Rubrics%201960&testmode=regular&lang2=English&votive=C9
http://divinumofficium.com/cgi-bin/missa/missa.pl?lang2=English&Propers=1&date=10-14-2018&votive=Defunctorum

**Comment by rl1234567890** [comment]
Many thanks! Is there a way also to turn the "Solemn" and "Rubrics" options on?

**Comment by gregordick** [comment]
> Many thanks! Is there a way also to turn the "Solemn" and "Rubrics" options on?

Yes: there are `solemn` and `rubrics` parameters which should be set to `1` in order to enable the corresponding option, but for these to take effect, the `first` parameter must also be set to `1`.  For example:

http://divinumofficium.com/cgi-bin/missa/missa.pl?lang2=English&date=10-16-2018&solemn=1&first=1
