### ISSUE TITLE
Problem with alternative epub generator

### ISSUE THREAD

**Issue by bjjnpy** [DivinumOfficium/divinum-officium#4191]
Hello,
I tried to contact Marcin Babnis but breviarium@srubarovi.cz isn't available so maybe someone can help me here on GitHub.
I successfully used this Breviarium generator a couple of times. However an unknown error has been appearing recently and I don't know how to workaround it. Has anyone got any idea what to do now?
![HPW6EciLTKBOaWN0](https://github.com/user-attachments/assets/ceb5e144-bca9-4b8e-a0a1-bbaf22589c9f)

**Comment by mbab** [comment]
This look strange, I would try to do:
-  check if there is enough disk space?
-  check if command without arguments (stop at `mbab1/doepub`) is working?
- remove docker image

 breviarium@srubarovi.cz  is certainly not my address, use [first name] . [last name] @ gmail.com
_(można pisać po polsku :-)_

**Comment by bjjnpy** [comment]
- There's 10 GB of free space on C: and 342 GB on D: drive.

- Without arguments:

![image](https://github.com/user-attachments/assets/66914fdf-6524-4200-a6b9-46287e411d68)

- Removing Docker image didn't help

**Comment by bjjnpy** [comment]
Thanks you very much, it's working now!
