### ISSUE TITLE
Anticipated sundays: pre-PiusX psalmody?

### ISSUE THREAD

**Issue by peterdiekertz** [DivinumOfficium/divinum-officium#420]
At Matins on anticipated sundays (e.g. Sat. 23 Jan 2016, Dom. III post Epi.), the Trient options don't work properly as they use the 12 psalms from Saturday and try to separate them into 3 nocturns (which doesn't work).
Unfortunately I can't locate the rubric about anticipated sundays in the printed breviary, so I don't know which psalms should be shown (probably the 18 Sunday psalms though).

**Comment by gregordick** [comment]
Thanks.  Pre-Pius X, anticipated Sundays were of simple rite, so there should be a single nocturn of twelve (Saturday) psalms.  The Sunday's third-nocturn lessons are read.  This is covered by R.G. IV. 4-5.

**Comment by peterdiekertz** [comment]
Closing in favour of the older #220
