### ISSUE TITLE
Incorrect commemorations with 2020 calendar

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#4216]
@FAJ-Munich, the only problems I found with #4215 during testing are with new calendar celebrations (2020 calendar). Some incorrect commemorations are happening.

On August 14 with the new rubrics, the headline says “Commemoratio ad Laudes tantrum” but doesn’t say what is commemorated (St. Eusebius is). However, perhaps celebrating St. Maximilian on this day is all wrong, since the Vigil of the Assumption is II class, which doesn’t permit the celebration of a new saint: _Cum sanctissima_ only allows new saints to be celebrated on III class feasts and vigils. Having St. Maximilian as an option may be something left over from before _Cum sanctissima._
https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=8-14-2024&command=prayLaudes&version=Rubrics%201960%20-%202020%20USA&testmode=regular&lang2=English&votive=

On May 13, when celebrating Our Lady of Fatima, lectin 3 is a commemoration of St. Robert Bellarmine instead of a reading for the feast. There should only be a commemoration at Lauds.
https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=5-13-2024&command=prayMatutinum&version=Rubrics%201960%20-%202020%20USA&testmode=regular&lang2=English&votive=

St. Robert is also incorrectly commemorated at Vespers:
https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=5-13-2024&command=prayVesperae&version=Rubrics%201960%20-%202020%20USA&testmode=regular&lang2=English&votive=

On August 9, the Vigil is incorrectly being commemorated at Matins, but (correctly) there is no commemoration at Vespers.

So, it seems that whatever is producing these incorrect commemorations may depend on the rank or some other detail of the data files for the new celebrations rather than the code.

**Comment by APMarcello3** [comment]
I have moved 08-14n to the Obsolete folder per the argumentation above.

On May 13, since there is no reading established, I repeated Lectio7 from 08-22 (appropriately a reading from St. Robert Bellarmine). The issue of the commemoration at Vespers I leave to @FAJ-Munich to rectify.

Similarly, for St. Edith Stein I selected the Lectio4 patristic reading from the Common.

**Comment by fiapps** [comment]
> I have moved 08-14n to the Obsolete folder per the argumentation above.
> 
> On May 13, since there is no reading established, I repeated Lectio7 from 08-22 (appropriately a reading from St. Robert Bellarmine). The issue of the commemoration at Vespers I leave to @FAJ-Munich to rectify.
> 
> Similarly, for St. Edith Stein I selected the Lectio4 patristic reading from the Common.

Shouldn't the 3rd lectio come from the common in the absence of a proper lectio?

**Comment by APMarcello3** [comment]
I made this decision in light of: https://www.newliturgicalmovement.org/2017/04/ecclesia-dei-commission-decree-on.html?m=1

**Comment by FAJ-Munich** [comment]
> St. Robert is also incorrectly commemorated at Vespers: https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=5-13-2024&command=prayVesperae&version=Rubrics%201960%20-%202020%20USA&testmode=regular&lang2=English&votive=
> 

By the same logic: 
In the case of April 28, for instance, I guess the commemoration of S. Pauli a Cruce at Vespers needs to be dropped, too?
https://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=4-28-2025&command=prayVesperae&version=Rubrics%201960%20-%202020%20USA&testmode=regular&lang2=English&votive=

**Comment by fiapps** [comment]
> I made this decision in light of: https://www.newliturgicalmovement.org/2017/04/ecclesia-dei-commission-decree-on.html?m=1

After thinking about this for a while, I think I see the logic of it. I can recognize this as a reasonable choice, though I don't know if other people who celebrate the feast would make the same choice.
