### ISSUE TITLE
Holy Innocents Vespers 12/28 on Saturday DA rubrics

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#4225]
When Holy Innocents falls on Saturday, the octave of the Nativity is commemorated, not the Sunday, which is omitted, even if it is to be celebrated the next day. Currently the Sunday is commemorated, but not the octave.

The commemoration comes **after** Becket, however.

**Comment by APMarcello3** [comment]
@FAJ-Munich

**Comment by FAJ-Munich** [comment]
> not the Sunday, which is omitted, even if it is to be celebrated the next day

Why should that be the case? The concurrent office is always commemorated and, under DA rubrics, as the very first commemoration.

Divino Afflatu: Tit. VII, §5
```
Quando plures fieri debeant Commemorationes, cauto quod in Vesperis semper fit prima 
Commemoratio de Officio concurrenti, cujusvis ritus et dignitatis …
hic ordo servatur …
1 De Dominica qualibet vel de Vigilia Epiphaniæ …
5 de Duplici minori …
7 de die infra 8vam Nativitatis Domini … 
```

Breviarium 1942, p. 425:
```
Si vero Dominica incidat in Festum S. Thoma: aut S. Silvestri, 
ipsa die Officium fit de Dominica, cum Commemoratione Festi occurrentis 
et Octavæ Nativitatis
```

So the commemoration, imho, are Dominica infra Octavam, Thomas, Die infra Octavam (which needs to be restored just like for Dec 29 #4226)

**Comment by MRoth1910** [comment]
Rubricarius apparently made a mistake in copying 2013/2019 to 2024.
