### ISSUE TITLE
Sancta Missa - problems on 2nd February, versions older than 1960

### ISSUE THREAD

**Issue by DLakomy** [DivinumOfficium/divinum-officium#437]
When I view the texts for the Mass on 2nd February everything is ok, as long as I use 1960 version or newer. For versions older than 1960 Blessing of Candles is not included among the latin texts, while they are still displayed on the vernacular side.

**Comment by petermottola** [comment]
Closely related to issue #315.

**Comment by APMarcello3** [comment]
Closed by 79de911c4.
