### ISSUE TITLE
Commemoration Vigilia St. Matthiae

### ISSUE THREAD

**Issue by mbab** [DivinumOfficium/divinum-officium#443]
This year should be on Feb 24

**Comment by peterdiekertz** [comment]
But only in the Mass (in Quadragesima, nihil fit de Vigilia in Officio).

**Comment by mbab** [comment]
Actually in 2016 we have this Commemoration at 23rd Laudes in DA and 1910.

**Comment by peterdiekertz** [comment]
Certainly not; this year the vigil is on 24 Feb.
Am 15.02.2016 19:23 schrieb "mbab" <notifications@github.com>:

**Comment by petermottola** [comment]
Right, because the reckoning is based on "x days before the Kalends", not a certain "day of the month".

**Comment by petermottola** [comment]
Additionally, this problem also exists in the 2012 Kalendarium, suggesting that the calcac branch will need to copy the code used to reckon the Feast and paste it into a section used to calculate the date of the Vigil.

**Comment by gregordick** [comment]
This is something that's very difficult to fix on `master`, as separate offices assigned to the same day can't be transferred independently of one another.  On `calcalc` they can, but I haven't yet implemented the special handling for the end of February in leap years.

**Comment by gregordick** [comment]
More, by e-mail from a user:

> Being a leap year there seems to be an error in the Martyrology for tomorrow's (23rd) office of Prime. It's pulling the same reading and date and day of the moon as for the 28th.

**Comment by APMarcello3** [comment]
Cf. #1443

**Comment by APMarcello3** [comment]
From a correspondent:

> the 9th "lectio" in the Matins of tomorrow (In Cath. S. Petri) according to 
the
> "Divino Afflatu", is not "Hanc confessionem" (as normally it would be) but is
> taken from the Common of the Vigils of the Apostles because of the
> coincidence of the following 3 conditions: where are not in Lent-time, the
> feast of S. Peter is on Saturday, and 2014 is not leap-year ("si hoc festum
> ante quadragesimam occurrerit in sabbato, et annus non sit bissextilis,
> legitur ix lectio de homilia vigiliae anticipatae s. Matthiae, ut in vigiliis 
Ap.orum")

This won't happen again until 2031.

**Comment by gregordick** [comment]
Plan: Move the propers for the vigil into a separate file, and create another new file referencing both the propers of St Peter Damian and of the vigil.  Use the transfer tables to pick the appropriate files, so that in non-leap years they look something like
```
02-23=02-23-feast-vigil
```
and in leap years something like
```
02-23=02-23-feast
02-29=02-23-vigil
```
(N.B. In leap years, the 24th of February gets mapped to 02-29 for calendar lookups, hence the above.  See `get_sday()`.)
