### ISSUE TITLE
1960: St. Agatha wrong Magnificat antiphon

### ISSUE THREAD

**Issue by igneus** [DivinumOfficium/divinum-officium#445]
At Vespers according to the 1960 rubrics St. Agatha should have proper Magnificat antiphon "Stans beata Agatha in medio carceris ....", not "Veni sponsa" from the Common as is currently the case.

EDIT 2015-02-06: The Vespers of St. Agatha also have wrong psalms. There ought to be (in all versions of the Roman Breviary) psalms "de Communi Apostolorum, sed loco ultimi, Ps. Lauda Jerúsalem". Not psalms from the Commune Virginum.

**Comment by rl1234567890** [comment]
Actually even in this 1604 breviary the same antiphon is prescribed:

https://books.google.com/books?id=8vxZjRtm5BwC&pg=PA729#v=onepage&q&f=false

**Comment by igneus** [comment]
So there is quite probably this issue also in the "Trident 1570" version. I will check facsimile of the first edition of the Tridentine breviary by my next visit of the library.

**Comment by igneus** [comment]
Having checked the Tridentine "typical edition", I confirm that Trident 1570 should also have the same proper antiphon for Vespers.

**Comment by igneus** [comment]
(I don't know if you get notifications on edit. So: I've edited the issue. There is one more bug.)

**Comment by gregordick** [comment]
Thanks, @mbab!

**Comment by rl1234567890** [comment]
I can go ahead and fix it for the Italian, if that is OK.

**Comment by gregordick** [comment]
@rl1234567890: @mbab's change should have fixed it in all languages, but please do check.

**Comment by rl1234567890** [comment]
It works flawlessly. Thanks!

On Sat, Feb 6, 2016 at 1:43 PM, Gregor Dick <notifications@github.com>
wrote:

> @rl1234567890 <https://github.com/rl1234567890>: @mbab
> <https://github.com/mbab>'s change should have fixed it in all languages,
> but please do check.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DivinumOfficium/divinum-officium/issues/445#issuecomment-180870942>
> .
>



-- 
+ Non nobis, Domine, non nobis, sed nomini tuo da gloriam
Meae editiones librorum. Αἱ ἐμαὶ ἐκδόσεις βίβλων.
<http://www.lulu.com/spotlight/bedwere>

**Comment by mbab** [comment]
There is another bug with St. Agatha: 1st Vespers (in 1570) have Psalms Ant's from Commune.

**Comment by mbab** [comment]
And also Vespers should have Sundays Psalms.
