### ISSUE TITLE
Wrong hymn label (?) in C7.txt (Latin)

### ISSUE THREAD

**Issue by DLakomy** [DivinumOfficium/divinum-officium#470]
In C7.txt (Latin) we can find something like this:
`[Hymnus Vespera]`
`{:H-Tristeserantapostoli:}v. Fortem virili pectore`

[Link to the file](https://github.com/DivinumOfficium/divinum-officium/blob/master/web/www/horas/Latin/Commune/C7.txt) (see the line 21)

I suggest changing to this:
`{:H-Fortemvirilipectore:}v. Fortem virili pectore`

At the moment I didn't touch it, since I don't know what is this 'label' used for and if it can be changed freely.

**Comment by gregordick** [comment]
The `{::}` construct is used by the unmaintained standalone version.  It's used to reference images containing the chant.  In this case, there's no image for *Fortem virili pectore*, but in Paschaltide it's sung to the tone of *Tristes erant Apostoli*.  I think we should leave it as it is for now; perhaps in the future we should purge all of the `{::}` records.
