### ISSUE TITLE
Tranfer of Commemoratio Pro Papa

### ISSUE THREAD

**Issue by petermottola** [DivinumOfficium/divinum-officium#482]
We list (and have listed since 2014) the Votive Collect for the anniversary of the installation of Pope Francis on March 19th, but according to the FSSP Ordo (2014), page 21, it should be transferred:
"NOTE:  March 20th is the anniversary of the solemn installation of His Holiness, Pope Francis, (perpetually transferred to March 20 due to the Feast of Saint Joseph [Rubric #363]).  The Votive Collect Pro Papa must be added (under one conclusion) to the Collect of all Masses, whether low or sung, unless the Votive Mass for the Anniversary of the Coronation of the Pope is said.   The Votive Mass for the Coronation of the Pope is obligatory in cathedral and collegiate churches, and is 'permitted, with the consent of the local Ordinary, as a Votive Mass of the 2nd class, in the individual churches on a day in which celebrations are held in honor of the Pope.'  [see Rubric #365]"

Besides needing to normally be transferred to the 20th, this year, the 20th being Palm Sunday, does it transfer to ... Monday of Holy Week?  But that is a first class day, as is every day until April 5th...

**Comment by gregordick** [comment]
363(b) says that, when accidentally impeded, the commemoration is transferred to the first day not of the first class; so indeed, it should be transferred to Low Tuesday.

**Comment by gregordick** [comment]
Fixed in 9420db9..210c833.
