### ISSUE TITLE
Compline Hymn on Easter Day in Italian Translation

### ISSUE THREAD

**Issue by rl1234567890** [DivinumOfficium/divinum-officium#488]
Happy Easter!

Te lucis ante terminum is not sung today, according to the Latin. However, the Italian translation shows it. 
I'll be glad to fix it, if you tell me how. Thanks!

**Comment by DLakomy** [comment]
Same in Hungarian.

**Comment by DLakomy** [comment]
In Italian Completoriump1960.txt change _Inno_ to _Hymnus_. It will be skipped on the website as expected. But wait, there's more! It will be still shown as _Inno_ thanks to the file Translate.txt ;)

Could you provide the fix for Hungarian as well? (same file, change _Himnusz_ to _Hymnus_)

**Comment by gregordick** [comment]
Thanks all!
