### ISSUE TITLE
Monastic Prime corrections

### ISSUE THREAD

**Issue by gregordick** [DivinumOfficium/divinum-officium#490]
From a user:

> For instance at Prime today [2016-03-30].....
> After Deus in adjutorium meum intende ect. the Hymn Jam Lucis is recited followed by the first antiphon from Lauds of Sunday. The psalms for feria quarta today are correct. The chapter for feasts Regi saeculorm immortali et invisibili soli Deo honor et Gloria in saecula saeculorum. Amen is recited followed by the versus which is correct. Kyrie eleison Christe eleison Kyrie eleison Pater Noster in silence up to et ne nos ect. (the creed and confitero are only said on ferias and sundays with no feast) The prayer for Prime every day is as follows.. Domine Deus omnipotens, qui ad principium hujus diei nos pervenire fecisti: tua nos hodie salva virtute; ut in hac die ad nullum declinemus peccatum, sed semper ad tuam justitiam faciendam nostra procedant eloquia, dirigantur cogitations et opera. Per Dominum nostrum Jesum Christum ect. Amen  R.Domine exaudi orationem meam V. Et clamor meus ad te veniat. Benedicamus Domino, Deo Gratias. Then the martyrology is read followed by V. Pretiosa in conspectu Domine R. Mors Santorum ejus  Sancta Maria et omnes sancti intercedant pro nobis ad Dominum ut nos mereamur ab eo adjurari et salvia. qui vivit et regnat in saecula saeculorum Amen.
> V. Deus in adjutorium intende  R. Domunum ad adjuvandum me festina 3 times
> Gloria Patri ect.
> Kyrie eleison Christe eleison Kryie eleison
> Pater in silence up to et ne nos ect.
> V. Respice in servos tuos, Domine, et in opera tua dirige filios eorum R. Et sit splendor Domini Dei nostri super nos, et opera manum nostrarum dirige super nos, et opus manuum nostrarum dirige.
> Gloria Patri ect.
> Oremus
> Dirigere ect...
> Comemoratio, omnium fratrum familiarum ordinis nostril atque benefactorum nostrorum 
> V. Requiescant en pace R. Amen 
> Psalm 129 followed by Requiem aeternam dona eis Domine et lux perpetua luceat eis R. A porta inferi V. Erue Domine animas eorum
> R. Requiescant en pace V. Amen
> V. Domine exaudi orationem meam R. Et clamor meus ad te veniat
> Oremus,,
> Deus veniae largitor et humanae salutis amator: quaesumus clementiam tuam; ut nostrae congregations fratres, propinquos et benefactors qui ex hoc saeculo transierunt beata Maria semper Virgine intercedente cum omnibus Sanctis tuis ad perpetuae beatudinis consortio pervenire concedes. Per Dominum nostrum ect......
> V. Requiem aeternam dona eis Domine R. Et lux perpetua luceat eis
> V. Requiescant en pace R. Amen
> Reading from the Holy Rule for March 30th Chapter 48
> I realize this is a lot other than the psalms everything stays the same for Prime every day.

@gregordick note: this date is during the octave of Easter.  How should the monastic office be affected?

**Comment by gregordick** [comment]
For 2016-03-31:

> Matins......
Psalm 3 and the invitatory are correct,
It says Hymnus Omittitur which is not correct. The hymn Rex sempiterne Domine ect. is said for Matins for Pascahltide
1st Nocturn
One Antiphone only
Jesum qui crucifixus est, quaeritis, alleluja; non est hic: surrexit enim, sicut dixit vobis alleluja
The ferial psalms for Thursday (feria V) are said namely,,,,
73, 74, 76, 77 verses 1-39 Gloria and 77 verses 40-78, Psalm 78. Verisicle is correct. Absolution Exaudi Domine is correct. Blessings for Matins when a Gospel is read are 1st lesson Jube Domine Benedicere. Evangelica lectio sit nobis salus et protector. Amen 2nd Divinum auxilium maneat semper nobiscum 3rd Ad societatem civium supernorum, perducat nos Rex Angelorum. The lessons and responseries that you have are correct for today.
Second nocturne....
One antiphone only
Venite, et videte locum, ubi positus erat Dominus, alleluja, alleluja. psalms...
79,80, 81,82,83, and 84
Short lesson is
2 Corinthians 5, 14-15
Caritas Christi urget nos: aestimantes hoc, quoniam si unus pro omnibus mortuus est ergo omnes mortui sunt> et pro omnibus mortuus est Christus;* ut et qui vivunt, jam non sibi vivant, sed ei, qui pro ipsis mortuus est et resurrexit. Deo Gratias
V. Mane nobiscum Domine alleluja.
R. Quoniam advesperacit alleluja.
Kyrie eleison Christe eleison Kyrie eleison
Pater noster ect. in silence until et ne nos ect.
Oremus
Prayer is correct.
For Lauds
All the psalms and antiphones are correct..
The little chapter should be 1 Cor. 5, 7
Fratres: Expurgate vetus fermentum, ut sitis nova conspersio sicut estis azymi, Etenim Pascha nostrum immolatus est Christus. Deo Gratias
R. Br. Surrexit Dominus de sepulcro* Alleluja, alleluja. Surrexit repeat. V. Qui pro nobis pependit in ligno. Alleluja. Gloria Patri ect. Surrexit.
Hymn
Aurora lucis rutilat ect.
Versicle is correct
Benedictus antiphone is correct.
Oration is correct.
Prime is correct with the daily exceptions I enumerated yesterday.
The minor hours are correct except the hymns are said as well as the little chapters and versicles proper to paschal tide for each hour.
Note for the duration of paschaltide the termination for the hymns for Prime, Terce, Sext and None is....
Gloria tibi Domine qui surrexisiti hodie, cum Patre et Sancto Spiritu en sempitere saecula Amen.

**Comment by APMarcello3** [comment]
Closing this issue as Monastic office is being revamped entirely to bring it into conformity with the 1963 Breviarium Monasticum. Cf. issue #1256
