### ISSUE TITLE
Missing commemoration on April 3rd 2016 (rubrics 1960)

### ISSUE THREAD

**Issue by DLakomy** [DivinumOfficium/divinum-officium#495]
According to the table of concurrence, in the Vespers today we should commemorate _In Annuntiatione_. This commemoration is missing when I read Vespers according to 1960 rubrics. Am I right?

**Comment by gregordick** [comment]
That's correct.  This will be fixed when `calcalc` is merged (which I hope will be before the next time that the Annunciation is transferred...).

**Comment by APMarcello3** [comment]
Closed by 72346f6bfb18f36243b7bc68cc84164911d24b4a.
