### ISSUE TITLE
04-14 Tempore Paschali

### ISSUE THREAD

**Issue by APMarcello3** [DivinumOfficium/divinum-officium#504]
The commemoration of Sts. Tiburtius et al. in Paschaltide should have the following antiphon and verse in Paschaltide rather than the "Filiae Ierusalem"/"Pretiosa":

Ant.  Lux  perpétua  * lucébit  Sanctistuis, Dómine, et ætérnitas témporum,allelúja.

V. Sancti et justi, in Dómino gaudéte.   Allelúja.  
R. Vos   elégit   Deus   inhereditátem sibi. Allelúja.

**Comment by gregordick** [comment]
Fixed and deployed to live site.
