### ISSUE TITLE
Missing/wrong elements in the Little Office

### ISSUE THREAD

**Issue by gregordick** [DivinumOfficium/divinum-officium#506]
In 1955/1960, Ps. 128 is missing: http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=4-16-2016&caller=&command=prayCompletorium&version=Rubrics%201960&testmode=regular&lang2=English&votive=C12

This is present in Divino and earlier.

With all rubrics, 'Converte nos', and the Gloria after 'Deus in adjutorium' are missing.

CC @DLakomy.

**Comment by DLakomy** [comment]
'Converte nos', and the Gloria after 'Deus in adjutorium' are still missing.

**Comment by gregordick** [comment]
> 'Converte nos', and the Gloria after 'Deus in adjutorium' are still missing (Compline).
> 
> One more observation: the verse 'Diffusa est gratia' is missing before 'Pater noster' in Matins.

@mbab: Could you please take a look at this one?

**Comment by DLakomy** [comment]
I think the Antiphona ad BMV is missing in the Compline. I see it in my Diurnale, but not on the website.

**Comment by DLakomy** [comment]
@igneus This issue concerns the Little Office (Officium Parvum).

**Comment by igneus** [comment]
@DLakomy Oh, I'm sorry for the noise. I must have skipped the title when reading the comments.

**Comment by DLakomy** [comment]
There is more issues:
- there is no Gloria Patri in [Responsory2] in C12A (it is correct), it is present on the website, though which is wrong),
- conclusion missing during the Advent (I haven't tested other seasons), all hours,
- lack of Gloria Patri and Alleluia at the beginning, in minor hours,
- wrong capitulum and antiphon during the Advent (I haven't tested other seasons); however, the file C12A seems to be ok.

**Comment by mbab** [comment]
Close?

**Comment by DLakomy** [comment]
Few things remain:

1. Wrong capitulum, verse and antiphon in Vesperæ (tested using 1960 rubrics, during Advent; I'm unsure about the other seasons).
2. Antiphon to BMV missing in Compline.

By the way: other languages have to be conformed, to include the corrections. I'm unsure if it's a reason to leave this issue open.

**Comment by gregordick** [comment]
Let's leave it open until everything's fixed.

**Comment by mbab** [comment]
Please let me know if #680, doesn't fix this or close this.

**Comment by DLakomy** [comment]
The files seem to be conformed properly, so I think almost everything is fixed. One thing remains only: the vernacular files (except for Polish) don't contain `[Commemoratio]` section. See _Commemoratio de Sanctis_ [here](http://divinumofficium.com/cgi-bin/horas/officium.pl?votive=C12&rubrics=Divino%20Afflatu&browserdate=7-26-2017&command=prayLaudes). It is rendered in Latin in all vernacular languages, apart from Polish.
