### ISSUE TITLE
SS. Cleti et Marcellini (April 26) - collect

### ISSUE THREAD

**Issue by igneus** [DivinumOfficium/divinum-officium#511]
While the "Nova et Vetera" 1960 rubrics breviary has the same collect as is currently used for all historical versions at divinumofficium, the 1912 Antiphonale has a custom collect for this feast:

```
Beatórum Mártyrum paritérque Pontíficum Cleti et Marcellíni
nos, Dómine, fóveat pretiósa conféssio: * 
et pia júgiter intercéssio tueátur. 
Per Dóminum.
```

The same is true for a 1898 breviary.

**Comment by gregordick** [comment]
That collect is already used for Tridentine rubrics:

http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=4-26-2016&command=prayLaudes&version=Trident%201910&testmode=regular&lang2=English&votive=

The rubrics that we describe as 'Divino afflatu' use the common of Popes.  Whether this should be so is debatable, but it seems that that was a deliberate design decision on the part of Laszlo Kiss.

If there's a place where the wrong collect is used, could you please post a link?

**Comment by igneus** [comment]
Oh, you are right. The app uses the "new" collect only from Divino Afflatu on. I should have checked better.

But it is definitely not correct. I checked my last old breviary - Divino Afflatu rubrics like the Antiphonale - printed in Ratisbona/Regensburg 1927. It still has the "old" collect. So the collect must have been changed sometime between 1927 and 1960.

If the collect was subject of some minor reform between 1927 and 1955, would it be preferable for the app to follow the old version ("Divino Afflatu" meaning "state of texts at time of introduction of the new psalter and rubrics") or the new version ("latest state of texts before the 1955 rubrics reform was introduced")?

**Comment by gregordick** [comment]
"Divino afflatu" in divinumofficium-ese means "calendar of 1942, rubrics immediately prior to the Holy Week reforms".  I think.  For added confusion, "Trident 1910" means "calendar of 1888, rubrics prior to Pius X".

**Comment by peterdiekertz** [comment]
I think that's accurate.
The common of supreme pontiffs is from 1942. If Divino Afflatu would refer to 1910 or 1913, it would lack feasts like the Precious Blood (1 July) or Christ the King.

I guess that when calcalc is implemented, the options can maybe be given some more precise names? (Like Divino 1942 or Trient 1888).

**Comment by igneus** [comment]
Ok, thanks for explanation. Then this issue seems to be void and can be closed.

**Comment by gregordick** [comment]
> I guess that when calcalc is implemented, the options can maybe be given some more precise names? (Like Divino 1942 or Trient 1888).

This could be done independently of `calcalc`.  I'll open a new issue so that it doesn't get forgotten.
