### ISSUE TITLE
Errors in Masses for Rogation Days

### ISSUE THREAD

**Issue by petermottola** [DivinumOfficium/divinum-officium#519]
When in "Rubrics 1960" a third class feast falls on Feria Secunda in Rogationibus the title of the Missa page includes the subtitle "Commemoratio: Feria Secunda in Rogationibus" but the day is not commemorated.  I am not sure which is the error, the notation or the non-inclusion.
In "Feria Tertia infra Hebdomadam V post Octavam Paschae ~ IV. classis", which is also Feria Tertia in Rogationibus although this is not noted on the page (at least, it is not noted when a third class feast already fills the subtitle spot), there is an instruction to omit the gloria in the Mass "Vocem iucunditátis".  This is incorrect.  The gloria is omitted in the II class votive Mass for rogation days "Exaudivit de templo" but not in the ferial Mass.  The votive Mass is only celebrated "in ecclesiis in quibus fit processio" etc. according to the rubric.  It would also be a nice feature to be able to select these Mass texts on this day.
The day before the Ascension is labelled "In Vigilia Ascensionis ~ Feria".  In Rubrics 1960 this is a II class day and should be labelled as such.

**Comment by APMarcello3** [comment]
Vigil of the Ascension has been fixed in 1960 rubrics.

**Comment by APMarcello3** [comment]
Title has been fixed for Feria Tertia in Rogationibus as well.

**Comment by APMarcello3** [comment]
"Commemoratio" title has been changed to "Scriptura" for Monday and Tuesday Rogations under 1960 rubrics.

**Comment by APMarcello3** [comment]
Closed by 0251b2015.
