### ISSUE TITLE
Wrong preface on Festum Sanctissimi Corporis Christi (1960)

### ISSUE THREAD

**Issue by DLakomy** [DivinumOfficium/divinum-officium#533]
According to the rubric number 498, and to the propers given in the missal, it should be Communis, not de Nativitate. It can be checked here: http://musicasacra.com/2007/10/missale-romanum-1962/ (page 32 and 458, according to the PDF numbering).

I will provide a suggested fix in a moment. Please tell me, if it's ok.

**Comment by APMarcello3** [comment]
Technically, the ad libitum preface of the Eucharist may also be used. It might be helpful to provide that instead as a compromise.

**Comment by DLakomy** [comment]
As far as I know the preface of the Eucharist is allowed only in France and Belgium (it's a Neogallican preface, not a Roman one). Is there any document that would allow its usage in other countries?

**Comment by DLakomy** [comment]
If we agree with each other, should my PR be merged? Is it technically correct?

By the way. If the preface of the Eucharist _must_ be used in France, I suggest changing the preface for this language only. We could at least open an issue at the moment.

**Comment by petermottola** [comment]
Just noting for completeness that the traditional response at Prime "Qui natus es de Maria virgine" was already correctly replaced with "Qui sedes ad dexteram Patris" in our existing 1960 code, so this issue with Nativity texts is limited to Mass only.

**Comment by DLakomy** [comment]
I will merge when I'll find some free time (manual merge is needed, unfortunately).

**Comment by DLakomy** [comment]
The fix has been merged.
