### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lemtom** [DivinumOfficium/divinum-officium#545]
I understand most texts to fall under “Fair Use”, but what about everything else? Is there any specific license in mind?

**Comment by gregordick** [comment]
The licences under which the texts are used are recorded at http://divinumofficium.com/www/horas/Help/credits.html.

As to the code, Laszlo Kiss wrote the original version of the blurb at http://divinumofficium.com/www/horas/Help/brevitechnical.html:

> This part of the help manual is written explicitly for encouraging anyone interested in the topic to write his/her own system, using whatever he/she wants from these ideas. The only restriction is that we at the Divinum Officium Project [Laszlo's version read "I"] have no legal responsibility for any mistake, and my ideas cannot be copyrighted, limiting our rights or the access of others to the same ideas.

The last sentence is relevant but a bit vague.  It would be good to clarify this.  I would suggest that we license the software under the GPL or the MIT License.  The former might be more compatible with Laszlo's wishes.  Does anybody have any opinions?

**Comment by lemtom** [comment]
I suppose any license would mean copyrighting the scripts: a public domain release would be the closest to such a wish, and relicensing the project as-is would be fraud. But he said ideas, and to my knowledge ideas can’t be copyrighted (only patented, perhaps).

“No legal responsibility for any mistake”, this part would be covered by the MIT license and even most public domain releases. The fair-use nature of some of the texts would already be a big legal barrier to selling this software in any modified form, except perhaps for publishers who would use this is an interface for liturgical translations they own the rights to. The latter group might want to encrypt or obfuscate their fork to protect their texts, not an ideal situation but in my opinion preferable to not having such options at all. The access to the ideas is guaranteed by this Github project. Forking this project for own use on Github already means having the source code viewable and forkable, regardless of any sublicensing.

I would really caution against the GPL. It’s a very viral license, long and technical. They depend on copyright law to be enforceable too. The large scope of the project combined with the (unfortunately) niche subject is already a big barrier for undesirable reuse. The MIT license or a Public Domain declaration (such as Creative Commons Zero) would also be very “future-proof”, since many copyleft licenses are incompatible which eachother and there might be future usage situations that we can not envision now.

**Comment by apotheon** [comment]
My impression, given what Laszlo Kiss wrote, is that CC0 or Unlicense would be much better fits than the GPL (or, failing that, some other public domain dedication).  The words "my ideas cannot be copyrighted" in particular read like an attempt to dedicate his work to the public domain, which is at the core of both CC0 and the Unlicense.

If, for some reason, this project opts to forego strict adherence to that statement, the next best thing would be some copyfree license, such as the MIT/X11 License mentioned by lemtom.

**Comment by gregordick** [comment]
I interpreted "my ideas cannot be copyrighted" etc. to mean that he wished any derived works to be open-source and freely available, hence my suggestion of the GPL.  On the other hand, the interpretations above are entirely defensible.

I am somewhat disinclined to choose CC0 or similar, since I would be reluctant to cede as much as those licences do without strong evidence that this was LK's intention.  A similar argument could be employed against the significant constraints imposed by the GPL.  I would have no objections to using a variant of the MIT License.

**Comment by ariofrio** [comment]
As far as I can tell, there are four possible things in the project whose copyright status can be considered:

1. The original source texts, many of which are in the public domain.
2. The scans of the source text. Even though Microsoft/Internet Archive claims to be able to restrict use of their scan for "non-commercial, personal, research, or education purposes, or any fair use," [Project Gutenberg's lawyers conclude](gutenberg) that scans are not copyrightable.
3. The organization of the materials into a system understandable by a program. I don't know the kind of work that was involved in this, but it could range from "substantial reorganization" which is not copyrightable to "a new compilation of existing materials", which is (according to [Gutenberg][]).
4. The programs that parse the materials and display them. This is certainly copyrightable.

(3) and (4) refer to contributions to this project, and are owned by the respective contributors [as far as I can tell](https://cla.github.com/#why-is-a-cla-necessary).

  [gutenberg]: http://www.gutenberg.org/wiki/Gutenberg:No_Sweat_of_the_Brow_Copyright

**Comment by cpelish** [comment]
Has there been any further discussion on this? I'd like to be able to create an android app that serves this content without requiring access to the internet, but the lack of license makes me apprehensive about using this content. Thanks!

**Comment by apotheon** [comment]
Considering the GPL is not enforceable without employing copyright law, I think any claim that something "cannot be copyrighted" is definitionally contrary to the idea of applying the GPL.

For something that applies to both text and code, by the way, the [Open Works License](http://copyfree.org/content/standard/licenses/owl/license.txt) (a medium-nonspecific license) may be a more appropriate choice than either the MIT License (which explicitly refers to code) or any non-CC0 license from Creative Commons (all of which CC itself has claimed are not suitable for code).  OWL Is roughly like the MIT License with broader applicability to both software and non-software works.

That said, I'm fine with the MIT License as well.

**Comment by APMarcello3** [comment]
As the director of this project since the death of Laszlo Kiss (designated as such by his widow and children), it has been my practice over the past nearly 10 years of directing this Project to approve any requests to use our code and texts for any legitimate purpose, especially since all content is freely available on Github. Forgive my ignorance, but I am not exactly sure to what end such a license would be necessary.

**Comment by APMarcello3** [comment]
@cpelish Please feel free to use the code in any way you see fit. If you have any questions, please contact me directly at canon DOT missae AT gmail DOT com.

**Comment by rl1234567890** [comment]
> @cpelish Please feel free to use the code in any way you see fit. If you have any questions, please contact me directly at canon DOT missae AT gmail DOT com.

Father, why don't you just proclaim it to be [Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/)?

Quoting:

You are free to:
Share — copy and redistribute the material in any medium or format
Adapt — remix, transform, and build upon the material
for any purpose, even commercially.

It seems that people really need a clear, legal statement.

**Comment by apotheon** [comment]
As a friend previously involved in this said of the situation:

> Creative Commons advises against using their licenses for software, except for CC-0. See https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

Please don't use CC-BY.  CC0 is a perfectly suited selection for meeting the standard of permission provided in the creator's statements about free use.

**Comment by fiapps** [comment]
Unlike MIT and BSD licenses, CC0 does not protect the authors from being sued for a software error that displays the wrong office. More seriously, some texts (e.g., a Polish translation of the psalms) are used with permission, and cannot unilaterally be made public domain.

**Comment by apotheon** [comment]
I guess we're back to the best options being MIT License for popularity of the license or OWL (or maybe COIL) for purposes of making it a more suitable license for non-code content as well (thought MIT License is better for non-software than CC-BY is for software).

**Comment by APMarcello3** [comment]
I have added the MIT license to the README.md file.

**Comment by apotheon** [comment]
Thank you.  I appreciate your attention to this, and your choice to make the materials broadly available for use by others.  The importance of the spread of such knowledge as is represented by this project supersedes other concerns, in my opinion, and the reassurances of legality for reuse provided by a straightforward, human readable, broadly compatible license like the MIT License are important for that purpose.
