### ISSUE TITLE
C9p.txt and C11p.txt are the same

### ISSUE THREAD

**Issue by DLakomy** [DivinumOfficium/divinum-officium#549]
The files said contain the same (at least I don't see any difference). Is it correct?

**Comment by mbab** [comment]
`C9` is `Officium Defunctorum` and is in only use as `ex` in `11-02`. 
`C9p` is `In Festis Beatae Mariae Virginis ` so I suspect existence of this file is mistake.

**Comment by mbab** [comment]
this is also in #233

**Comment by mbab** [comment]
Fixed. Please close.
