### ISSUE TITLE
St. Bonaventure's name missing from oratio

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#575]
As of 0912248 (merging pull request #567 from @mbab), the oratio for St. Bonaventure calls him "beatum N." instead of "beatum Bonaventuram" (see [the current output from Pofficium.pl](http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=7-14-2012&command=prayLaudes&version=Rubrics%201960&testmode=regular&lang2=English&votive=)). Also, the oratio has lost its accents. The said commit changed Latin/Commune/C4a to use references to C4 instead of duplicating texts. In principle this is a good thing, but when one copy of a text has accents, and another does not, it would be best to keep the accented text.

Furthermore, in this case it has caused the substitution of "N." with the saint's name to fail, which seems to be due to a bug in the Perl code rather than an error in the data. I copied the accented prayer previously in C4a into C4, but this did not fix the problem.

**Comment by mbab** [comment]
Again the proper link should point to C4 not C4a, I will look at all such cases tomorrow.
As accents I'm trying to copy them if section are linked, but just omit the case (will repair this).

**Comment by fiapps** [comment]
#576 contains the change I mentioned above: it does not involve a link, but placing the oratio with the accents in C4.

**Comment by mbab** [comment]
It is corrected. So please close the issue.
