### ISSUE TITLE
Abbreviations of books

### ISSUE THREAD

**Issue by luc--** [DivinumOfficium/divinum-officium#582]
Hello,

I haven't found any tables for all the abbreviations used in DivinumOfficium (only this pagehttp://divinumofficium.com/www/horas/Help/Abbreviations1.html)… It seems that all abbreviations aren't the same for each translation or even not the same in a single abbreviation.

For example, the book of Jeremy is written `Jerem` or `Jer`, or `Ex`, `Exod` and `Exodus` for the book of Exodus, etc. We can also note that abbreviations are sometimes ended by a point.

As I'm actually working on an automatic conversion from French text files (provided by the Abbaye du Barroux) to the format used in DO, I have to do a list of the abbreviations used in DO. Wouldn’t it be an occasion to have the same abbreviations everywhere in any languages ?

I would suggest using abbreviations based on Latin names of the books of the Bible : Gen, Ex, Lev, Num, Deut, Ios, Iud, etc. It would then be simple to use them in any language of DO by a simple parsing script.

---

PS : A useful method to find abbreviations used in DO :

``` bash
grep -rnw <directory_of_DO> -e "\!abbreviation"
```

**Comment by gregordick** [comment]
Standardising the abbreviations for each language would be an excellent idea.  I agree with your suggestions for the Latin; furthermore, I think it would be best to those used by a particular edition of the liturgical books where possible.

> It would then be simple to use them in any language of DO by a simple parsing script.

Could you please describe this suggestion in more detail?

**Comment by fiapps** [comment]
> I think it would be best to those used by a particular edition of the liturgical books where possible.

I think the 1961 editio typica would be the edition to follow. This is the official reference for the version we call "Rubrics 1960." Its abbreviations are terminated with a period: Luc., Rom., 1 Tim., 1 Ioann., etc. Unlike DO, it does not use book name abbreviations in the readings of matins, where the name of the book has just been given in full. For example, DO today has (using italics for rubrics):

> **_Lectio 1_**
> Lectio sancti Evangelii secundum Matthaeum.
> _Matt 16:24-27_

The _editio typica_ has:

> Lectio sancti Evangelii secundum Matthaeum.
> _Lectio I_ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; _Cap. 16, 24-27_

However, the abbreviations of the _editio typica_ are not normative. The choice of abbreviations is an editorial decision.

As for using the Latin abbreviations in other languages, I have no objection, but I've seen commits changing Latin abbreviations to English ones in the English translation.

**Comment by luc--** [comment]
@gregordick 
>> It would then be simple to use them in any language of DO by a simple parsing script.

> Could you please describe this suggestion in more detail?

I thought about some simple bash script applied to all current files which would change old forms in new normalized abbreviations chosen by the project (with regex probably)…
Of course, it would firstly imply to search all old forms (with grep for example).

Anyway, it wouldn’t be part of the project, as it would only serve to make one conversion of current files, would it?

@fiapps 
> As for using the Latin abbreviations in other languages, I have no objection, but I've seen commits changing Latin abbreviations to English ones in the English translation.

If we want abbreviations adapted to each language, I think it would be possible to make it automatically by adding some other regex rules in current perl scripts (and so keeping the same abbreviations in each data file)… But is it really necessary?

**Comment by luc--** [comment]
Here it is.

? : not sure of it (deduced from other abbreviations but not found)
NV : Nova Vulgata
**Remark** : Sometimes, for complete words (`Iudith` for example), there is no period.

----

VETUS TESTAMENTUM

- Genesis : Gen.
- Exodus : Ex.
- Leviticus : Levit.
- Numeri : Num.
- Deuteronomium : Deut.
- Iosue : Ios.
- Liber Iudicum : Iudic.
- Ruth : Ruth ?
- Liber I. Regum (vel NV : I Samuel) : 1 Reg.
- Liber II. Regum (vel NV : II Samuel) : 2 Reg.
- Liber III. Regum (vel NV : I Regum) : 3 Reg.
- Liber IV. Regum (vel NV : II Regum) : 4 Reg.
- Liber I. Paralipomenon (vel Chronicorum) : 1 Paral.
- Liber II. Paralipomenon (vel Chronicorum) : 2 Paral.
- Liber I. Esdræ (vel NV : Esdræ) : 1 Esdr.
- Liber II. Esdræ (vel NV : Nehemiæ) : 2 Esdr.
- Liber III. Esdræ (non canonicus) : 2 Esdr.
- Liber IV. Esdræ (non canonicus) : 4 Esdr.
- Tobias (vel NV : Thobis) : Tob.
- Iudith : Iudith
- Esther : Esth.
- Iob : Iob ?
- Liber Psalmorum : Ps.
- Liber Proverbium : Prov.
- Liber Ecclesiastes : Eccl.
- Canticum Canticorum : Cant.
- Liber Sapientiæ : Sap.
- Liber Ecclesiastici : Eccli.
- Prophetia Isaïæ : Isai.
- Prophetia Ieremiæ (vel NV : Ieremia+Lamentationes) : Ierem.
- Prophetia Baruch : Baruch.
- Prophetia Ezechielis : Ezech.
- Prophetia Danielis : Dan.
- Prophetia Osee : Osee
- Prophetia Ioel : Ioël.
- Prophetia Amos : Amos
- Prophetia Abdiæ : Abdiæ ?
- Prophetia Ionæ : Ionæ
- Prophetia Michææ : Mich.
- Prophetia Nahum : Nahum, Nah. ?
- Prophetia Habacuc : Habacuc, Hab. ?
- Prophetia Sophoniæ : Soph ?
- Prophetia Zachariæ : Zach.
- Prophetia Malachiæ : Malach.
- Liber I. Machabæorum : 1 Mach.
- Liber II. Machabæorum : 2 Mach.

NOVUM TESTAMENTUM

- Evangelium secundum Matthæum : Mtth. / Mt.
- Evangelium secundum Marcum : Marc.
- Evangelium secundum Lucam : Luc. / Lc.
- Evangelium secundum Ioannem : Ioann. / Io.
- Actus Apostolorum : Act.
- Epistola Pauli ad Romanos : Rom.
- Epistola Pauli ad Corinthios I. : 1 Cor.
- Epistola Pauli ad Corinthios II. : 2 Cor.
- Epistola Pauli ad Galatas : Gal.
- Epistola Pauli ad Ephesios : Ephes.
- Epistola Pauli ad Philippenses : Phil.
- Epistola Pauli ad Colossenses : Col.
- Epistola Pauli ad Thessalonicenses I. : 1 Thess.
- Epistola Pauli ad Thessalonicenses II. : 2 Thess.
- Epistola Pauli ad Timotheum I. : 1 Tim.
- Epistola Pauli ad Timotheum II. : 2 Tim.
- Epistola Pauli ad Titum : Tit.
- Epistola Pauli ad Philemonem : Philem. ?
- Epistola Pauli ad Hebræos : Hebr.
- Epistola catholica Iacobi : Iacobi ?
- Epistola Petri I. : 1 Petri
- Epistola Petri II. : 2 Petri
- Epistola Ioannis I. : 1 Io.
- Epistola Ioannis II. : 2 Io.
- Epistola Ioannis III. : 3 Io.
- Apocalypsis Ioannis : Apoc.

**Comment by gregordick** [comment]
Thanks, looks good.  The one alteration that I think should be made is to use 'J' where appropriate.  This will be changed automatically to 'I' at runtime for "Rubrics 1960" and later versions.

**Comment by fiapps** [comment]
The 1961 _editio typica_ was reprinted photographically by Libreria Editrice Vaticana in 2009 as part of the series Monumenta Liturgica Piana. It's a bit expensive (€110), but important for anyone trying to produce a breviary for the extraordinary form.

The abbreviations in the Missal sometimes differ from those in the breviary (e.g., "1 Io." instead of "1 Ioann."). Also, for many books of the Old Testament, the abbreviation may never occur, because these are read only at matins. However, if we make the editorial decision use the book abbreviation instead of "Cap." when giving the references for matins, we could also make the editorial decision to use the abbreviations of the Missal.

In the cases where there are two alternatives, I would generally prefer the shorter one.

I think a Wiki here on GitHub would be a good place to document this and other aspects of the project.

**Comment by luc--** [comment]
Thanks. Just two more questions : I think I'll do it in a few days, but do I have to add an abbreviations.html help page on the website?

I'll also add a page on the wiki, do I put the script somewhere in the project?

**Comment by luc--** [comment]
@fiapps 
Do those abbreviations fit better with those of the breviary (I changed them a bit) :
---
VETUS TESTAMENTUM

    Genesis : Gen.
    Exodus : Ex.
    Leviticus : Levit.
    Numeri : Num.
    Deuteronomium : Deut.
    Iosue : Ios.
    Liber Iudicum : Judic.
    Ruth : Ruth
    Liber I. Regum (vel NV : I Samuel) : 1 Reg.
    Liber II. Regum (vel NV : II Samuel) : 2 Reg.
    Liber III. Regum (vel NV : I Regum) : 3 Reg.
    Liber IV. Regum (vel NV : II Regum) : 4 Reg.
    Liber I. Paralipomenon (vel Chronicorum) : 1 Paral.
    Liber II. Paralipomenon (vel Chronicorum) : 2 Paral.
    Liber I. Esdræ (vel NV : Esdræ) : 1 Esdr.
    Liber II. Esdræ (vel NV : Nehemiæ) : 2 Esdr.
    Liber III. Esdræ (non canonicus) : 3 Esdr.
    Liber IV. Esdræ (non canonicus) : 4 Esdr.
    Tobias (vel NV : Thobis) : Tob.
    Iudith : Judith
    Esther : Esth.
    Iob : Job
    Liber Psalmorum : Ps.
    Liber Proverbium : Prov.
    Liber Ecclesiastes : Eccl.
    Canticum Canticorum : Cant.
    Liber Sapientiæ : Sap.
    Liber Ecclesiastici : Eccli.
    Prophetia Isaïæ : Isai.
    Prophetia Ieremiæ (vel NV : Ieremia+Lamentationes) : Jerem.
    Prophetia Baruch : Baruch.
    Prophetia Ezechielis : Ezech.
    Prophetia Danielis : Dan.
    Prophetia Osee : Osee
    Prophetia Ioel : Joël.
    Prophetia Amos : Amos
    Prophetia Abdiæ : Abdiæ ?
    Prophetia Ionæ : Jonæ
    Prophetia Michææ : Mich.
    Prophetia Nahum : Nah.
    Prophetia Habacuc : Hab.
    Prophetia Sophoniæ : Soph.
    Prophetia Zachariæ : Zach.
    Prophetia Malachiæ : Malach.
    Liber I. Machabæorum : 1 Mach.
    Liber II. Machabæorum : 2 Mach.

NOVUM TESTAMENTUM

    Evangelium secundum Matthæum : Mtth.
    Evangelium secundum Marcum : Marc.
    Evangelium secundum Lucam : Luc.
    Evangelium secundum Ioannem : Ioann.
    Actus Apostolorum : Act.
    Epistola Pauli ad Romanos : Rom.
    Epistola Pauli ad Corinthios I. : 1 Cor.
    Epistola Pauli ad Corinthios II. : 2 Cor.
    Epistola Pauli ad Galatas : Gal.
    Epistola Pauli ad Ephesios : Ephes.
    Epistola Pauli ad Philippenses : Phil.
    Epistola Pauli ad Colossenses : Col.
    Epistola Pauli ad Thessalonicenses I. : 1 Thess.
    Epistola Pauli ad Thessalonicenses II. : 2 Thess.
    Epistola Pauli ad Timotheum I. : 1 Tim.
    Epistola Pauli ad Timotheum II. : 2 Tim.
    Epistola Pauli ad Titum : Tit.
    Epistola Pauli ad Philemonem : Philem.
    Epistola Pauli ad Hebræos : Hebr.
    Epistola catholica Iacobi : Jacob.
    Epistola Petri I. : 1 Petri
    Epistola Petri II. : 2 Petri
    Epistola Ioannis I. : 1 Ioann.
    Epistola Ioannis II. : 2 Ioann.
    Epistola Ioannis III. : 3 Ioann.
    Apocalypsis Ioannis : Apoc.

**Comment by fiapps** [comment]
I found the following differences:

* "Iac." (our "Jac.") instead of "Jacob."
* "Matth." instead of "Mtth." - however, this is in the title "Liber 3 in Matth. cap. 19", not directly in a biblical citation.
* "Is." instead of "Isai."

**Comment by luc--** [comment]
Thanks. I keep those.

PS : For *Matth.*, it was an error of mine.

**Comment by rarty** [comment]
In the Missal, Threni (Lamentations of Jeremias) is usually abbreviated Thren. (cf. 1962 Missal, Sept. 15, Tractus)

**Comment by gregordick** [comment]
> Thanks. Just two more questions : I think I'll do it in a few days, but do I have to add an abbreviations.html help page on the website?

Thanks.  No need for abbreviations.html.

> I'll also add a page on the wiki, do I put the script somewhere in the project?

`admin/` is where we collect assorted scripts.  Please feel free to commit it there, and to create as many subdirectories as you feel necessary.

**Comment by luc--** [comment]
#613

**Comment by peterdiekertz** [comment]
Please don't change the German translation. I'm using the abbreviations there which come from the official translation of the bible approved by the bishops' conferences of the German-speaking countries. These abbreviations are in use everywhere from ordos to parish newsletters, also in the realm of the 'extraordinary' form. It makes no sense to replace them by a translation from the Latin, which in some cases doesn't even resemble the translated German one at all.

**Comment by peterdiekertz** [comment]
Correction: "to replace them by an abbreviation from Latin, which"

**Comment by luc--** [comment]
I've changed all files in my pull request, but with one commit for each language in order to be able to answer to that sort of problems. So thanks to git, it's quite simple to cancel the modification for German files.

However, I thought of it as a standardization of the code : rendering it differently for each language could possibly be a next step, so imho it would be better to keep the modifications everywhere...

**Comment by peterdiekertz** [comment]
I'm all for the standardization of the abbreviations. But the abbreviations in the German files are already "standardized"; and I don't see why the abbreviations should be in a different language.

**Comment by luc--** [comment]
@peterdiekertz @fiapps  

Hello, I think I have misunderstand this issue : at the beginning, I remarked that there was many different abbreviations used in Divinum Officium, so I proposed to use *one* set of abbreviation and then made a script (with final help from @LGD-Fr) to standardized all this.

I must agree with you that was a mistake as it’s more logical to have abbreviations adapted to the language used. However, I think my work (and which of @LGD-Fr which has improved it) isn’t totally useless for DO, and I’ve two ideas about what can be done with it : 

- Use Latin abbreviations everywhere *only* in the code, but add some perl script to translate in the right language when the html is generated (so I cancel my current git pull, before making an other one later with that modification) ;
- Use the script only on languages which have no standardized abbreviations in DO (and then thinking about an other script to convert it in the right language, this step is quite simple now).

Does one of those solution sound good for you ? I personally think the second one is probably a lot more simple…

**Comment by fiapps** [comment]
Standardizing abbreviations is good, and this work has thus far led to a standard list of abbreviations for Latin, as well as a script to enforce that standard. This is good as a model for other languages, but I don't think it should be directly applied to other languages.

Rather, for each other language where the problem of diverse abbreviations exists, a standard set of abbreviations for that language should be chosen and documented. Then a script can be used to enforce the standard.

Concretely, I suggest that at this point you prepare a pull request that changes only the Latin texts and adds your script to the admin directory. Other languages can be addressed in the future with the involvement of those who maintain them. It might not be possible to address the issue for Magyar (Hungarian), because the person who worked on that translation is deceased.

**Comment by gregordick** [comment]
> Concretely, I suggest that at this point you prepare a pull request that changes only the Latin texts and adds your script to the admin directory. Other languages can be addressed in the future with the involvement of those who maintain them.

I agree with this plan.
