### ISSUE TITLE
Incorrect statement about a commemoration

### ISSUE THREAD

**Issue by DLakomy** [DivinumOfficium/divinum-officium#587]
On August 14th 2016 ([link](http://divinumofficium.com/cgi-bin/horas/officium.pl?version=Rubrics%201960&browsertime=08-14-2016)), there is a statement about a commemoration in the title of the office (Commemoratio ad Laudes tantum: In Vigilia Assumptionis B.M.V.).

It shouldn't be there, as there is no commemoration.

**Comment by petermottola** [comment]
This is a known issue, [discussed](https://github.com/DivinumOfficium/divinum-officium/issues/293#issuecomment-161806421) in #293.
