### ISSUE TITLE
Octave of the Assumption should not appear for Reduced 1955

### ISSUE THREAD

**Issue by peterdiekertz** [DivinumOfficium/divinum-officium#594]
...as it was abolished then.

**Comment by mbab** [comment]
Could You provide link?
Or it is corrected and should closed?

**Comment by peterdiekertz** [comment]
<http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=8-18-2016&command=prayLaudes&version=Reduced%201955&testmode=regular&lang2=English&votive=>

**Comment by gregordick** [comment]
@mbab: The change above is not correct.  Not all of the 1960 calendar changes apply to 1955.  A correct fix would require a new calendar, but for the 1955 rubrics I don't think it's worth the effort.

**Comment by APMarcello3** [comment]
Deleted the 1955 St. Lawrence and Assumption octaves.
