### ISSUE TITLE
Latin spelling changes without j

### ISSUE THREAD

**Issue by rarty** [DivinumOfficium/divinum-officium#595]
Words with the root ad/abjicio (like "adjicientur" in the Gospel today, Mt 6:33) should become "adicientur" when the letter j is not used. i.e., the root is spelled ad/abicio. Currently, the output with Rubrics 1960 is "adiicientur". There might be other examples like this.

**Comment by luc--** [comment]
Excuse my ignorance, but why *adiicientur* wouldn’t be acceptable ?

**Comment by rarty** [comment]
It very well may be acceptable. But many of the books that do not use "j" (and nearly all since 1960) do not use it:

e.g., the example I give above from the 1962 *Missale Romanum* (Dominica XV post Pent.):

![texshop_image](https://cloud.githubusercontent.com/assets/6454162/24083175/afd53b90-0ca0-11e7-9afa-7da9b7f73edc.png)

**Comment by APMarcello3** [comment]
https://github.com/rarty is correct. 

“Item, circa modum rectae scripturae vocabulorum, haec notentur: a. Litera ‘J’ aboletur, et eius loco adhibeatur semper litera ‘I’.”

Ordinationes ad librorum liturgicorum editores directe a S. Rituum Congregatione datae, mensibus octobris et novembris 1961.

In Braga, C. and Bugnini, A. (eds.), Documenta ad Instaurationem Liturgicam Spectantia. Roma: CLV - Edizioni Liturgiche, 2000, p. 1110

**Comment by luc--** [comment]
Thanks for the reference. So every time we encounter `ii` or `ij` or `ji`, it should be replaced by `i`. Am I correct?

Furthermore, your reference was published in 1961. Is this correct – that is traditional – in older editions?
