### ISSUE TITLE
Errors in triduum introduced by #590

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#596]
The merging of 1955/1960 offices with the older offices in pull request #590 from @mbab caused some errors in the output for the 1960 rubrics (the only ones I currently test):

* At the offices of Holy Saturday from Lauds to None, the English translation of the antiphon (or "prayer", if you prefer) "*Christus factus est … super omne nomen*" has been replaced by the Latin. The rest of the prayers still have an English translation. Examples [Lauds](http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?command=prayLaudes&date1=4-7-2012&version=Rubrics%201960&testmode=regular&lang2=English&votive=), [Prime](http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?command=prayPrima&date1=4-7-2012&version=Rubrics%201960&testmode=regular&lang2=English&votive=), [Terce](http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?command=prayTertia&date1=4-7-2012&version=Rubrics%201960&testmode=regular&lang2=English&votive=)
    * The Italian translation does not have this problem: the Italian translation of the antiphon appears just as it always did. I haven't checked other languages.
* Compline in the Triduum should conclude with the usual prayer *Visita, quæsumus.* Instead, it ends with the prayer of the day *Réspice, quǽsumus.* Examples: [Holy Thursday](http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?command=prayCompletorium&date1=4-5-2012&version=Rubrics%201960&testmode=regular&lang2=English&votive=), [Good Friday](http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?command=prayCompletorium&date1=4-6-2012&version=Rubrics%201960&testmode=regular&lang2=English&votive=), [Holy Saturday](http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?command=prayCompletorium&date1=4-7-2012&version=Rubrics%201960&testmode=regular&lang2=English&votive=) (in this case, the erroneous prayer is *Concéde, quǽsumus*).

**Comment by gregordick** [comment]
@mbab: Could you please take a look?
