### ISSUE TITLE
BMV de Mercede should take everything from the Proprium and Commune (?)

### ISSUE THREAD

**Issue by peterdiekertz** [DivinumOfficium/divinum-officium#615]
The "Divino" settings show the ferial psalms for the feast of BMV de Mercede, 24 September, duplex majus. I think the psalms from the Common need to be used instead, according to the rubric which is at the beginning of the Proprium Sanctorum in the Divino books ("In omnibus Festis novem Lectionum Domini, beatae Mariae Virginis, Angelorum, sancti Joannis Baptistae, sancti Joseph, Apostolorum, Evangelistarum, nec non in omnibus Duplicibus I vel  II  classis, integrum Officium dicitur ut in Proprio vel Communi").

**Comment by APMarcello3** [comment]
Should be fixed by 5a378dade.
