### ISSUE TITLE
Wrong commemorations on October 6, Vespers, pre-1960

### ISSUE THREAD

**Issue by DLakomy** [DivinumOfficium/divinum-officium#617]
Vespers on October 6: Latin version displays only one commemoration (_of S. Brunonis Confessoris_) while in vernacular there three (the one mentioned plus _of S. Mark, Pope_  and _of the Holy Martyrs Sergius, Bacchus, Marcellus and Apuleius_). The problems occurs while rubrics older than 1960 are used.

[Link](http://divinumofficium.com/cgi-bin/horas/officium.pl?browsertime=10-6-2016&version=Divino%20Afflatu&command=prayVespera).

I'm unfamiliar with these rubrics, so I'm unsure which version is correct.

**Comment by gregordick** [comment]
My Divino breviary has a rubric _Et fit commemoratio tantum præcedentis_, and this is borne out by section VII. in the _Additiones et variationes_, so the text as currently displayed in the Latin is correct.  Pre-Divino, I think all of the commemorations should in principle be made (although there, of course, the feasts are in different places).
