### ISSUE TITLE
Problem with German encoding

### ISSUE THREAD

**Issue by peterdiekertz** [DivinumOfficium/divinum-officium#624]
The German translation of the "reliqua omittuntur, nisi Laudes separandae sint" at the end of Matins is currently shown as "Das Folgende betet man nur, wenn sich die Laudes nicht unmittelbar anschlieÃŸen". In the last word there should be the letter ß, as I put it into the Ordinarium files. I know this will be because of a wrong encoding, but I don't know how to fix it. ß is shown correctly when it occurs in other files.

**Comment by fiapps** [comment]
The output is a consequence of the encoding of the file being misidentified as CP-1252. You can force the encoding to be recognized as UTF-8 by placing a [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark) (BOM) at the beginning. The easiest way to do this is to use an editor with good text encoding support to save the file in this format. I do it on macOS with TextWrangler, which is free.
