### ISSUE TITLE
BMV de Guadalupe

### ISSUE THREAD

**Issue by igneus** [DivinumOfficium/divinum-officium#645]
http://divinumofficium.com follows, I suppose, the 1960 General Roman Calendar. Then at least with the "Rubrics 1960" version the feast of BMV de Guadalupe should be left out, as it is not in the [General Roman Calendar](https://en.wikipedia.org/wiki/General_Roman_Calendar_of_1960).

**Comment by APMarcello3** [comment]
The reason for retaining the feast of Our Lady of Guadalupe is mainly a practical one, in that Catholics on two continents should be allowed to celebrate this feast. If one wishes to celebrate the ferial office, one can easily do so by selecting the "Seasonal" option and omitting the Commemoration.
