### ISSUE TITLE
Commemorations are missing the "Per Dominum" conclusion

### ISSUE THREAD

**Issue by peterdiekertz** [DivinumOfficium/divinum-officium#676]
If there is more than one commemoration, the conclusion "$Per Dominum" is only shown for the last commemoration.

**Comment by DLakomy** [comment]
From 1960 Breviarium general norms:
249. The collect of the Office of the day is always said with its own conclusion, the rule given at No. 110 a being observed. The collects belonging to commemorations, however, are concluded only after the last one; but the Oremus is said before each collect.

**Comment by peterdiekertz** [comment]
Was this different in previous rubrics? I can't find anything explicitly written, but have here a breviary from 1942 which says "Per Dominum" for e.g. today (Cathedra S. Petri Romae) after both the oration of St. Paul and St. Prisca.

**Comment by DLakomy** [comment]
[Here](http://divinumofficium.com/www/horas/Help/Rubrics/R30.txt) (DA Rubrics):
5. Quando plures Orationes dicuntur, prima tantum dicitur sub sua conclusione
Per Dominum. vel aliter, ut supra : alie non concluduntur, nisi in ultima Oratione ; 
sed unicuique Orationi semper præponitur Oremus, preterquam in
Officio Defunctorum, in quo, alio modo quam ut supra, Orationes dicuntur: item
in Litaniis, Orationes omnes dicuntur conjunctim sub uno Oremus, ut suis
locis habetur.

**Comment by peterdiekertz** [comment]
Alright then.
