### ISSUE TITLE
Rubrics in the martyrology

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#694]
At the end of the martyrology for 23 February (read on the previous day), there are rubrics explaining what to do in leap years (bissextile years). As was pointed out to me, it is a bit confusing to have these rubrics in ordinary black text, like the rest of the martyrology that is meant to be read aloud.

Is it possible to format these as rubrics? I tried putting the relevant lines in parentheses, but this didn't cause them to be formatted as rubrics.

Another alternative would be to simply remove these rubrics, since the program will automatically present the correct martyrology each day. However, they do serve some purpose by assuring users that it's not a mistake that *Sexto Kaléndas Mártii* occurs two days in a row in bissextile years.

The relevant files are `web/www/horas/Latin/Martyrologium*/02-23.txt`.

**Comment by gregordick** [comment]
I agree that these should be in red, but I don't believe there's support for that in the martyrology currently.  It shouldn't be too hard to add.

**Comment by fiapps** [comment]
I changed the title because there is another case in which there are rubrics in the martyrology: Christmas. The rubrics are already in parentheses in `web/www/horas/Latin/Martyrologium*/12-25.txt`. All we need is code to put text in parentheses in red.

**Comment by DLakomy** [comment]
I've made a quick and dirty solution ([17ed4ae](https://github.com/DLakomy/divinum-officium/commit/17ed4aec68f2b67cfd3eb5fda4d37aa4ba523dc1) in my fork, will try to improve it).

There is a problem I'd like to mention: not every text in parentheses is a rubric. In fact, there is a lot of comments in parentheses, which are meant to be read aloud (I believe so), for instance `(ut beátus Ignátius ad Antiochénses scribit)` in `Latin/Martyrologium1960/05-06.txt`. How should we define rubrics, then?

**Comment by fiapps** [comment]
I was under the impression that we were generally using parentheses to indicate rubrics, but a search of the data files shows that this is not the case: with use them for conditionals, for parentheses in text, and for rubrics or pseudo-rubrics (e.g. `(fit reverentia)` in various psalms). Furthermore, in the case of the martyrology, I see that there are dozens of parentheses that are meant to be normal text, while I only only of two dates (02-23 and 12-25) on which we have rubrics. So I don't think we should use parentheses in the martyrology to indicate rubrics.

Some other syntax is needed. What comes to mind is curly braces, e.g.:
```
consecrare, de Spiritu Sancto conceptus, novemque post conceptionem decursis
mensibus {Hic vox elevatur, et omnes genua flectunt}, in Bethlehem Judae nascitur
ex Maria Virgine factus Homo. {Hic autem in priori voce dicitur, et in tono passionis:}
Nativitas Domini nostri Jesu Christi secundum carnem.
{Quod sequitur, legitur in tono Lectionis consueto; et surgunt omnes.}
```
I added some line breaks to the text to make the example more readable.

Curly braces aren't used anywhere in the martyrology, and I don't think they would ever appear as normal text in a breviary. In Latin, at least, they're only being used now to mark hymns with the tune to which they are to be sung, but in this case colons are also used, e.g.,
```
[Hymnus Vespera]
{:H-Deustuorummilitum:}v. Deus tuórum mílitum
Sors, et córona, prǽmium,
…
```
The argument against curly braces is that they aren't used for rubrics anywhere else, and this inconsistency could make the syntax of the files harder to understand (it would be nice if we had a wiki that documented it).

**Comment by kraftbj** [comment]
Curly braces make sense. Instead of a wiki, could have a README.md in the root of the martyrology to note any unique aspects of it, this being one.

**Comment by APMarcello3** [comment]
Cf. also issue #694, which suggests incorporating conditionals into the martyrology.

**Comment by APMarcello3** [comment]
Cf. also issue #234, relative to the date in other languages in the martyrology.
