### ISSUE TITLE
Wrong English text for Gradual of Second Sunday of Lent

### ISSUE THREAD

**Issue by michaelsbradleyjr** [DivinumOfficium/divinum-officium#702]
The English text for the gradual of the Mass of the Second Sunday of Lent is incorrect.

**Comment by michaelsbradleyjr** [comment]
The English text for the tract of the same Mass is also incorrect.

**Comment by peterdiekertz** [comment]
What is the correct Version then?

Am 07.03.2017 6:42 nachm. schrieb "Michael Bradley ن" <
notifications@github.com>:

**Comment by michaelsbradleyjr** [comment]
Upon review, I see that the problem is rather that the English text for the gradual (*Ps 24:17–18*) is missing. The English text for the tract is correct; however, on the left-hand side (the Latin side) under *Tractus* the chapter and verse are incorrect: 105:1–1 is indicated, but it should be as on the right-hand side, 105:1-4.

**Comment by michaelsbradleyjr** [comment]
Also, on the right-hand side (the English side), there should be a *Tract* or (*Tractus*) subheading above the supplied text.
