### ISSUE TITLE
Gloria not entirely ommitted during Passiontide in the Parvum B.M.V. office

### ISSUE THREAD

**Issue by Geremia** [DivinumOfficium/divinum-officium#715]
"Gloria omittitur" appears in the Matutinum of the Parvum B.M.V. office, but it appears in all the other hours. Also, "Gloria omittitur" should've begun yesterday (Sunday) (or Saturday evening at Vespers?), whereas "Gloria omittitur" first began appearing in the Matutinum today (Monday).

The "hodie" office also still has the same problem.

I'm using Divino Afflatu.

**Comment by gregordick** [comment]
During Passiontide, the Gloria is omitted only at Mass, from responsories and from the invitatory.  In other places, it remains until the triduum.  I've had a quick look at the Divino afflatu Little Office, and the behaviour appears to be correct.  If I'm mistaken, could you please provide a link (using the "Cellphone" version) to a problematic office?

**Comment by Geremia** [comment]
@gregordick I think you're right. So the Gloria should not be omitted in the Matutinum of the Parvum B.M.V. office.
