### ISSUE TITLE
Vespers 3 July (Divino) wrongly are of the Octave

### ISSUE THREAD

**Issue by peterdiekertz** [DivinumOfficium/divinum-officium#746]
On 3 July (2017), Vespers are shown as Sexta die infra Octavam Ss. Petri et Pauli. ~ Feria major with commemoration of St. Leo. It should be of St. Leo (who is semiduplex), with commemoration of the Octave (which is an octava communis only).
The day of the Octave should also be called semiduplex, not feria major.

**Comment by mbab** [comment]
Closed by  77eebab

**Comment by peterdiekertz** [comment]
I still see this error.

**Comment by APMarcello3** [comment]
The error concerning 07-03 Vespers should be fixed by 4705dbc58 but I will leave this open for the question of the title of the days of the Octave in Divino rubrics.
