### ISSUE TITLE
Difference in Repositories?

### ISSUE THREAD

**Issue by benyanke** [DivinumOfficium/divinum-officium#757]
I'd love to start working on this in my free time, and I already have a local copy up and running on my webserver. However, I'm having trouble making sense of the multiple repos (`divinum-officium` and `divinum-officium-website`). What is the purpose of each, and which should I be using as my base if I'd like to start adding features on my own end to PR back?

**Comment by DLakomy** [comment]
Hello and welcome!
We work on `divinum-officium` repo.  I'm unsure what is the second one used for, precisely. It is synchronised with the former one from time to time.

**Comment by benyanke** [comment]
Probably would be good to update the readme. If someone knows what that second repo is for, I'd be happy to update both readmes.

**Comment by APMarcello3** [comment]
Hello Ben: 

Welcome aboard. Divinum-Officium-Website is essentially an identical copy of Divinum-Officium which only is used to update the live website. 

Thank you for your willingness to help with the Divinum Officium website!

God bless,

Fr. Albert Marcello, JCL
