### ISSUE TITLE
"Title" of Vespers is wrong

### ISSUE THREAD

**Issue by peterdiekertz** [DivinumOfficium/divinum-officium#766]
When viewing Vespers, the "title" of the web page is wrong ("Divinum Officium Vespera"). This title is shown as the name of the tab in my browser. I suppose it should be "Vesperae" like it's already shown in the selection menu for the hours.

**Comment by lukecaputo** [comment]
Vesperae is the plural of vespera. In the selection of the hours from the menu, it is referencing the collection of versera hours -  the versperae. In presenting the title of the web page and on the page itself, it is referencing a singular item of the vesperae - a vespera.

**Comment by peterdiekertz** [comment]
No. Vespera means evening. Vesperae = vespers is a word that only has a plural form, just like Laudes (Lauds).

**Comment by rl1234567890** [comment]
A cursory look to a printed  breviary confirms Peter's point.

**Comment by APMarcello3** [comment]
Closed by c06197508.

**Comment by rl1234567890** [comment]
I propose that this correction be applied also to the completion button, which presently reads "Vespera persolut.", so that it becomes "Vesperae persolut."
