### ISSUE TITLE
Correction needed

### ISSUE THREAD

**Issue by Sarto1** [DivinumOfficium/divinum-officium#772]
I found a minor typo in the 1910 version of today (Dominica XIII Post Pentecosten I. Septembris ~ Semiduplex Dominica minor) in the Lectio 1:

"quingénta quoque juga **boum** et quingentæ ásinæ"

I think it should be **bovum**.

**Comment by peterdiekertz** [comment]
Contrary to common intuition, boum is in fact the gen. pl. of bos. <https://en.wiktionary.org/wiki/bos#Latin> and it's printed like that in the breviary (and the Vulgate: <http://vulsearch.sourceforge.net/html/Job.html>).

**Comment by Sarto1** [comment]
Then I would like to apologise for my mistake, and thank you for this information!
