### ISSUE TITLE
Drawings on the front page

### ISSUE THREAD

**Issue by peterdiekertz** [DivinumOfficium/divinum-officium#779]
Would it be ok to replace the rather low-quality drawings on the "front page" (those which we find in printed breviaries before the beginnings of new sections) with better versions? I can scan them from a printed breviary that is now in the public domain.
The files are currently in web/www/horas as GIFs. Do they need to be GIFs and do they need to have the exact same size?

**Comment by rl1234567890** [comment]
OK with me.

**Comment by APMarcello3** [comment]
Please go ahead - use whatever file format is convenient, so long as they are relatively the same size.

**Comment by fiapps** [comment]
PNG (for images with few unique colors, like black and white/transparent) or JPEG (for continuous tone images) have smaller file size than GIF, and would therefore make the page load slightly faster.
