### ISSUE TITLE
Ember days should not be commemorated at Vespers; Oration at Ember day Vespers should be from the Sunday

### ISSUE THREAD

**Issue by peterdiekertz** [DivinumOfficium/divinum-officium#793]
Rubric at the Ember Wednesday and Friday of September:

[Oratio ad Laudes]
Et dicitur usque ad Nonam.
Ad Vesperas vero Oratio Dominicae praecedentis. Si autem Vesperae dicendae non sint de Feria, de ea nec fit Commemoratio.

**Comment by APMarcello3** [comment]
Closed by 890a75dd5.
