### ISSUE TITLE
Sancta Missa: English proper encroaches on other translations

### ISSUE THREAD

**Issue by rl1234567890** [DivinumOfficium/divinum-officium#819]
When the file with the  English proper for a saint has some texts that are only the same as in the common, these parts are shown also in the other translations.
For example, today is St. Albert the Great. The English proper has the text of the introit, which is the same as in C4a. If you look at the Italian translation, it will have the English introit, although it should have the text from the Italian C4a.

**Comment by peterdiekertz** [comment]
I suppose the solution is to remove these texts from the English Proprium
files.

Am 16.11.2017 3:14 vorm. schrieb "rl1234567890" <notifications@github.com>:

**Comment by rl1234567890** [comment]
That would be one solution. The other solution would be to change missa.pl so that it handles the proper correctly.

**Comment by rl1234567890** [comment]
Although I don't know perl, I did some investigation. The problem seems to be in /web/cgi-bin/horas/dialogcommon.pl
which is one of the modules loaded by mass.pl
If in lines 302-311 one substitutes Italianofor English, than it is Italian that encroaches.

`    if ($lang eq 'English')
    {
      # English layers on top of Latin.
      $base_sections = setupstring($basedir, 'Latin', $fname, 'resolve@' => RESOLVE_NONE);
    }
    elsif ($lang && $lang ne 'Latin')
    {
      # Other non-Latin languages layer on top of English.
      $base_sections = setupstring($basedir, 'English', $fname, 'resolve@' => RESOLVE_NONE);
    }
`

**Comment by fiapps** [comment]
This is how translations are designed to work: missing parts are taken from English.

The reason for the incorrect behavior is that the English translation contains sections that it should not contain, and so the solution is to remove these, as peterdiekertz said. The Polish translators, and particularly mbab, have been helping with this.

One could consider automatically searching for sections in the English translation that do not have a corresponding section in the Latin. This would indicate that these sections should be removed. However, such a check should not be done at run time, but as a part of database maintenance. This way, it will not slow down the website, and a human can review the changes to ensure that the sections really should be discarded.

**Comment by rl1234567890** [comment]
It seems to be a flaw in the design, which should be based on the Latin, not the English.
If the Latin indicates that a movable part is to be taken from the common, the program should look first in the common of the chosen vernacular and see if it is there. If it is not present, then use the English version. Analogously, if the Latin says that a movable part should be taken directly from from the Sancti file, the program should look first in the Sancti file of the vernacular of choice. Only if not present in the vernacular of choice, the program should resort to the English.
