### ISSUE TITLE
Resumed 6th Sunday After Epiphany has wrong Introit, Gradual, Offertory, and Communion

### ISSUE THREAD

**Issue by landondepasquale** [DivinumOfficium/divinum-officium#829]
The Resumed 6th Sunday after Epiphany (which was celebrated this year on November 19th) had the Introit, Gradual, Offertory, and Communion propers for the last Sunday after Pentecost instead of the 6th Sunday after Epiphany.

It should be the _Adorate Deum_ Mass, but instead lists the _Dicit Dominus_ Mass.

**Comment by peterdiekertz** [comment]
Sorry, but this was a wrong fix.
Dominicae quae superfuerunt post Epiphaniam use the propers Dicit Dominus etc. from the 23rd and 24th Sunday after Pentecost, when they are resumed before Advent.

**Comment by APMarcello3** [comment]
Fixed.
