### ISSUE TITLE
Automatic red initial code fails on matins of 2 November

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#840]
The code in `specials.pl` that adds "v. " to the beginning of lines does the wrong thing with the matins of 2 November. See the oratio at the end:
http://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=11-2-2017&command=prayMatutinum&version=Rubrics%201960&testmode=regular&lang2=English&votive=

`&Dominus_vobiscum2` is being turned into `v. &Dominus_vobiscum2`, which after further processing becomes `&Dominus vobiscum` in the HTML, with a big red "&."

This only happens at matins of that day, not at lauds or vespers.

The problematic code was added by @mbab in e6d3417. I simply report the bug, since I don't know whether it's better to check for an ampersand at the beginning of the line or move the substitution to a later point, after `&Dominus_vobiscum2` has been substituted.

**Comment by APMarcello3** [comment]
I have added a temporary workaround in dd0ef2c in the Latin and English versions of Commune/C9.

**Comment by rl1234567890** [comment]
Unfortunately the exact same fix doesn't work for Italian.
