### ISSUE TITLE
Missing oremus in commemorations due to use of common

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#902]
In 07f399d2, @mbab replaced three commemorations with the corresponding *oratio* from C2. This is a good idea in principle, but had the effect of eliminating the `$oremus` that must precede the *oratio* of the commemoration.

I leave it to you (especially mbab) to decide how best to fix this:

1. revert the commit;
2. modify the substitution so as to cause `$oremus` to be used;
3. modify the code to insert `$oremus` in such cases (if you do this, please test the code well).

**Comment by APMarcello3** [comment]
Commit https://github.com/DivinumOfficium/divinum-officium/commit/6a4d03dc31d84ed5261676ff0a444da2eb0015de fixes this issue via option 2 listed above.

**Comment by fiapps** [comment]
Sorry about this: it was my error. I hadn't picked up the latest change to specials.pl.

The extra $oremus lines in 6a4d03d didn't fix the problem I was having: instead they add an "Oremus/Let us pray/…" just before the antiphon of the commemoration.
