### ISSUE TITLE
Feria IV Quattuor Temporum in Adventu: Te Deum is shown

### ISSUE THREAD

**Issue by peterdiekertz** [DivinumOfficium/divinum-officium#904]
Feria IV Quattuor Temporum in Adventu: Te Deum is shown in Latin instead of the 3rd responsory.

All versions except Rubrics 1960.

**Comment by APMarcello3** [comment]
https://github.com/DivinumOfficium/divinum-officium/commit/f5cd16d20126a818cc6fbba03dd56614183d4f10 closes this issue due to a reference from Sancti/03-25, which had the Te Deum appended.
