### ISSUE TITLE
2018

### ISSUE THREAD

**Issue by peterdiekertz** [DivinumOfficium/divinum-officium#908]
The calendar for 2018 (and therefore all offices) don't work. I suppose we need these transfer tables?

**Comment by APMarcello3** [comment]
I have composed transfer tables for 1960 rubrics for 2018 and 2019. I will need someone to compose these for the other rubrical structures.

**Comment by peterdiekertz** [comment]
I haven't had to do with the tables before. I suppose this should work for Divino, based on how the previous files look.

**Comment by gregordick** [comment]
@peterdiekertz Thanks for doing the DA table.  I'll take a look at the DA Scripture transfer table.

**Comment by gregordick** [comment]
e483478 adds the remaining tables.  There might be some omissions, particularly in pre-Divino versions, but things are basically operational.  I'll deploy to the live site.
