### ISSUE TITLE
Wrong Italian antiphons of Vespers of the Holy Innocents

### ISSUE THREAD

**Issue by rl1234567890** [DivinumOfficium/divinum-officium#910]
It seems the Italian antiphons for Vespers of today are wrong. Instead of those of Christmas, they are the same as for Lauds. Is there anything I can do to fix this? Thanks!

PS

There is no problem for St. Stephen or St. John the Evangelist.

**Comment by APMarcello3** [comment]
https://github.com/DivinumOfficium/divinum-officium/commit/41e41c0a6ee9e17d371c801ee4414b32114c65fc should close this issue.
