### ISSUE TITLE
Nat1-0 Lectio1 Sancti rule not working

### ISSUE THREAD

**Issue by APMarcello3** [DivinumOfficium/divinum-officium#913]
Lines 603-607 in specmatins.pl are supposed to render the first two readings in Matins (1960 rubrics) from the occurring Scripture if Nat1-0 (Sunday within the Octave of Christmas) falls on December 29, 30, or 31. This rule does not seem to be working and is rendering the Scriptures from Christmas day (which is accurate if Nat1-0 falls on December 26, 27, or 28). 

If the rule "no commemoratio (rubrica 1960)" is removed, this partially solves the problem, although Lectio 2 in this case should be composed of (in the case of 2017) lections 2 & 3 from 12-31r; this also creates a separate issue because the commemoration of the nth day of the octave should vanish under 1960 rubrics.

**Comment by gregordick** [comment]
Relevant is the change e930c93 that I made four years ago to address issue 203:

```
commit e930c939804569fd92eb986f0b3cb717d11ddcaf
Author: Gregor Dick <igregord@gmail.com>
Date:   Sun Dec 8 21:59:03 2013 +0000

    Horrible fix for Nat1-0 Matins readings. Real fix will come eventually from calcalc. Closes issue 203.
```

calcalc is of course still not ready.  I'll see whether further jury-rigging is possible.

**Comment by gregordick** [comment]
Fix for the case where the commemoration is suppressed was pushed as d9cef52 and deployed.

**Comment by APMarcello3** [comment]
Gregor:

Thank you for your speedy work; however, Lectio 2 should be a contraction of Lectio 2 & 3 from the sanctoral occurring Scripture. 

I will reopen the issue.

**Comment by gregordick** [comment]
c3bbd76 contracts the lessons in the case where the file had to be re-read.
