### ISSUE TITLE
Commemorations sub unica conclusione/1955 version

### ISSUE THREAD

**Issue by Sarto1** [DivinumOfficium/divinum-officium#928]
Laudetur Iesus Christus!

I am not very well acquainted with the Rubrics of the 1955 version of the Breviarium Romanum, but today at Laudes (Feria VI infra Hebdomadam II post Epiphaniam ~ Ferial, Commemoratio: Ss. Marii, Marthæ, Audifacis, et Abachum martyrum), I noticed that the 2nd and 3rd oration did not have a conclusio. I know from the "1962" version that the conclusio is added after the 3rd oration according to the general rules.

Did the 1955 version only have a conclusio after the 1st oration, or is this an error?

**Comment by APMarcello3** [comment]
Should be corrected by d097933ec.
