### ISSUE TITLE
Semiduplex in 1955?

### ISSUE THREAD

**Issue by Sarto1** [DivinumOfficium/divinum-officium#929]
I was confused to see the rank of "Semiduplex" in the 1955 version of Divinum Officium, since - as is my knowledge - the rank had been suppressed in 1955, and feasts of this rank were then re-categorised as duplex or simplex.

**Comment by APMarcello3** [comment]
I have examined two altar Missals (a 1958 Pustet and a 1959 Desclée) and one breviary (a 1956 Mame Horae Omnes), and all of them retain the ranking of semiduplex in their labeling of certain days (e.g. Dominica infra Octavam Nativitatis, 01-22, 05-12, etc.). 

While I see your argument from Cum Nostra Hac Aetate 20, in approved liturgical texts published between 1956 and 1961, the ranking of feasts in the title of the feast day itself did not evidently change.

If you have access to any 1955-1960 liturgical texts and the ranking in the books differs from what is seen on the site, please submit the errata accordingly.
