### ISSUE TITLE
New Polish translations

### ISSUE THREAD

**Issue by efati** [DivinumOfficium/divinum-officium#938]
Polish translations of Psalms and other canticles come from the public domain translation done by Fr. Jakub Wujek (https://pl.wikisource.org/wiki/Biblia_Wujka_(1923)). It is a very respectable and important translation which is moreover very useful because it strictly follows the original Vulgate Latin source. However, the transcription (called „B”) is quite old and uses language forms which becomes more and more unintelligible. I have found another translation or another version of the translation done by Fr. Stanisław Styś (https://pl.wikipedia.org/wiki/Stanis%C5%82aw_Sty%C5%9B). It is a revised (not to say modernized) version of the Fr. Wujek translation. It is still very close to Latin original, but can be read as easily as any contemporary text.

I have recently contacted the provincial of the Jesuit order who have the copyrights for the translation and I'm happy to announce that they gave me permission to use the translation in Divinum Officium project. Therefore I would like to add the translation of Fr. Styś as an alternative to the existing one. It raises a couple of questions:

1. Following the recent addition of Pius XII psalter should I use for example `web/www/horas/Polski/Stys` directory for psalms?
2. An alternative solution would be to create a new top-level language, e.g. _Polski2_ or _PolskiS_. It may be necessary due to the differences of language style in other texts like antiphones and hymns. The new language _Polski2_ could default to _Polski_ in case of missing source files.
3. Another problem comes from different styles of writing personal pronouns. In Polish we used to write them with a small letter in the past, and nowadays we start with a capital letter. Personally, I prefer the new notation because we are used to it. Moreover, it is simple to programmatically (and dynamically) change all „On/Twój/Jego/…” into „on/twój/jego/…”. The inverse is impossible to automate.

What is your opinion?

**Comment by DLakomy** [comment]
Ad. 1. and 2. I haven't got an opinion; nonetheless, I would like to avoid showing two different „Polski” entries in the menu without any nesting/subdirectory. It would look strange to me.
Ad. 3. As I understand you would like to capitalise personal pronouns addressing the God (and the BMV, right?) in the source files and add an option to lowercase them? If so, I like the idea.

**Comment by efati** [comment]
Ad. 2. I think of a whole new directory structure `web/www/horas/Polski2` with subdirectories `psalms1`, `Psalterium` etc.
Ad. 3. Precisely.

**Comment by efati** [comment]
There is also one more solution:

4. Completely switch over to Fr. Styś's translation by replacing the contents of the `web/www/horas/Polski/psalms1` directory. But I expect there are people who like (and prefer) the original Fr. Wujek's version.

**Comment by DLakomy** [comment]
I think that 4. is not an option. There are people I know (including me) who really like the fact that, as you put it, the Fr. Wujek's translation strictly follows the original Vulgate Latin source. The newer translation could be a default option (it can be discussed), but abandoning the older one would be a great loss.

**Comment by efati** [comment]
I understand, accept, and respect that opinion.

However, I think that the translation of Fr. Styś is underestimated. I'm now comparing, verse by verse these two translations, and I must say that they are almost identical besides the grammar, transcription, orthography, and sometimes vocabulary. It is just a contemporary version of Fr. Wujek's translation, still being a word-for-word translation of Vulgate. I used it for several months for understanding the Latin text, and it proved to be simple, helpful, and precise.

**Comment by fiapps** [comment]
Since I don't know Polish, I can't evaluate 4. The choice between 1 and 2 depends on how extensive the change will be: if you only intend to introduce the translation by Fr. Styś for Psalms, 1 is sufficient. If antiphons or other text will be changed, then option 2 (or 4) is required, and I think it will indeed be necessary to change the antiphons in order to handle the case where the antiphon is the same as the beginning of the Psalm.

**Comment by efati** [comment]
The more I think about it the more I am convinced that the change will be quite massive…

Candidates for updates are in all directories: `Commune`, `Ordinarium`, `psalms1`, `Psalterium`, `Sancti`, `Tempora`, to a lesser extent `Martyrologium`. Interestingly, files in `Sancti` and `Tempora` directories capitalise personal pronouns addressing God, so we already have some inconsistencies.

It becomes clear that it is necessary to apply solution 2 or 4, but 4 has just been rejected. We are left with solution 2.

**Comment by DLakomy** [comment]
I think 2 is a good way to go. I’d like to add few words to my previous opinion:
> I would like to avoid showing two different „Polski” entries in the menu without any nesting/subdirectory.

I guess the mechanism allowing `Polski2` to fallback to `Polski` has yet to be implemented. What I meant before is to provide a feature on the frontend, that would present the alternative Polish in the other way than treating them as separate languages. This is just a minor not-very-important suggestion. Apart from that I'm ok with this option.

**Comment by mbab** [comment]
The **2** is only solution, but in my opinion **only** after all work on current translation is finished.

**Comment by DLakomy** [comment]
Yesterday I was told that the Polish text is almost unreadable. I think we could start implementing another translation at least partially (psalms and readings), before the current one is 100% finished.

I'm not sure, though, if we should use Fr. Styś's translation (will it be a great improvement?), or consider using _Biblia Tysiąclecia_, if permission is granted (I know it's a controversial choice). I haven't got an opinion. I would prefer Fr. Styś's version but if the readability is a problem, I'm not sure if it's enough.

**Comment by efati** [comment]
I think Fr. Styś's version is much (MUCH) better translation than _Biblia Tysiąclecia_. It is just Fr. Wujek's version but using modern language. I have prepared the Psalms, and **I have permission** to use it in this project. On paper.

**Comment by DLakomy** [comment]
Ok. So the only thing we need, is some kind of mechanism allowing _PolskiN_ (_PolskiNewer_, or however we call it) to default to _Polski_, unless we want to do a copy-paste thing and struggle to keep it in sync.

@efati Does the permission apply to the whole Bible? When I asked for permission several years ago, I was told, if remember correctly, that the copyrights are splitted among two provinces (there were two revisors).

@mbab Are you able to say if it’s difficult to implement? I mean a mechanism allowing to default _PolskiN_ to _Polski_, which in turn should default to _English_?

**Comment by efati** [comment]
The permission applies to the whole Bible.

**Comment by DLakomy** [comment]
@efati Very good. If so, I'd prefer not to use a translation name like "*_Stys", since there was more than one revisor. I'll try to think over the fallback mechanism implementation soonish. By the way, if I remember correctly, Fr. Tadeusz Karyłowski's hymns translations are in Public Domain now. I don't think we will be changing to them soon (if ever), but I think we should take that (and similar changes other than the Bible translation itself) into consideration when choosing a naming schema.

@fiapps Seems good to me.

**Comment by DLakomy** [comment]
@efati The fallback mechanism is in place, so we can add `Polski-Newer` language (any better name? I would avoid using "Stys", as I've said before; apart from that I haven't got any preference). It can be done in stages. I suggest starting with the Psalterium.

There is still a problem with the pronouns (to capitalise or not). I think that they should be capitalised, since it's possible to automatically change them to lower-case, as you've already stated before. I would consider opening a separate issue for that, if it's going to be posponed.

I suggest that we close this issue, when the new translation is partially done (I don't think we need to keep it open till it's 100% ready, as it's going to be a long and vaguely defined process).

**Comment by efati** [comment]
I am sorry for the delay but finally I have managed to upload the translations. See  #1045.

**Comment by DLakomy** [comment]
Tested on PROD. It seems to be ok. It's indeed a bit easier to read.

I'm not sure when we should close this issue.

**Comment by DLakomy** [comment]
I've added a laconic note to `credits.html` in c7f8b0c.
