### ISSUE TITLE
Warnings about missing octaves

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#941]
The recent elimination of the octaves of St. Lawrence and of the Immaculate Conception is causing warnings to appear in the offices of the days that follow (with 1960 rubrics). The [Lauds of St. Giacinta Mariscotti](http://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=8-17-2018&command=prayLaudes&version=Rubrics%201960&testmode=regular&lang2=English&votive=) have these warnings:

> Sancti/08-15r Octava 2 missing
> 
> Sancti/08-10 Octava 2 missing

At Vespers of the same day, the warning is "Sancti/08-15 Octava 2 3 missing."

The warnings are produced because the prayers in `Sancti/08-10` and `Sancti/08-15r` for commemorating the octaves are conditional on the rubrics used, but the commemorations in the offices of the following days contain references (e.g. `@Sancti/08-15r:Octava`) that don't have an appropriate conditional. Since I'm unsure exactly what the condition should be, I leave the resolution to you. Problematic offices include:

* Sancti/08-17
* Sancti/08-19
* Sancti/08-20
* Sancti/08-21

**Comment by APMarcello3** [comment]
Closed by 5f327fd6f.
