### ISSUE TITLE
fecundas

### ISSUE THREAD

**Issue by Sarto1** [DivinumOfficium/divinum-officium#951]
I have seen that sometimes the word "fecunda..." is written in 3 different ways:

Fœcundas, fecundas and fæcundas.

Maybe this could be changed so that there is only one way to write this word (my Breviary says "fœcundas").

Especially today in the 1955 version, there is the oratio of St. Thomas with "et sancta operatióne fecúndas", and the commemoration of St. John of God with "Ecclésiam tuam nova prole fœcundásti".

**Comment by DLakomy** [comment]
In my breviary ('60) it's “fecúndas”. If I remember correctly, we used to stick to the ortography used in the books printed in '60s. Can anyone confirm?

**Comment by rl1234567890** [comment]
Lewis & Short argue that is should be [fecundus, a, um](http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.04.0059%3Aentry%3Dfecundus)

> fēcundus (sometimes erroneously foecund-and faecund-, but v. Varr. ap. Gell. 16, 12 fin., and ap. Non. 54, 8), a, um, adj. from ‡ feo, whence also fetus, femina, fenus, etc., cf. felix,

**Comment by Sarto1** [comment]
Yes, but there are different versions of spelling within the 1955 version. I am not arguing to change a correct spelling, but to make it uniform. As I have stated, within the orations, there are two different forms.

**Comment by DLakomy** [comment]
I agree. So it should be „fecúndum” (+declension) everywhere.

**Comment by fiapps** [comment]
Yes. In the particular case of the *orationes* mentioned, the 1961 *editio typica* has “fecúndas” on March 7 and “fecundásti” on March 8.

Fr. Marcello has been gradually making changes to standardize on the 1961 spellings, but there are a lot of texts to correct.
