### ISSUE TITLE
Wrong Oratio

### ISSUE THREAD

**Issue by Sarto1** [DivinumOfficium/divinum-officium#974]
Today in the "Divino Afflatu" version, the Oratio for Vespers is wrong. It should be the Sacred Heart Oratio ("Deus, qui nobis in Corde Filii tui..."), since it is the I. Vespers for the Octave Day. Instead, the Oratio from last Sunday – Dominica III Post Pentecosten, infra Octavam SSmi Cordis D.N.J.C ~ Semiduplex Dominica minor – is displayed ("Protector in the sperantium...").

The same issue with tomorrow (the Octave Day): the Vespers Oratio is from the 3rd Sunday after Pentecost.

**Comment by APMarcello3** [comment]
Closed by c8f696669
