### ISSUE TITLE
Octave Day of the Sacred Heart

### ISSUE THREAD

**Issue by Sarto1** [DivinumOfficium/divinum-officium#975]
The "Divino afflatu" assigns to the Feast of the Most Sacred Heart an Octava Privilegiata III. ordinis. Does this make the Octave Day a duplex, or a semiduplex? On the website, it says semiduplex, but the antiphons are repeated. I have not found any information regarding this issue (except for octaves of the 1st and 2nd order, but not for ones of the 3rd order).

**Comment by APMarcello3** [comment]
The day is a duplex major. Closed by 5cafdf2b3.
