### ISSUE TITLE
III Sunday after Pentecost has prayer of the Sacred Heart

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#978]
It looks like something is wrong with the edits recently made for #975. With the 1960 rubrics, the III Sunday after Pentecost now has the prayer for the feast of the Sacred Heart instead of the prayer for the Sunday: http://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=6-10-2018&command=prayLaudes&version=Rubrics%201960&testmode=regular&lang2=English&votive=

The same thing happens on ferial days that should have that Sunday's prayer:
http://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=06-15-2018&command=prayLaudes&version=Rubrics%201960&testmode=regular&lang2=English&votive=

**Comment by APMarcello3** [comment]
Closed by 39fdc90c2.

**Comment by fiapps** [comment]
I updated my fork, and that commit did not change the prayer that appears. I still see the prayer for the Sacred Heart.
