### ISSUE TITLE
III Sunday after Pentecost still has prayer of the Sacred Heart

### ISSUE THREAD

**Issue by fiapps** [DivinumOfficium/divinum-officium#980]
A week ago I reported (see #978) that with the 1960 rubrics, the III Sunday after Pentecost now has the prayer for the feast of the Sacred Heart instead of the prayer for the Sunday. A commit was pushed, and the issue was closed, but the commit did not fix the problem, as can be seen by clicking on the links in that issue, which I reproduce below. As far as I can tell, that commit (39fdc90) had no effect whatsoever.

I commented that the issue was not fixed, but the issue remains closed, so I have to open a new one for the same problem.

Here is the problem on the Sunday: http://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=6-10-2018&command=prayLaudes&version=Rubrics%201960&testmode=regular&lang2=English&votive=

The same thing happens on ferial days that should have that Sunday's prayer:
http://www.divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=06-15-2018&command=prayLaudes&version=Rubrics%201960&testmode=regular&lang2=English&votive=

**Comment by APMarcello3** [comment]
Closed by b6a9229ee
