### ISSUE TITLE
Trident 1570 Ad Lauds

### ISSUE THREAD

**Issue by Esther1957** [DivinumOfficium/divinum-officium#994]
The entire office of Lauds for the year 1570 is wrong.  All of the Psalm verses are wrong and the entire 2nd half of the office in English is missing.  I say only the 1570 office and saw this on 2 August 2018 at 6:30 am.   Forgpt to add this office was for St. Stephan, Pope and Martyr on 2 August 2018.

**Comment by APMarcello3** [comment]
Closed by 43c6c8e86e3a2dc23c58623153f6615b1216ec83

**Comment by Esther1957** [comment]
Thank You very much!

bjr
