### ISSUE TITLE
Duplicate Ascension in 2019 calendar

### ISSUE THREAD

**Issue by petermottola** [DivinumOfficium/divinum-officium#995]
A user reported to me that for date 6-6-2019, Rubrics 1960, Office gives "S. Norberti Episc. et Confessóris ~ III. classis | Scriptura: Feria V infra Hebdomadam post Ascensionem" but Mass is given as "In Ascensione Domini ~ I. classis".  This date would be the octave day of Ascension in calendars where it has an octave.
"In Ascensione Domini    I. classis" is also (rightly) listed on May 30 of that year.
(Same Octave behavior can be observed on 05-28-2020.)

**Comment by APMarcello3** [comment]
Closed by f2b76a0db
