### ISSUE TITLE
All Hours on one page

### ISSUE THREAD

**Issue by FrPolley** [DivinumOfficium/divinum-officium#997]
It would be nice to have the option of viewing all of the hours for the day on one HTML page, the way it used to be. It may be convenient for some to have only one hour per page, but if you want to take the day, download it, and convert it into an ebook for traveling, the multiple pages makes it a nuisance. 
(Of course, having the ability to output a day into an ebook format like epub, or mobi would be even better!)

**Comment by fiapps** [comment]
There are already two offline tools in the project for generating ePub files. The output of the newer of the two, `epubgen2`, can be downloaded from http://breviarium.srubarovi.cz. Both ePub and MOBI formats are available.
