### ISSUE TITLE
1910 Office

### ISSUE THREAD

**Issue by Sarto1** [DivinumOfficium/divinum-officium#999]
I have found some problems with the 1910 version:

– the Suffragium for Ss. Peter and Paul has this passage in the Oratio: "de profúndo pelagi~ liberávit:"

– The punctuation, and the apostrophes are mostly missing (thus making the correct pronunciation a bit complicated); especially Antiphones are lacking them

– Today, St. Romanus of Rome has changed genders: Commemoratio S. Romanæ Martyris (it's beato Romano in the Oratio, though)

**Comment by APMarcello3** [comment]
Errors fixed by c22a34e. Correction of punctuation and apostrophes is ongoing.
